### ISSUE TITLE
$PAGE->set_url() in sessions.php

### ISSUE THREAD

**Issue by michael-milette** [danmarsden/moodle-mod_attendance#105]
In session.php, could you please make the following change:

$PAGE->set_url($att->url_sessions());

to

$PAGE->set_url($att->url_sessions(array('action'=>$pageparams->action)));

Besides the fact that $PAGE->url should never resolve to an invalid URL, the reason I ask is because I have a plugin which modifies the URL of the page to in order alter its appearance. However, because $PAGE->url doesn't include the action parameter, the page ends up displaying a message which says "A required parameter (action) was missing."

There may be other Moodle code which also expects a valid $PAGE->url.

Best regards,

Michael Milette

**Comment by danmarsden** [comment]
sure! - any chance you could file a pull request with the change?

**Comment by michael-milette** [comment]
As requested Dan. See https://github.com/danmarsden/moodle-mod_attendance/pull/106

Best regards,

Michael
