### ISSUE TITLE
Allow grade with decimal

### ISSUE THREAD

**Issue by danmarsden** [danmarsden/moodle-mod_attendance#111]
As grades with decimals are allowed by Moodle, it would be a good idea I think to have attendance allowing it too.
We've made a quick patch in our Moodle and so far so good, everythings still working.
Change mdl_attendance_statuses grade column to decimal(10,5)
In \mod\attendance\preferences.php, set both $newgrade and $grade to PARAM_FLOAT instead of PARAM_INT on line #55 and #94
I know PARAM_FLOAT don't live well with comma as decimal separator but I don't know what the official Moodle way to handle it.

Copied from: https://tracker.moodle.org/browse/CONTRIB-5597

**Comment by davosmith** [comment]
This has already been integrated independently at: https://github.com/danmarsden/moodle-mod_attendance/commit/5ed33cc95053daad83102a5668a2f2849d8ca4d3

**Comment by danmarsden** [comment]
Thanks Davo - I vaguely remembered it happening but needed to shift everything out of the moodle tracker as I'd like to have the components in JIRA disabled.
