### ISSUE TITLE
Attendance in Metacourse showing Dropped Students

### ISSUE THREAD

**Issue by danmarsden** [danmarsden/moodle-mod_attendance#118]
Moved from: https://tracker.moodle.org/browse/CONTRIB-4625

We are a Moodle 2.4 school.  We recently implemented Metacourses.  When we use a Metacourse, we are having difficulty - and it is a but confusing. 

Let's say student A is enrolled in the ABC program.  Initially she is enrolled in ABC-101-1 - however she was dropped form that course.  She then signed up again - but this time for ABC-101-2.  

The two courses are children to a metacourse ABC-101-1,2.  The affected student is now currently listed as a dropped student in the attendance activity contained in the metacourse (ABC-101-1,2).  The student appears as a student in ABC-101-2.  They are no longer enrolled as far as we can tell in ABC-101-1.  Is there a way to "refresh" the attendance module?  Has anyone else ever seen this?

Thanks for any help that can be provided....

**Comment by danmarsden** [comment]
comment copied from tracker: 
this was also reported in the forums here:
https://moodle.org/mod/forum/discuss.php?d=235634
This isn't something I'll have time to work on as a volunteer at the moment but patches/funding are always welcome.

**Comment by Syxton** [comment]
changed the sql in get_users() to 

            $sql = "SELECT ue.userid, MIN(ue.status) as status,
                           $mintime AS mintime,
                           $maxtime AS maxtime
                      FROM {user_enrolments} ue
                      JOIN {enrol} e ON e.id = ue.enrolid
                     WHERE ue.userid $sql
                           AND e.status = :estatus
                           AND e.courseid = :courseid
                  GROUP BY ue.userid";

**Comment by danmarsden** [comment]
Thanks Dave - I've merged that into the master branch - would be good if someone else could verify this as well and I'll cherry pick into the other branches.
