### ISSUE TITLE
When no session is generated within a selected range "Sessions successfully generated" is shown

### ISSUE THREAD

**Issue by barrysspace** [danmarsden/moodle-mod_attendance#120]
Steps to reproduce:

1.  Add a new session and tick "Create multiple sessions"
2.  Leave the Session Date as today's date.
3. Change the Session end date to tomorrows date.
4. Select an incorrect Session day i.e. if today is Wednesday and tomorrow is Thursday, select any day other than Wednesday or Thursday.
5. Click Add Session.

*Expected Result:*
A redirect message should appears saying "Error in generating sessions"
*Actual Result:*
A redirect message appears saying "Sessions successfully generated"

**Comment by danmarsden** [comment]
Thanks Barry,

which version of the plugin were you using? - this sounds similar to:
https://github.com/danmarsden/moodle-mod_attendance/commit/a9146bef1fac6723a6f41a73a553672fb75fa49f

**Comment by barrysspace** [comment]
Hi Dan, Sorry I didn't check if there was a fix in a later version already. We are using the 2.7 version so we didn't have that fix yet. Any chance of backporting it to 2.7?

**Comment by danmarsden** [comment]
thanks Barry, I've been out of the office for a week but I've just merged the backport you added.
