### ISSUE TITLE
Report seems to show incorrect grades when using 2 status set

### ISSUE THREAD

**Issue by antonio-c-mariani** [danmarsden/moodle-mod_attendance#127]
When using two different status set the report seems to show incorrect grades. The attached images shows  a cenario where I expected:
student P 1 - 4.0 / 6.0 - 66.7%
student U 1 - 6.0 / 6.0 - 100 %
but the report showed:
student P 1 - 4.0 / 4.0 - 100 %
student U 1 - 6.0 / 4.0 - 100 %

![1-att_sets](https://cloud.githubusercontent.com/assets/10731910/8767917/89d80694-2e43-11e5-9c96-6df043df1bc5.png)
![2-att_set_1](https://cloud.githubusercontent.com/assets/10731910/8767916/89802cc6-2e43-11e5-80e2-ba1ddff45969.png)
![3-att_set_2](https://cloud.githubusercontent.com/assets/10731910/8767912/8955bcf2-2e43-11e5-9141-6f94ce2efc45.png)
![4-att_ses1](https://cloud.githubusercontent.com/assets/10731910/8767911/8954c86a-2e43-11e5-867f-a9fca3c5508b.png)
![5-att_ses2](https://cloud.githubusercontent.com/assets/10731910/8767915/897ff300-2e43-11e5-8b12-fbe13eca0015.png)
![6-att_rep](https://cloud.githubusercontent.com/assets/10731910/8767913/8956a194-2e43-11e5-9f8a-2caf88d6d4f1.png)
![7-att_grade](https://cloud.githubusercontent.com/assets/10731910/8767914/897a8fe6-2e43-11e5-8b7f-e5c43a8ffc46.png)

**Comment by danmarsden** [comment]
Thanks for the report - the way that table is built is over-complicated and the function that obtains the maxgrade doesn't take into account the status set on each item within the report. It doesn't look like this will be a simple fix and is not something I'll have time to work on as a volunteer.

I'm happy to review any community developed patches or if you have funding/budget to pay for my time to fix this let me know.

**Comment by antonio-c-mariani** [comment]
Hi Dan,

There is a pull request that try to fix this.

Antonio Carlos Mariani

**Comment by danmarsden** [comment]
Antonio - is this one completely resolved now or is there still something missing?

**Comment by antonio-c-mariani** [comment]
It seems ok now.

**Comment by danmarsden** [comment]
cool - thanks.
