### ISSUE TITLE
Updating a status variable to have empty acronym or description

### ISSUE THREAD

**Issue by barrysspace** [danmarsden/moodle-mod_attendance#129]
If you update a status variable to have an empty acronym or description nothing happens to the acronym or description.  If you also update the grade to be empty the acronym or description will remain unchanged but the grade will become zero.

It would be better to prevent updating any fields of a status variable if either the acronym or description are set to be empty.  The user should also be notified about their error and that the record was not updated.

**Comment by danmarsden** [comment]
fixed in 7fd4b431b179b12972851821f1c2ac09613a796d Thanks!
