### ISSUE TITLE
Upgrade isues with attendance

### ISSUE THREAD

**Issue by heather-williams** [danmarsden/moodle-mod_attendance#139]
Version 2011071602 (attforblock) creates the following tables on install:

mdl_attendance_log
mdl_attendance_sessions
mdl_attendance_statuses
mdl_attforblock

When trying to upgrade from 2011071602 to version 2015040500 you get the following error:

-->mod_attendance
Default exception handler: DDL sql execution error Debug: Table 'mdl_attendance_sessions' already exists
CREATE TABLE mdl_attendance (
    id BIGINT(10) NOT NULL auto_increment,
    course BIGINT(10) NOT NULL DEFAULT 0,
    name VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci,
    grade BIGINT(10) NOT NULL DEFAULT 100,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_atte_cou_ix (course)
)
 ENGINE = InnoDB
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE = utf8_general_ci
 COMMENT='Attendance module table'
;
CREATE TABLE mdl_attendance_sessions (
    id BIGINT(10) NOT NULL auto_increment,
    attendanceid BIGINT(10) NOT NULL DEFAULT 0,
    groupid BIGINT(10) NOT NULL DEFAULT 0,
    sessdate BIGINT(10) NOT NULL DEFAULT 0,
    duration BIGINT(10) NOT NULL DEFAULT 0,
    lasttaken BIGINT(10),
    lasttakenby BIGINT(10) NOT NULL DEFAULT 0,
    timemodified BIGINT(10),
    description LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    descriptionformat TINYINT(2) NOT NULL DEFAULT 0,
    studentscanmark TINYINT(1) NOT NULL DEFAULT 0,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_attesess_att2_ix (attendanceid)
, KEY mdl_attesess_gro2_ix (groupid)
, KEY mdl_attesess_ses2_ix (sessdate)
)
 ENGINE = InnoDB
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE = utf8_general_ci
 COMMENT='attendance_sessions table retrofitted from MySQL'
;
CREATE TABLE mdl_attendance_log (
    id BIGINT(10) NOT NULL auto_increment,
    sessionid BIGINT(10) NOT NULL DEFAULT 0,
    studentid BIGINT(10) NOT NULL DEFAULT 0,
    statusid BIGINT(10) NOT NULL DEFAULT 0,
    statusset VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci,
    timetaken BIGINT(10) NOT NULL DEFAULT 0,
    takenby BIGINT(10) NOT NULL DEFAULT 0,
    remarks VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_attelog_ses2_ix (sessionid)
, KEY mdl_attelog_stu2_ix (studentid)
, KEY mdl_attelog_sta2_ix (statusid)
)
 ENGINE = InnoDB
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE = utf8_general_ci
 COMMENT='attendance_log table retrofitted from MySQL'
;
CREATE TABLE mdl_attendance_statuses (
    id BIGINT(10) NOT NULL auto_increment,
    attendanceid BIGINT(10) NOT NULL DEFAULT 0,
    acronym VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
    description VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
    grade SMALLINT(3) NOT NULL DEFAULT 0,
    visible TINYINT(1) NOT NULL DEFAULT 1,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_attestat_att2_ix (attendanceid)
, KEY mdl_attestat_vis2_ix (visible)
, KEY mdl_attestat_del2_ix (deleted)
)
 ENGINE = InnoDB
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE = utf8_general_ci
 COMMENT='attendance_statuses table retrofitted from MySQL'
Error code: ddlexecuteerror
* line 449 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
* line 910 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 76 of /lib/ddl/database_manager.php: call to mysqli_native_moodle_database->change_database_structure()
* line 412 of /lib/ddl/database_manager.php: call to database_manager->execute_sql_arr()
* line 364 of /lib/ddl/database_manager.php: call to database_manager->install_from_xmldb_structure()
* line 663 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
* line 420 of /lib/upgradelib.php: call to upgrade_plugins_modules()
* line 1615 of /lib/upgradelib.php: call to upgrade_plugins()
* line 171 of /admin/cli/upgrade.php: call to upgrade_noncore()

!!! DDL sql execution error !!!
!! Table 'mdl_attendance_sessions' already exists
CREATE TABLE mdl_attendance (
    id BIGINT(10) NOT NULL auto_increment,
    course BIGINT(10) NOT NULL DEFAULT 0,
    name VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci,
    grade BIGINT(10) NOT NULL DEFAULT 100,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_atte_cou_ix (course)
)
 ENGINE = InnoDB
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE = utf8_general_ci
 COMMENT='Attendance module table'
;
CREATE TABLE mdl_attendance_sessions (
    id BIGINT(10) NOT NULL auto_increment,
    attendanceid BIGINT(10) NOT NULL DEFAULT 0,
    groupid BIGINT(10) NOT NULL DEFAULT 0,
    sessdate BIGINT(10) NOT NULL DEFAULT 0,
    duration BIGINT(10) NOT NULL DEFAULT 0,
    lasttaken BIGINT(10),
    lasttakenby BIGINT(10) NOT NULL DEFAULT 0,
    timemodified BIGINT(10),
    description LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    descriptionformat TINYINT(2) NOT NULL DEFAULT 0,
    studentscanmark TINYINT(1) NOT NULL DEFAULT 0,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_attesess_att2_ix (attendanceid)
, KEY mdl_attesess_gro2_ix (groupid)
, KEY mdl_attesess_ses2_ix (sessdate)
)
 ENGINE = InnoDB
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE = utf8_general_ci
 COMMENT='attendance_sessions table retrofitted from MySQL'
;
CREATE TABLE mdl_attendance_log (
    id BIGINT(10) NOT NULL auto_increment,
    sessionid BIGINT(10) NOT NULL DEFAULT 0,
    studentid BIGINT(10) NOT NULL DEFAULT 0,
    statusid BIGINT(10) NOT NULL DEFAULT 0,
    statusset VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci,
    timetaken BIGINT(10) NOT NULL DEFAULT 0,
    takenby BIGINT(10) NOT NULL DEFAULT 0,
    remarks VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_attelog_ses2_ix (sessionid)
, KEY mdl_attelog_stu2_ix (studentid)
, KEY mdl_attelog_sta2_ix (statusid)
)
 ENGINE = InnoDB
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE = utf8_general_ci
 COMMENT='attendance_log table retrofitted from MySQL'
;
CREATE TABLE mdl_attendance_statuses (
    id BIGINT(10) NOT NULL auto_increment,
    attendanceid BIGINT(10) NOT NULL DEFAULT 0,
    acronym VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
    description VARCHAR(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
    grade SMALLINT(3) NOT NULL DEFAULT 0,
    visible TINYINT(1) NOT NULL DEFAULT 1,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
CONSTRAINT  PRIMARY KEY (id)
, KEY mdl_attestat_att2_ix (attendanceid)
, KEY mdl_attestat_vis2_ix (visible)
, KEY mdl_attestat_del2_ix (deleted)
)
 ENGINE = InnoDB
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE = utf8_general_ci
 COMMENT='attendance_statuses table retrofitted from MySQL'
Error code: ddlexecuteerror !!
!! Stack trace: * line 449 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
* line 910 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database-&gt;query_end()
* line 76 of /lib/ddl/database_manager.php: call to mysqli_native_moodle_database-&gt;change_database_structure()
* line 412 of /lib/ddl/database_manager.php: call to database_manager-&gt;execute_sql_arr()
* line 364 of /lib/ddl/database_manager.php: call to database_manager-&gt;install_from_xmldb_structure()
* line 663 of /lib/upgradelib.php: call to database_manager-&gt;install_from_xmldb_file()
* line 420 of /lib/upgradelib.php: call to upgrade_plugins_modules()
* line 1615 of /lib/upgradelib.php: call to upgrade_plugins()
* line 171 of /admin/cli/upgrade.php: call to upgrade_noncore()

Stepping through 2.4 2.2->2.4->2.7 does not result in error

**Comment by danmarsden** [comment]
yes - we no longer support upgrades from the older attforblock in the latest code. It required a very hacky patch that abused the version.php file. Sounds like you figured it out in the end. The patch that removed the hacky stuff is 3d00b1cc16bc5b775ad65d10d49d66af61cdc9c#diff-5bbd3ccd25214f9956eea7e9f714bc08

Hopefully there shouldn't be many other people running 2.2 anymore....
