### ISSUE TITLE
PHP Fatal error:  Using $this when not in object context

### ISSUE THREAD

**Issue by NMCPaul** [danmarsden/moodle-mod_attendance#141]
Whenever a user clicks the green dot to take attendance, they get a white screen and I get the following error in my PHP error logs:

`[20-Aug-2015 09:08:21 America/Detroit] PHP Fatal error:  Using $this when not in object context in /path/to/moodle/install/mod/attendance/take.php on line 53`

Line 53 is:

`$allowedgroups = groups_get_activity_allowed_groups($this->cm);`

If I change that line to:

`$allowedgroups = groups_get_activity_allowed_groups($cm);`

it appears to work.

We're running Moodle 2.9+ (2015051101.00) and mod_attendance (master branch, 2015062900).

**Comment by danmarsden** [comment]
Thanks! - all fixed, sorry about that! the master branch does occasionally contain some changes that "should work" but may not have been tested a lot.
