### ISSUE TITLE
Debug Notice in Moodle 2.9 when student tracks his attendance 

### ISSUE THREAD

**Issue by Kathrin84** [danmarsden/moodle-mod_attendance#147]
Hi Dan,

as we are updating to Moodle 2.9, I got the following message when a student tracks his attendance:

Fields list in snapshot record does not match fields list in 'attendance_log'. Record is missing fields: id
line 793 of /lib/classes/event/base.php: call to debugging()
line 900 of /mod/attendance/locallib.php: call to core\event\base->add_record_snapshot()
line 60 of /mod/attendance/attendance.php: call to attendance->take_from_student()

Notice: Undefined property: stdClass::$id in /var/www/html/moodle_dev/lib/classes/event/base.php on line 797
This page did not call $PAGE->set_url(...). Using https://moodle-dev.uni-ulm.de/mod/attendance/attendance.php
line 560 of /lib/pagelib.php: call to debugging()
line 768 of /lib/pagelib.php: call to moodle_page->magic_get_url()
line 48 of /blocks/login_userinfo/renderer.php: call to moodle_page->__get()
line 141 of /blocks/login_userinfo/block_login_userinfo.php: call to block_login_userinfo_renderer->login_userinfo()
line 288 of /blocks/moodleblock.class.php: call to block_login_userinfo->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 973 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1025 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 473 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 30 of /theme/bootstrapbase/layout/embedded.php: call to core_renderer->standard_head_html()
line 1015 of /lib/outputrenderers.php: call to include()
line 945 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 881 of /lib/outputrenderers.php: call to core_renderer->header()
line 2674 of /lib/weblib.php: call to core_renderer->redirect_message()
line 65 of /mod/attendance/attendance.php: call to redirect()

Kind regards,
Kathrin

**Comment by danmarsden** [comment]
Hi Kathrin, 

it sounds like you haven't updated the attendance plugin code. You should always upgrade your 3rd party plugins when upgrading Moodle. Can you please upgrade to the latest version available for moodle 2.9? 

If you have upgraded can you please provide the version number of the attendance plugin you have installed?

**Comment by Kathrin84** [comment]
Hi Dan,

I've updated all the plugins Moodle showed me that there are updates available because there's a newer version of them in the plugins repo.

Now, I've downloaded your latest code from here and now the notice does not appear any more when a student tracks the attendance himself.

Sorry about the circumstances. 
You can close this ticket.

Kind regards,
Kathrin

**Comment by danmarsden** [comment]
thanks for letting us know.
