### ISSUE TITLE
Fatal error when trying to take attendance in META course with groups/groupings

### ISSUE THREAD

**Issue by NMCPaul** [danmarsden/moodle-mod_attendance#148]
Whenever the instructor of a META course tries to take attendance for a group, we get the following in the PHP error logs:
```
[01-Sep-2015 11:18:05 America/Detroit] PHP Notice:  Undefined variable: groupid in /usr/local/moodle2/NMC/app/mod/attendance/take.php on line 55
[01-Sep-2015 11:18:05 America/Detroit] Default exception handler: You can't take attendance for group "CRN 1404 MWF 11:45-12:45" Debug: 
Error code: cannottakeforgroup
* line 57 of /mod/attendance/take.php: moodle_exception thrown
```
It works just fine if we take attendance for the course itself, just not in any groups. We're running the most recent version of 2.9.1+ as well as the most recent version of the master branch of your code.  Please let me know if you need any more information to diagnose (I'm not 100% up on how groups/groupings/meta courses work, so I'm unsure exactly what would be useful here).

**Comment by danmarsden** [comment]
Thanks for the report - I made some changes recently to the group handling to make it easier to read in the code, but obviously missed a parameter conversion. Often the master branch in the github repo may contain code that hasn't been tested as well as I would like.. This should all be fixed now.
