### ISSUE TITLE
Feature request: make tab temporary users optional with a global setting

### ISSUE THREAD

**Issue by Kathrin84** [danmarsden/moodle-mod_attendance#154]
Hi Dan,

I've installed the latest version of your plugin and have seen that there's the new functionality 'temporary users'. In our setting, this new feature should not be visible and usable.
Is it possible that you could build a global setting for enabling or disabling this feature through the admin?

We would need it as soon as possible. If you don't have any time at the moment for implementing such a setting, I could hire a developer for this issue.

Greetz,
Kathrin

**Comment by danmarsden** [comment]
I'm always available for hire - I work for the Moodle Partner Catalyst IT, drop me a private e-mail for details on our rates :-)

Although I can see this being useful and might work on it as a volunteer at some point I can't give you any guaranteed timeframes unless funding is provided for my time.

It's also possible that one of the other community developers monitoring these issues might throw something together quickly for you. It should be pretty straight-forward to add.

**Comment by davosmith** [comment]
I might see if I have a moment to look at this - the feature was developed by Synergy Learning for one of our clients and I handled pushing it back into the official repo, so I could probably make it optional fairly easily.

**Comment by Kathrin84** [comment]
Hi Dan and hi Davo,
by making a diff my colleaque found out, that there's the new capabillity mod/attendance:managetemporaryusers. By taking it away from our teachers, the tab temporary users is gone and the issue is therefore fixed.
I'll close this issue.

**Comment by davosmith** [comment]
Yes - now you mention it that does sound familiar (I hadn't had a chance to stop and look at the code again to remind myself exactly how it worked).

Glad you found the solution.

**Comment by danmarsden** [comment]
Great! - thanks Davo/Kathrin!
