### ISSUE TITLE
Trying to delete selected sessions without selecting sessions takes you back to main Moodle page

### ISSUE THREAD

**Issue by barrysspace** [danmarsden/moodle-mod_attendance#159]
Since sessid is a required_param_array() an error is thrown but you go back to the main Moodle page (or dashboard) when you click Continue.

It would be better to handle this in the same was as Changing duration does i.e. print an 'No sessions selected' error and redirect to the attendance module when the user clicks Continue

**Comment by danmarsden** [comment]
Great! - thanks Barry!!! - there are a few other commits in the master branch that I'm happy to back-port to earlier branches if you manage to test them and find them useful.
