### ISSUE TITLE
Separate the concepts of "points" and "grades"

### ISSUE THREAD

**Issue by antonio-c-mariani** [danmarsden/moodle-mod_attendance#163]
In our Institution teachers use the attendance module with two purposes: 1) just register and count attendances; 2) grading students based on the attendances. These two forms of use are possible through "grade type" option at attendance module settings. But when the option "none" for "grade type" is selected, the column "grades" is no longer displayed in the reports and teachers can not easily view some kind of summary of the taken attendances.

In this sense, I think it is interesting to separate the concepts of "points" and "grades". Considering this distinction, "Grades" only exist at grade book and they only exist if some kind of "grade type" is selected at the module settings. On the other hand, "Points" always exist as a result of the taken attendances and are always shown in the reports as "points".

**Comment by danmarsden** [comment]
I think the issue that teachers can not see a summary of the taken attendances would be a problem but I don't know that we need to differentiate between grades/points - we just need to make sure the reports show useful information when grades are not being used.

**Comment by antonio-c-mariani** [comment]
Hi, Dan

At #164 you said "We would need to make sure the interface made sense ...". I think this is very import. To be usefull the information needs to make sense. My suggestion goes exactly in this direction. if one teacher choose not to use grades, then grades no longer make sense. Why then keep showing him this term?

When teachers are taking attendances they are not giving grades. Grades are consequence if the teacher choose to use them. In my case (as a teacher) when I see the attendance reports I don't want to see grades. I wonder if students are coming to school or not. To me percentage is the best option (see #38). We have this at our university and our teachers are very happy.

My suggestion is very simple to implement. It can be done just by changing the terms. There are few effective code changes.

**Comment by danmarsden** [comment]
thanks - there are a few open issues related to reports and it would be great to tidy them up a bit more. Screenshots of planned changes can help a lot too.

**Comment by antonio-c-mariani** [comment]
Follows two screenshots of our Moodle production system. This report tries to cover the following issues: #163, #127, #38, #66, #103, 
I'm using two statusset (P4=>4, P2=>2, Au=>0) and (P2=>2, Au=>0). In the session details you can see the acronym and the corresponding points. On the right there are two columns, one for sum of points and another for percentage. At the bottom there is a summary that shows the number of students for each status of the corresponding statusset.
The "Summary" tab is exactly like "All" tab except that it doesn't show session details (columns).
The tab named "Below 75%" only shows students with percentage below 75%. This number is very important to us because it sets the threshold required for students to be approved. There is a global parameter that defines this threshold. If the teacher configure the attendance to use grades, the "grade to pass" parameter has precedence over this global parameter.
I think the "Below 75%" tab is weird because its semantic is different from the other tabs. Maybe it's better to work with a filter on each tab instead of a separated tab.

![attendance1](https://cloud.githubusercontent.com/assets/10731910/10194714/a0458c2a-6760-11e5-82d6-55ca32195322.png)
![attendance2](https://cloud.githubusercontent.com/assets/10731910/10194718/a70292ce-6760-11e5-8859-871bc49808f0.png)
