### ISSUE TITLE
Option to set session end time

### ISSUE THREAD

**Issue by antonio-c-mariani** [danmarsden/moodle-mod_attendance#164]
In our institution the duration of classes is 50 minutes, starting at 7:30 AM. When creating sessions sometimes teachers need to make some calculations to properly set the duration of the corresponding session. Thus, it would be much simpler if there where an option to set the end time of a session instead of setting its duration.

The suggestion is to include a global parameter that defines the way teachers can set the session end time, either by session duration (as it is today) or by the end time (new option). This new option seems to apply even when the duration of the classes is an integer (1 hour, for instance).

**Comment by danmarsden** [comment]
I'm not sure we need to handle both - most core activity plugins use a start and end date rather than a duration. We would need to make sure the interface made sense when using it to create multiple sessions as well. 

I think my preference would be to add a new time selector directly under the existing session date that lined up with the hour/minute drop downs to set the end-time of the session.

Also - I don't think the header "session end date" is very clear when creating multiple sessions - the "add session" form could do with a good tidy up.

There must be some real-life examples that allow multiple events to be created that make more sense than our current form.

**Comment by antonio-c-mariani** [comment]
Hy, Dan

I agree with you about the header "session end date". I think an old version of this plugin had two different tabs, one to create a single session an another for multiple sessions. If I could choose I would like to go back to that version.

We have changed the portuguese translation a lot trying to make the current interface as clear as possible. Still many teachers end up confusing things.

To simplify the lives of our teachers we have changed the plugin exactly as you said by replacing the "duration" field by a new time selector field called "end time". I could send you this change for now. If you have any other suggestions I can try to implement it.

**Comment by danmarsden** [comment]
cool, I think it makes sense to get rid of the duration option and replace it with an end-time - particularly if we can get that to line up nicely with the start date above.

I wonder if we can completely hide the options to generate multiple sessions unless the option to select multiple sessions is made - rather than show them as greyed out. I vaguely remember doing this with a Moodle form in the past.

**Comment by antonio-c-mariani** [comment]
I tried to find something like "hiddenIf", but I did not succeed. We will try to make a patch and submit to the Moodle hq (see https://moodle.org/mod/forum/discuss.php?d=71658). 

It's possible to built a proper javascript but I don't like the idea. I prefer to use existing resources. Do you have any different suggestion? For now, what do you think about the two tabs that I mentioned before?

What about the "duration" field of the database? It remains as it is or must be replaced by something like "endtime"?

On the issue of the session "start time", it seems more related to "end time" than the session "date" or session "start date" (without time). I have talked to some colleagues and they agree with this, especially in the case of multiple sessions.

**Comment by antonio-c-mariani** [comment]
Below is a proposal for the "session add" interface. It keeps the same structure of the current version, but changes the fields position. This way it seems unnecessary to hide any field when the user choose to add a single session.

![add](https://cloud.githubusercontent.com/assets/10731910/10261066/a88187f6-695c-11e5-8522-3c433357d66c.png)

**Comment by antonio-c-mariani** [comment]
Another version of the "session add" interface showing the "group sessions" and "status set" options. A second image shows the "session update" interface. Some other minor changes:
* Added a "cancel" button to keep consistency with update form.
* Changed the term "Common" by "All students" because  it's difficult to understand what "common" means in this context. I think the term "All students" better reflects the semantic.
* The group names were prefixed by the term "Group".

![add](https://cloud.githubusercontent.com/assets/10731910/10264967/f9cc0298-69f3-11e5-9f81-12125f210497.png)

![update](https://cloud.githubusercontent.com/assets/10731910/10265032/2428d262-69f6-11e5-94c7-81a28a88f8db.png)

**Comment by danmarsden** [comment]
great to see all the updates here - I probably won't get a chance to digest and read it properly until later next week - school holiday madness.... :-)

**Comment by antonio-c-mariani** [comment]
Ok.

I sent you a pull request in the case you want to see the code in action. 

There are some other minor changes:
* changed de term "Period" by "Time".
* opening the session update form on a new tab instead for "add" tab
* changed the button name of the update form to "Save changes" trying to keep consistency with other Moodle interfaces.

**Comment by danmarsden** [comment]
Thanks Antonio - now that I've had a chance to look at these screenshots I like them a lot - thanks for working on this! - It appears to be more logical.

I don't think the "description" field is in the right place - I know it is at the bottom of the old form at the moment - I wonder if it would be better at the top like with most other activity module forms?

I wonder if anyone will find the change from a full text-editor to a simple text box to be a problem? - I vaguely remember a way of embedding a text editor but displaying a very small text box to start with and allow people to expand it/pop-out editing buttons if needed. I'll try to track that down but it may be from when tinymce replacements were being investigated.

**Comment by danmarsden** [comment]
I expect when sessions are configured to allow students to record their own attendance the session description is more likely to contain extra information and a full atto editor might be required.

**Comment by danmarsden** [comment]
I asked Damyon about this - "The default height of Atto will be taken from the number of rows in the original text area - that way you can make it smaller initially (see quiz multi choice questions edit page)" - so hopefully we should be able to implement atto but in a way that doesn't take up too much space.

**Comment by antonio-c-mariani** [comment]
Yes, normally the most important things come first  like the "name" and "description" fields in the activity module forms. But in this context I think the "description" is not as important. I really do prefer the date and time fields first. In my case, for instance, I have never used the description field.

I have changed the "description" field to atto editor with the minimum height. There is a pull request for that.

**Comment by danmarsden** [comment]
yeah - makes sense. looks better as one line too. Lets put description at the very bottom of the "add session" set (under the studentscanmark checkbox) Looks like the other merges have caused this to be in conflict but should be straightforward - let me know if you don't have time to fix the conflicts and I'll do it at this end. 

This makes some really nice improvements to the interface - thanks!

What are your thoughts on leaving the multiple sessions group expanded by default? - I wonder if we should minimise it by default? - or do you think that might mean that teachers never notice the extra options?

**Comment by antonio-c-mariani** [comment]
I've changed the description field positions as you suggested. I've solved the conflicts and I've done some coding guideline fixes too.

About the multiple sessions group I think it must be always expanded because the creation of multiple sessions seems to be the normal use case.

**Comment by danmarsden** [comment]
cool - I'll take another look this week. Thanks!

**Comment by danmarsden** [comment]
Thanks Antonio, now that I've integrated the Travis CI checks you can see the Moodle coding guideline errors and the behat test failures that occur after the interface change. These get run automatically each time the pull request changes so you can see any progress. Let me know if you don't think you will be able to fix up the behat failures and I can try to do them myself. Don't worry about the PHP Mess detector violations that are shown in the Travis checks - most of those will all be pre-existing.

**Comment by danmarsden** [comment]
I've merged this in, will fix the travis stuff separately - thanks heaps for working on it Antonio!
