### ISSUE TITLE
List of "All Participants" in "Take Attendance" under grouping restriction

### ISSUE THREAD

**Issue by srfdino** [danmarsden/moodle-mod_attendance#175]
Hi All!

I have the following case:
- Moodle 2.9.1+ (Build: 20150711)
- mod_attendance 3.0.0.1 (2015102200) or 2.9.1 (2015040500)
- The Attendance activity is assigned to a 'grouping' and Restricted access to this same 'grouping'
  (See screen capture 1)

![screen-capture-1](https://cloud.githubusercontent.com/assets/14875086/10921337/58b725fa-8275-11e5-9060-6b6398b9f46e.png)
- Define a "common" session
- When you enter "Take Attendance" you get the group selection selector with the options "All Participants" and the 'groups' belonging to the given 'grouping', "AG12" in the example.
  (See screen capture 2)

![screen- capture-2](https://cloud.githubusercontent.com/assets/14875086/10921339/5d13b26c-8275-11e5-972b-e013efcb51a1.png)

If "All Participants" is selected the full list of students enrolled to the course is shown.
We think that the behaviour should better be to show only students belonging to the 'grouping'.
It is confusing to have the option to set the attendance of students that are not allowed to attend.

Besides, this is the behaviour of the core Task activity in the same situation.

What do you think?

Many thanks in advance!

**Comment by danmarsden** [comment]
Makes sense to me - unfortunately the time I have as a volunteer is quite limited and I have a large tasklist so It's unlikely I'll have time to work on this. If you have someone that is able to develop a patch to fix this please share it here and I'll endeavour to include it in the core code-base. Alternatively if you have funding to help pay for my time to work on this fix let me know and I can provide details on our rates.  Thanks for the report!

**Comment by srfdino** [comment]
HI!

Many thanks for your fast answer!!
Unfortunately we are not able to put any budget on it.

Anway, may be we could do it.
Just give me a clue about were to start looking at it.
(Where in the code is generated the list of participants).

Of course if we finally make the patch I will come back to you in order to provide it in the best way.

Thanks again!!

**Comment by danmarsden** [comment]
The renderer calls attendance::get_users() and passes it the groupid - you'll probably need to modify that somehow to check for groupings.

**Comment by srfdino** [comment]
HI!
I think the problem is that functionality arround
$CFG->groupmembersonly and $this->cm->groupmembersonly
was removed in 2.8 and substituted by Access restriction.
Anyway, the list of groups into the grouping is being correctly calculated.
I'll try a (simple) solution.

**Comment by danmarsden** [comment]
groupmembersonly code was removed in the plugin recently - not sure if this means that groupings now work correctly but closing this off as I'm hoping it's all working. Feel free to create a more specific issue if this is still an issue with the latest code available in github. Thanks.
