### ISSUE TITLE
Constant times winter/summer time

### ISSUE THREAD

**Issue by lpawlak** [danmarsden/moodle-mod_attendance#176]
How to achieve same times in all sessions?
When I generate multi session and there are change between summer and winter time, then times are different.
There is discussion on Moodle forum: https://moodle.org/mod/forum/discuss.php?d=322614
Please help.

**Comment by danmarsden** [comment]
Thanks - sounds like a bug. I'll try to take a look at this sometime. I work on Attendance as a volunteer and my time is limited so I cannot guarantee a time-frame. Things that can speed this process up include funding the time for me to look at the issue or finding someone with development knowledge to track this down and provide a patch for me to review. Thanks! :-)

**Comment by danmarsden** [comment]
I can reproduce this when a session is scheduled to occur on a day that involves a DST change - looking at a way to resolve it now.

**Comment by fabiosegalla** [comment]
This problem still exists when inserting a single session in a day that involves a DST change or updating an existing one.
