### ISSUE TITLE
Expired self enrolments prevent student self-attendance taking when active manual enrolments exist

### ISSUE THREAD

**Issue by NeillM** [danmarsden/moodle-mod_attendance#178]
It is similar to issue 81

Steps to reproduce:
1. Add self enrolment method to a course (set to expire before attendance session)
2. As a student self enrol on the course
3. Create an attendance session, which allows students to mark their own attendance, which starts after the self enrolment expires
4. Manually enrol the student on the same course with no expiry date
5. As the student visit the attendance activity
6. The session above will be greyed out on the attendance register with "User enrolment ends ## ## #### (date)"

**Comment by NeillM** [comment]
I have sent some pull requests to fix the issue.

**Comment by danmarsden** [comment]
Great! - thanks Neil, all merged.
