### ISSUE TITLE
Coding activity types

### ISSUE THREAD

**Issue by mhughes2k** [danmarsden/moodle-mod_attendance#183]
We're getting involved with learning analytics, and one of the parameters that we're looking to track is student attendance.

We have users that use a single instance of mod-attendance for both their lecture and tutorial attendance, but we also have users that do the same thing but via 2 separated attendance module instances.

The observation that we've come to is that it currently doesn't provide a "coded" value for the type of activity that a session represents. 

The session's type is entirely _implicitly_ defined by the free text title for the activity.

If there was a way to define session types (at the server level) that allowed a coded value to be set, we would then be able to export to the learning analytics system more accurate data. 

It could also add some easier mechanisms for the management of sessions within a single instance of the module.

**Comment by mhughes2k** [comment]
Further thought: A setting when creating the module instance could allow the user to allow multiple session types within the activity or limit it to a single type of session.

**Comment by danmarsden** [comment]
sounds useful - feel free to submit a patch! :-)

**Comment by danmarsden** [comment]
- just be aware it will likely conflict with the work on Issue #164

**Comment by danmarsden** [comment]
closing as "won't fix" as it's not something I plan to work on - but I'm happy to review pull requests (or receive funding to extend the plugin) :-)

thanks!
