### ISSUE TITLE
Updating preferences within instance updates grades even when there is no grade yet

### ISSUE THREAD

**Issue by sam-moodle** [danmarsden/moodle-mod_attendance#184]
If you update the preferences within an instance and there is no grade yet for a student it can create a 0 grade. Here are the steps to reproduce:
1. Create course
2. Enroll student users into course
3. Add Attendance activity to the course
4. Add at least one session to the attendance activity
5. Go to the Settings tab within the attendance activity and just click Update (or you can make any change you want and click update)
6. Review the grade history for the item

Expected: Grades should show as '-' to students until the attendance is taken and grades given properly
Observed: As soon as the Update button is clicked, a grade update is inserted into the logs/gradebook giving all students a zero(F)

**Comment by sam-moodle** [comment]
Here is a PR that I think addresses the issue. https://github.com/danmarsden/moodle-mod_attendance/pull/185

If you have a minute to look at my patch, I'd really appreciate it. Thanks.

**Comment by danmarsden** [comment]
Thanks Sam - I'm away on leave at the moment but will try to take a look when I get back!

**Comment by danmarsden** [comment]
Patch merged - thanks!

**Comment by sam-moodle** [comment]
Thanks, Dan!
