### ISSUE TITLE
Allow default status set to be editable

### ISSUE THREAD

**Issue by Jarvil** [danmarsden/moodle-mod_attendance#187]
Hello,

I'm translating Attendance-plugin to Finnish and there seem to be some hard-coded strings that I cannot change from the language pack.
# Problem 1 as a student

When I'm self registering as a student (on attendance.php page, see bug1.png) I see choices for present, late, excused and absent even though I have translated them to the language pack as follows:

string Lacronym = M 
string Lfull = Myöhässä

string Pacronym = P
string Pfull = Paikalla

string Eacronym = S
string Efull = Sovittu poissaolo

string Aacronym = P
string Afull = Poissa

After I have selected one status as a student and saved it I see in the status-row the text is in english f.ex. Present (bug2.png)

![bug1](https://cloud.githubusercontent.com/assets/15193418/12637987/59863492-c5a2-11e5-9c0a-2021993560da.PNG)

![bug2](https://cloud.githubusercontent.com/assets/15193418/12637986/597c5f80-c5a2-11e5-8717-12a5fd3b7afd.PNG)
# Problem 2 as a teacher

The problem continues when a teacher is looking at the student attendances on the take.php -page.

If you hover the mouse over acronyms the first part of the text is translated from the string setallstatusesto but the status-attribute isn't so it says for me "Aseta kaikille käyttäjille statukseksi <<Present>>" see bug3.png. 
1. The third problem shows on the same page, at the bottom left statuses aren't translated and they show Present = x, Late = x, Excused = x and Absent = x.

![bug3](https://cloud.githubusercontent.com/assets/15193418/12637985/596931e4-c5a2-11e5-9541-941991bacfd5.png)

**Comment by Jarvil** [comment]
Hello,

I noticed that you can set your own Acronyms from the settings page. This could solve the problem if the default values would come from the language pack. At the moment they are in english by default

![settings](https://cloud.githubusercontent.com/assets/15193418/12639238/ae8b2020-c5ab-11e5-9053-9ed6c362c676.PNG)

**Comment by danmarsden** [comment]
They are pulled from the language pack set at installation time:
https://github.com/danmarsden/moodle-mod_attendance/blob/18324c0e8676134e8b9e717be6dc00bf3384dacf/db/install.php#L37

you should be able to set the language to use during install - i suspect your site was initially installed using the english language pack or has "english" set as the default. if this is not working then it is likely a bug and please let me know.

**Comment by Jarvil** [comment]
Hello,

Yes the Moodle was originally installed with English language and we cannot reinstall it because it is in use. 

For future you should consider doing this some other way, this doesn't sound a very good way of making a plugin or make those language strings available for translation in the language pack, thanks.

**Comment by danmarsden** [comment]
Yes - the default status set should be editable within the settings page of the attendance (even after first install) - I thought that was already possible but I can't see it anywhere in the interface unfortunately.

We won't likely change it to always pull from the lang pack but it should definitely allow you to re-configure the default set after install.
