### ISSUE TITLE
Feature request: Mark attendance with CSV Import

### ISSUE THREAD

**Issue by nadavkav** [danmarsden/moodle-mod_attendance#189]
An ability to upload a list of user ids with attendance statuses at the bottom of the attendance check page as an alternative way to import and upload attendance from other applications.

**Comment by danmarsden** [comment]
yeah - I've thought that this would be a really good feature too. it's something I've wanted to work on if I ever have time to do feature development on the code. (unfortunately I don't have much free time for it these days)

**Comment by nadavkav** [comment]
Great to read that you are in to this. It seems we are about to implement it over here, so I guess you should expect a PR soon :-)

**Comment by zmartinovic** [comment]
Any news on this feature? Import of attendance statuses via CSV would be very nice addition, along with the import of sessions :)

**Comment by nadavkav** [comment]
I might be starting to work on this next week. (as it was pushed deep down in the backlog, and now I finally have some time to clean it)

**Comment by zmartinovic** [comment]
Nice, looking forward to it :)

**Comment by gmleomil** [comment]
Is there any update on this feature? :D

**Comment by danmarsden** [comment]
nope - not sure if @nadavkav is still planning to work on it though.

**Comment by nadavkav** [comment]
We actually needed it for a very specific external web conferencing service we are using [Unicko](https://www.unicko.com/). which can export attendance into a CSV file.
I had it working, but after two weeks we found out we can use [web services](https://www.unicko.com/docs/api) to get the attendance data from our main web conferencing service, so we removed the option to upload attendance from CSV files, as it was confusing the teachers. and switched to web services. without bothering the teachers with the manual process.

I will see if I have that branch and try to push it, so you can cherry pick it.

**Comment by zmartinovic** [comment]
Having a global admin option to enable/disable CSV upload would allow you have this feature in the main branch and make it more usable for many Moodle users :)

**Comment by nadavkav** [comment]
@zmartinovic , I agree.

**Comment by hassan82** [comment]
Is there any improvement in taking attendance by importing from a CSV file? We are looking forward hearing good news!

Thanks in advance.

**Comment by danmarsden** [comment]
Not at this stage. You can create new sessions using a csv but marking attendance is not supported. Pull requests or funding are always welcome.

**Comment by gemguardian** [comment]
Hi Dan,

Wondering... could you give an cost /time estimation if you have to build this function in away it works from Moodle 3.3 and higher? 

Thank you 

Gemma

**Comment by danmarsden** [comment]
Hi Gemma, please get in touch privately and I can provide information on our rates.

**Comment by ja4ms** [comment]
Hi Dan,
I am looking for a CSV-Template around here and there to create new sessions but I couldn't find any single piece that came from you. Is it me? Or is there really nothing to find.
Thanks in advance.

**Comment by danmarsden** [comment]
yeah - documentation on Attendance is unfortunately really limited - would be nice if someone helped to improve it! :-) - if you put one together feel free to update the wiki here:
https://docs.moodle.org/en/Attendance_activity

**Comment by ja4ms** [comment]
Thanks for getting back to me :-)
English is – as you may have noticed – not my mother tongue. But I'll give it try maybe in october. I'm quite busy at the moment.
Or I'll try to help translate some messages to German. Maybe that would make more sense?

**Comment by danmarsden** [comment]
anything you contributed would be great! :-)

**Comment by flistergod** [comment]
Hello, i tried to reach out to you in linkedin, but i dont know if you got the message, so here it goes:
I am in my last year of cs degree and i am doing a project that you can through an app validate the presence of the students in a class with a qr code. Then the teacher can se the attendance of each class and the absence of each student. I am trying to export a cvs file for each class with the attendance of the class and upload it in the attendance of the moodle. So i am wondering, is there any improvement in taking attendance by importing from a CSV file? or do you know how, with an API that, while using the qr code, i can automatically change the absence of the student on moodle?
Any  help would be great, keep doing a great job man :)

**Comment by danmarsden** [comment]
Hi @flistergod - I replied to your linkedin message, sorry I can't help much further at this stage! - things are crazy busy right now and I am unable to provide private mentoring support for free - good luck with your project!

**Comment by flistergod** [comment]
Thanks. I will try to do something on my own. But is there improvement in taking attendance by importing from a CSV file?

**Comment by danmarsden** [comment]
there is a community pull request in #393 which needs me to spend a chunk of time before it gets merged in. But if you're doing this in an app you should really be using the webservices rather than importing via a csv (see update_user_status)

**Comment by danmarsden** [comment]
The ability for a teacher to upload a csv to a specific session has now been added to the main branch thanks to some initial work by @jonathanchan2 - it allows either the status acronym (PLEA etc) or the specific time the users attendance was taken to be passed in the csv file.

It does need extending so that you can import more than one session at a time, and possibly some CLI scripts might be nice but this hopefully gives us a base that we can extend further in future.

thanks!

**Comment by pierrealbin** [comment]
> The ability for a teacher to upload a csv to a specific session has now been added to the main branch thanks to some initial work by @jonathanchan2 - it allows either the status acronym (PLEA etc) or the specific time the users attendance was taken to be passed in the csv file.

That sounds wonderful. How would I go about uploading a csv file? When I click on attendance, there is an `export’ tab but not an `import’ tab. Thank you for any pointers!
