### ISSUE TITLE
Coding error detected on export page

### ISSUE THREAD

**Issue by wildgirl** [danmarsden/moodle-mod_attendance#190]
mod/attendance/export.php

Coding error detected, it must be fixed by a programmer: moodle_database::get_in_or_equal() does not accept empty arrays

Attendance version 3.0.0.1 (2015102200)
Moodle version 3.0.2 (Build: 20160111)

**Comment by danmarsden** [comment]
Thanks Helen - I don't suppose you have any line numbers on that error?

**Comment by durzo** [comment]
Hey Dan, here's the error from the server Helen is using

```
coding_exception: Uncaught exception 'coding_exception' with message 'Coding error detected, it must be fixed by a programmer: moodle_database::get_in_or_equal() does not accept empty arrays' in /lib/dml/moodle_database.php:695

in moodle_database::get_in_or_equal called at /mod/attendance/export_form.php (76)
in mod_attendance_export_form::definition called at /lib/formslib.php (196)
in moodleform::__construct called at /mod/attendance/export.php (52)
```

**Comment by danmarsden** [comment]
cool - that's the one I found in the end too - thanks. It occurred when there were no students enrolled in the course, I pushed a fix through for it yesterday.
