### ISSUE TITLE
Grade inconsistency when using status set visible option

### ISSUE THREAD

**Issue by antonio-c-mariani** [danmarsden/moodle-mod_attendance#192]
Define a status set similar to:

![att1](https://cloud.githubusercontent.com/assets/10731910/14531838/4bd34374-0235-11e6-8003-7e159d593871.png)

After taking some attendance, see the attendance report and the grade book.They are both consistent.

![att2](https://cloud.githubusercontent.com/assets/10731910/14531934/95fb3b5a-0235-11e6-9ee4-45721d3b8129.png)

![att3](https://cloud.githubusercontent.com/assets/10731910/14531942/9a82f60e-0235-11e6-88a5-8404846040df.png)

Hide the "P4" acronym:

![att_2_1](https://cloud.githubusercontent.com/assets/10731910/14531989/bf2b3b38-0235-11e6-86c6-44cf1d942a6d.png)

and return to the attendance report and the grade book. They are now inconsistent:

![att_2_2](https://cloud.githubusercontent.com/assets/10731910/14532034/efa9a236-0235-11e6-8b64-97a28bfd907a.png)

![att_2_3](https://cloud.githubusercontent.com/assets/10731910/14532042/f387fdd0-0235-11e6-80a9-8534c28a7f46.png)

Is this behaviour expected? Should the grades be recalculated?

What is the effective use of this option (hide an acronym)? It is really necessary?

**Comment by danmarsden** [comment]
I'm not sure what the effective use of that option is for off the top of my head - it was implemented before I took over maintenance for this plugin. I'm not convinced we should re-calculate the grades at that point but I'm open to feedback!

**Comment by antonio-c-mariani** [comment]
If this feature should be kept than I think the grades must be recalculated to reflect the changes. I have two arguments for that. 

First of all, I think the grades at the gradebook must be all the time consistent with the data showed in the attendance reports. Also, the next time a teacher take attendance for a student his data will be changed in the attendance report and the grade of this student will be automatically recalculated. But the data of all other students will be inconsistent until the teacher take some other action.

As a teacher I will see this as a bug.

**Comment by danmarsden** [comment]
I think we should probably just prevent the item from being hidden if it is already in use within the attendance - this is similar to how other things work in Moodle - if in use/prevent removal/hiding.
