### ISSUE TITLE
Criteria for "Low grade" report

### ISSUE THREAD

**Issue by antonio-c-mariani** [danmarsden/moodle-mod_attendance#196]
The criteria for a student to be shown in the "Low grade" report is defined by "$grade < $maxgrade" in renderables.php file. In other words this means show all the students who have less than 100% of grade/points.

How about change this criteria and start using "Grade to pass" attendance setting as the threshold for the "Low grade" report?

**Comment by danmarsden** [comment]
makes sense - we've only used the standard grading elements in the form in the master branch (2.8 branch still uses hard-coded grade field) - just didn't update the low grade report based on the new flexibility. Please make sure you submit this as a separate commit rather than including in the bigger one to make it easier to review. Thanks!

**Comment by antonio-c-mariani** [comment]
Hi Dan

I would like to suggest some other related changes (see the picture below):

1) put 'lowgrade' tab at the right of the other;

2) change the 'lowgrade' tab title to "Below n%" (the value of the "Grade to pass" is converted into percentage);

3) add a help icon to the 'lowgrade' tab (only when it is selected)

4) remove the piece of code below from file renderables.php
      
> $currenttime = time();
> if ($att->pageparams->view == ATT_VIEW_NOTPRESENT) {
>           $att->pageparams->enddate = $currenttime;
>  }

   in order to calculate the low grade over all taken sessions.

The last change aims to maintain consistency with the data presented on the "All" tab.

![below](https://cloud.githubusercontent.com/assets/10731910/14746406/decc7758-0885-11e6-8c18-14dbc7e4b466.png)

**Comment by danmarsden** [comment]
I just dug out those changes from your old pull request, tidied them up to squash into a single commit and removed the other changes that were unrelated and put this into the master and 3.5 stable branches here - thanks!
