### ISSUE TITLE
Send a message interface

### ISSUE THREAD

**Issue by antonio-c-mariani** [danmarsden/moodle-mod_attendance#197]
In the reports we can see the "Send a message" button at the left-bottom of the page while the corresponding checkboxes are at the right side. There is no clear relantionship between them. I think it is necessary some change in order to connect then clearly.

![msg1](https://cloud.githubusercontent.com/assets/10731910/14728592/8a82004c-080c-11e6-8896-724634719688.png)

A second issue concerns the selected students list. If you select 2 students and press "Send a message" you will see something like the picture below.
![msg2](https://cloud.githubusercontent.com/assets/10731910/14728595/8f25bc2e-080c-11e6-9e68-a26e6d809c5a.png)

At this point you can return to the report page clicking on "Keep searching" link. The previously selected students are still selected (the selection is stored in the session) but the checkboxes are all unmarked. In fact the checkboxes only serve to add new students to the the previously selected list. All unmarked students who had been previously selected will keep selected after you click "Send a message". I think it is not what a user expects as a result.

**Comment by danmarsden** [comment]
Thanks Antonio,

The send message page is even worse if you have messaging disabled on the site too... We are re-using the core messaging page like some other 3rd party plugins do such as Michael's Progress Bar. It would be good to improve the core Moodle send message page to allow better re-use like this. I don't really want to re-implement a custom "send message" form/page within the attendance plugin and would prefer to use the core form.

The checkboxes on the far right of the report seems weird to me too - maybe they will look better when on the left to start with.

**Comment by danmarsden** [comment]
I've just moved the checkboxes to sit with the new floating users name which appears more logical - fix in the master and 3.5 stable branches here - let me know if you think we need further improvements - thanks!
