### ISSUE TITLE
Users sort order

### ISSUE THREAD

**Issue by antonio-c-mariani** [danmarsden/moodle-mod_attendance#207]
The default sort order when listing users is given by ATT_SORT_LASTNAME. But our preference is ATT_SORT_FIRSTNAME. Currently the teachers have to manually change the list order every time they will take attendances.

This behaviour could be changed by adding a new global attendance config parameter that allows the Moodle admin select this behavior. A different approach is using the "users_order_by_sql" Moodle function as the default behavior.

I prefer the second option because it transfers the sort order to a global Moodle behavior.  I our case we have already changed the "users_order_by_sql" code  to accomodate our needs.

**Comment by danmarsden** [comment]
users_order_by_sql makes sense to me too. - feel free to submit a pull request with that change - thanks!

**Comment by danmarsden** [comment]
thanks - good to have the ordering working better - next step will be to rewrite those tables so they use more normal functions for sorting columns etc.
