### ISSUE TITLE
Error Message listing all courses as a student.

### ISSUE THREAD

**Issue by joelschmid91** [danmarsden/moodle-mod_attendance#209]
If I access the attendance activity with a student profile and choose the **All Courses** registry, I get a couple of error messages. Does anyone experience the same problem? 

```
Notice: Trying to get property of non-object in /var/www/html/moodle/mod/attendance/renderhelpers.php on line 240

Notice: Trying to get property of non-object in /var/www/html/moodle/mod/attendance/renderhelpers.php on line 246

Notice: Trying to get property of non-object in /var/www/html/moodle/mod/attendance/renderhelpers.php on line 247
```

We are running mod_attendance version: 2016052201 (master branch)

**Comment by danmarsden** [comment]
thanks Joel, I'll take a look.

**Comment by danmarsden** [comment]
I haven't been able to reproduce this but I found a possible issue and have pushed through a patch - can you please let me know if this resolves it for you? - thanks.

**Comment by joelschmid91** [comment]
Hello danmarsden
Perfect, it looks like the error is gone if I login as a regular student. Thanks for the super-fast fix! However if I choose "Switch role to"  and choose " student" the error still appears, but in that case on both registers, "This Course" and "All Courses.

**Comment by danmarsden** [comment]
Thanks - I can see some very different errors on the pages when using the switch-role function:

Notice: Trying to get property of non-object in/mod/attendance/classes/structure.php on line 680
Notice: Trying to get property of non-object in/mod/attendance/classes/structure.php on line 681
Notice: Trying to get property of non-object in/mod/attendance/classes/structure.php on line 682

Are those the ones you mean? - the start of the message might be the same, but the line numbers and related files are quite different.

**Comment by danmarsden** [comment]
I've just pushed another commit to fix those ones as well. there shouldn't be a scenario where a real student would get that fatal error as they cannot use the "Manage" attendance page anyway, but it should handle that better.

**Comment by joelschmid91** [comment]
I agree with that. :-) Anyway, perfect! Thank you for the fix!
