### ISSUE TITLE
lock the student names so they float (enhancement)

### ISSUE THREAD

**Issue by reactor0138** [danmarsden/moodle-mod_attendance#213]
That is to lock the student names so they float. On your attendance block, this is on your report tab, where it becomes near impossible to check attendance after you have add 20 or more slots (unless you have 2 screens or a really high res setting on your display). It would work like Gradereport does where the name stay as you scroll across the page.

**Comment by danmarsden** [comment]
I agree this would be nice - feel free to help us work on this improvement!

**Comment by jstilwell** [comment]
Thirded. This would be a very nice improvement to the interface for instructors.

**Comment by danmarsden** [comment]
Jesse - feel free to help us work on it! :-) - it's pretty high on the list of things I'd like to do if I have some free time to work on feature dev for the attendance.. unfortunately my free time usually gets taken up by general maintenance tasks etc.

**Comment by danmarsden** [comment]
I've just pushed a patch through that does this using css in the master and 3.5 branches here in github - seems to work well in my tests, but happy for feedback - thanks!
