### ISSUE TITLE
Call to undefined function attendance_get_user_grade() in Student outline report

### ISSUE THREAD

**Issue by SWiT** [danmarsden/moodle-mod_attendance#215]
A teacher started getting an "Exception - Call to undefined function attendance_get_user_grade()" error on a users outline report (report/outline/user.php).

I noticed between v3.0 and v3.1 that function was removed from locallib.php but there is still a reference to it in lib.php:231. There is also a call to attendance_get_user_max_grade() right after that will also error.

**Comment by danmarsden** [comment]
thanks for the report - I missed that while reviewing #201 from @saasexport - I'll take a closer look.

**Comment by danmarsden** [comment]
I've just pushed a fix through for this - can you please test and let me know if you have any issues?

**Comment by SWiT** [comment]
v3.1.1.0 seems to have fixed the issue. Thank you.
