### ISSUE TITLE
Confirmation message lingers after creating/deleting calendar events

### ISSUE THREAD

**Issue by creator23** [danmarsden/moodle-mod_attendance#220]
The issue is that immediately after creating/deleting a calendar event for a session, the message "Are you sure you want to create/delete the calendar events for the following sessions?" lingers

**Comment by danmarsden** [comment]
I can't reproduce this either - perhaps you could add some screenshots - also provide more details about the exact moodle version and which version of the attendance you are using?

**Comment by dannyjung90** [comment]
Moodle version 3.1.1
Attendance version 3.1.0.3

After confirming creation or deletion of a calendar event for a session through the attendance management page, the prompt for creating and deleting a calendar event appears when returning to the management page.

![lingering create prompt](https://cloud.githubusercontent.com/assets/3496334/18323558/fc95eaf2-74ec-11e6-83a2-76b48fcb8f84.png)
![lingering delete prompt](https://cloud.githubusercontent.com/assets/3496334/18323557/fc95d8a0-74ec-11e6-9aea-4c7e4b783220.png)

**Comment by danmarsden** [comment]
I see what you mean now - those items in the drop list shouldn't be there... possibly a bad merge on my part somewhere? - earlier versions of the calendar patch didn't add the calendar event to all sessions - so the feature to "add" them to existing events was added. I'll take a closer look to see how we ended up with different patches in the 3.1 branch from the master one.

**Comment by danmarsden** [comment]
it is there in the master version as well, it's just not supposed to be as it isn't needed and deleting the calendar event won't be permanent and isn't really supported anyway - I'll remove those 2 options from that drop-down.

**Comment by danmarsden** [comment]
fixed now - thanks for the report!
