### ISSUE TITLE
Error on updating duration of a session

### ISSUE THREAD

**Issue by creator23** [danmarsden/moodle-mod_attendance#221]
When I try to change the duration of a session, it gives me an error saying that 'timestart' is null. I created multiple sessions and this happened each time I tried to change the duration. The funny thing is that the durations were actually saved despite the error.

**Comment by danmarsden** [comment]
I'm having trouble reproducing this. were the sessions created with an older version of the attendance - any other tips on how to reproduce?

**Comment by dannyjung90** [comment]
Moodle version 3.1.1
Attendance version 3.1.0.3

After creating a new session with default settings, selecting the new session on the attendance management page and attempting to update the duration through the dropdown list leads to an error.

![change duration error](https://cloud.githubusercontent.com/assets/3496334/18323848/5292b29a-74ee-11e6-97bd-8b8d86e7786a.png)

**Comment by danmarsden** [comment]
thanks - I've been able to reproduce that now that you have posted the actual error message. you didn't mention in your first post that you were using the bulk-change method to modify duration. I'll get that fixed soon.
