### ISSUE TITLE
Global option to disable option for students to record their own attendance

### ISSUE THREAD

**Issue by jeremy-schweitzer** [danmarsden/moodle-mod_attendance#223]
Right now there doesn't appear to be a way to disable the option for student's to take their own attendance. There isn't a specific permission for this or an option on the plugin's configuration page to remove this option. 

It's turned off by default, but if a faculty member accidentally enables it there isn't an easy way to fix it, so we'd rather remove the ability entirely.

**Comment by danmarsden** [comment]
good point - I've just added a new option to the global attendance settings page that lets you disable it. Let me know if that works for you!
