### ISSUE TITLE
add new report for Present | Absent | Late | Excused totals like older reports.

### ISSUE THREAD

**Issue by BrennaKR** [danmarsden/moodle-mod_attendance#225]
This was in the previous version of the attendance module but is missing from the current version (3.1) - it used to simply show what the totals were for each individual at the far right of the report.  Now faculty have to manually calculate this and at my institution at least, they are not happy about it!
![moodle2 9](https://cloud.githubusercontent.com/assets/23039302/19660973/2704a810-99ef-11e6-8f77-03eeb08e3675.jpg)
![moodle3 1](https://cloud.githubusercontent.com/assets/23039302/19660974/2707ca54-99ef-11e6-84ed-cd0b0a6ecf14.jpg)

**Comment by danmarsden** [comment]
we had a number of issues/complaints related to the older reports and they were rewritten to help resolve those issues/complaints. The new version doesn't include the totals. I've had a few people mention they had noticed the totals had gone, but most people find the new reports better. I've been considering adding a new report to add them back for people that still want them, but I haven't had the time to do this. (Of course someone funding this work or filing a pull request with the changes would help)

**Comment by antonio-c-mariani** [comment]
Hi, Dan

I can see this. Two questions:
1 - These data should be displayed on every tab or just in the summary report?
2 - What to do when there are more than one statuset? I kind of merge (union) of the identical acronyms? In what order they should be presented? From highest to lowest grade?

**Comment by antonio-c-mariani** [comment]
Another way to treat multiple statuset is to show them side by side, probably with some way to distinguish them (background color, for instance):
![statusset](https://cloud.githubusercontent.com/assets/10731910/20652893/f45d50ae-b4e9-11e6-8a06-e93ad65d440c.png)

**Comment by danmarsden** [comment]
that would be nice - is this something you might have time to work on?

**Comment by danmarsden** [comment]
I don't think this needs to be on every report - we just need to have a way for people to see the breakdown if they want it.
