### ISSUE TITLE
Moodle 3.2 errors

### ISSUE THREAD

**Issue by durzo** [danmarsden/moodle-mod_attendance#229]
Hi Dan,

We are preparing MoodleCloud for 3.2 and get this error with mod_attendance:

```
Class 'core_search\area\base_activity' has been renamed for the autoloader and is now deprecated. Please use 'core_search\base_activity' instead.
line 117 of /lib/classes/component.php: call to debugging()
line ? of unknownfile: call to core_component::classloader()
line 36 of /mod/attendance/classes/search/activity.php: call to spl_autoload_call()
line 111 of /lib/classes/component.php: call to include_once()
line ? of unknownfile: call to core_component::classloader()
line ? of unknownfile: call to spl_autoload_call()
line 940 of /lib/classes/component.php: call to class_exists()
line 241 of /search/classes/manager.php: call to core_component::get_component_classes_in_namespace()
line 90 of /admin/searchareas.php: call to core_search\manager::get_search_areas_list()
```

Is there any chance you could fix this asap? 3.2 releases next week

**Comment by danmarsden** [comment]
yeah - should have that sorted this week - thanks for letting me know.

**Comment by juerghoerner** [comment]
Moodle 3.4.1+ new Installation: The message is the same, but other lines

Class 'core_search\area\base_activity' has been renamed for the autoloader and is now deprecated. Please use 'core_search\base_activity' instead.

    line 119 of /lib/classes/component.php: call to debugging()
    line ? of unknownfile: call to core_component::classloader()
    line 22 of /mod/scheduler/classes/search/activity.php: call to spl_autoload_call()
    line 113 of /lib/classes/component.php: call to include_once()
    line ? of unknownfile: call to core_component::classloader()
    line ? of unknownfile: call to spl_autoload_call()
    line 946 of /lib/classes/component.php: call to class_exists()
    line 262 of /search/classes/manager.php: call to core_component::get_component_classes_in_namespace()
    line 90 of /admin/searchareas.php: call to core_search\manager::get_search_areas_list()

**Comment by danmarsden** [comment]
Please make sure you are using the correct version of attendance for moodle 3.4. It sounds like you have installed the attendance code for an earlier release.

**Comment by juerghoerner** [comment]
I did not install the attendance mod. I had an earlier version uninstalled. I installed now the newest mod_attendance and now all is OK. Thank you for your prompt response. Juerg

		
		

		Outlook für iOS beziehen
	




On Thu, Feb 1, 2018 at 7:06 PM +0100, "Dan Marsden" <notifications@github.com> wrote:












Please make sure you are using the correct version of attendance for moodle 3.4. It sounds like you have installed the attendance code for an earlier release.
