### ISSUE TITLE
Moodle 3.2 import course issue

### ISSUE THREAD

**Issue by scyrma** [danmarsden/moodle-mod_attendance#231]
Hi, here's a debugging message that comes out while restoring a course with the "restore logs" option activated:

```In order to restore course logs accurately the event "mod_attendance\event\session_added" must define the function get_objectid_mapping().```

**Comment by danmarsden** [comment]
Thanks Mathieu. I hadn't seen that either. Will try to get that sorted this week.

**Comment by danmarsden** [comment]
Hi Matthieu, I've added a branch linked above that adds the functions to the event classes - I haven't tested it though as I don't seem to have any backup files with legacy log data included. let me know if you are able to share a file or if you are able to test it.

looking at the docs I might need to add the get_other_mapping() function in a few places as well.

**Comment by scyrma** [comment]
Thanks Dan - I'll test it here today

**Comment by scyrma** [comment]
Patch behaves well, according to the logs.

**Comment by danmarsden** [comment]
cool - thanks. merged into master.

**Comment by PickledKitty** [comment]
> 
> 
> Hi Matthieu, I've added a branch linked above that adds the functions to the event classes - I haven't tested it though as I don't seem to have any backup files with legacy log data included. let me know if you are able to share a file or if you are able to test it.
> 
> looking at the docs I might need to add the get_other_mapping() function in a few places as well.

Hey Dan,
Did you forget to add the get_other_mapping() function? 
I can't see it in the code and am getting a restore message: PHP Notice:  In order to restore course logs accurately the event "mod_attendance\event\session_added" must define the function get_other_mapping().

**Comment by danmarsden** [comment]
doesn't look like I did - feel free to help us work on it and file a pull request to improve it. Thanks!
