### ISSUE TITLE
Error in renderer.php

### ISSUE THREAD

**Issue by joelschmid91** [danmarsden/moodle-mod_attendance#234]
Hey guys

We're getting the following error, having the HEAD on the most current commit **b053e12** (HEAD, origin/MOODLE_31_STABLE, MOODLE_31_STABLE).

> Fatal error: Can't use function return value in write context in /var/www/html/moodle-dev/mod/attendance/renderer.php on line 816

Changing the code as follows, would fix the issue. However, I don't really understand why the error appears...
`                $configjs = get_config('attendance', 'studentscanmark');
                if (!empty($configjs) && !empty($sess->studentscanmark)) {
 `

We're running PHP 5.4.16. Would be great if you could fix this asap! :-)

Cheers, Joël

**Comment by joelschmid91** [comment]
Same problem in the following two locations. Defining a variable first and checking if it's empty solves the problem.			  

> Fatal error: Can't use function return value in write context in /var/www/html/moodle-dev/mod/attendance/add_form.php on line 121
> Fatal error: Can't use function return value in write context in /var/www/html/moodle-dev/mod/attendance/sessions.php  237

**Comment by joelschmid91** [comment]
I did some more research, seams as the code would work in PHP Version 5.5 (see changelog http://php.net/manual/en/function.empty.php). However, as some unix systems don't support 5.5 in their official repositories yet and as moodle 3.1 requires only php version 5.4.4 it would be great if the moodle_31_stable branch would support php 5.4.4+ as well.

**Comment by danmarsden** [comment]
Thanks Joel, 
feel free to submit a pull request with this change otherwise I'll try to get to it soon

**Comment by danmarsden** [comment]
thanks! - merged those in.

**Comment by joelschmid91** [comment]
Awesome! Thanks @martygilbert and @danmarsden
