### ISSUE TITLE
Comment fields are not saved when n

### ISSUE THREAD

**Issue by pavelsokolov** [danmarsden/moodle-mod_attendance#240]
![screen shot 2017-02-01 at 12 09 13](https://cloud.githubusercontent.com/assets/3234777/22501853/a044adf8-e87b-11e6-960e-87f0d4d13a57.png)
We have noticed that Moodle does not bother to save the comments unless one also actually make a selection of one of the attendance radio buttons. For us, it is illogical to select a button before the event, but quite sensible to put a comment in there before the event. Moodle gives absolutely no warning that it will drop those comments when saving.

I propose either of the options:
- read-only comment fields until any option is chosen
- warning before saving the form saying that the comments will be lost (= "you didn't select the attendance status for some attendees" )

**Comment by danmarsden** [comment]
thanks - I'll take a look!

**Comment by danmarsden** [comment]
I've just pushed a fix into the master branch that should fix this - let me know if you get a chance to test it.

thanks,

**Comment by pavelsokolov** [comment]
Thank you - it works!
