### ISSUE TITLE
Change in Attendance Report "All Past" No Longer Displays the Summary by Student Since 3.1 

### ISSUE THREAD

**Issue by looneyj** [danmarsden/moodle-mod_attendance#242]
Hi Dan,
We have requests for the attendance report to display the summary by student for "All Past" attendance. 
3.0 view in clean theme where the summary for each student displayed: 
https://www.screencast.com/t/TShGvO48UV
3.1 view in clean theme where the summary for each student does not display the same way it did: 
https://www.screencast.com/t/rJiN56P7ou - the summary here seems to focus more on a summary of each attendance session and no longer includes the individual user's summary
Is this possible?

**Comment by danmarsden** [comment]
which version of the attendance code are you using? - I think we added that back in the latest version in github.

**Comment by looneyj** [comment]
3.1.1.0
2016052202

**Comment by danmarsden** [comment]
see fix#225

**Comment by looneyj** [comment]
Doh! Thank you Dan ; )
