### ISSUE TITLE
DB Schema does not have intro and introformat

### ISSUE THREAD

**Issue by mattporritt** [danmarsden/moodle-mod_attendance#243]
Hi Dan,
I've been doing some testing with this plugin for Moodle Global search. The codebase I'm testing on is 3.1 but it looks like it will exist on Moodle 3.2 also.  This is also possibly related to Issue #216 

According to the Moodle dev docs (https://docs.moodle.org/dev/Activity_modules#install.xml) activity plugins need, `timemodified`, `intro` and `introformat` in their DB schema. mod_attendance has had timemodified introduced but doesn't have the other two. This is causing errors when indexing mod_attendance documents in global search. AFAIK global search is currently the only core code that is enforcing this.

Global search gives the option for activities to override the get_document method which would be one way to solve this, however, I'm guessing it should have the req'd fields in the DB.

I cherry picked the commit from Issue #216 into the 3.1 version of the plugin as part of my testing. As an aside will this be back ported into the MOODLE_31_STABLE branch of the plugin?

**Comment by danmarsden** [comment]
thanks - yeah that should probably be backported, feel free to submit a pull request, otherwise I'll try to find the time to do this in a couple of weeks.

**Comment by mattporritt** [comment]
Hi Dan,
No worries. I'll see if I can get someone to look at it

**Comment by roperto** [comment]
Just a quick info, to replicate the issue I installed the mod/attendance and elastic search from https://github.com/catalyst/moodle-search_elastic

After elastic search was working, I went to my local site http://moodle.test/report/search/index.php and requested a full indexing. It failed as per issue #216 and after backporting that fix I still got warnings due to the missing fields.

Pull requests coming soon...

**Comment by roperto** [comment]
# Summary: #

## Moodle 30 ##

* There is no search to test, but applied **same fixes as Moodle 31**. The documentation states it requires those fields, it could break in other places.

## Moodle 31 ##

* **Fixed:** Search indexing failed with fatal error  (missing `timemodified` field)
* **Fixed:** Search indexing presented warnings (missing `intro` and `introformat` field)

## Moodle 32 and 33 (master) ##

* There was no fatal errors, `timemodified` was already present.
* **Fixed:** Search indexing presented warnings (missing `intro` and `introformat` field)

**Comment by danmarsden** [comment]
Just noticed the patch doesn't seem to add intro fields to the activity editing form? - is that correct? - if we're adding the fields to the db, shouldn't we allow those fields to be editable? - or does something automatically add it to the form when the fields exist?

**Comment by danmarsden** [comment]
thanks Roperto/Matt - all merged in now. I'll release this in the plugins db in a couple of weeks or so.
