### ISSUE TITLE
Attendance policy reminder

### ISSUE THREAD

**Issue by haietza** [danmarsden/moodle-mod_attendance#252]
Our users would like the ability to set up an automatic reminder notification to students when they reach a specified threshold close to the limit for absences. Would the addition of a feature like this be possible?

**Comment by danmarsden** [comment]
I have an existing client that is looking at funding some improvements around this - I'll post any updates on this here as things develop.

**Comment by danmarsden** [comment]
The work for this feature has now landed in the github 3.2, 3.3 and master branches - no docs available yet but let us know if you have any feedback. Thanks.

**Comment by haietza** [comment]
@danmarsden this seems to work great with the email notification and at-risk report. Thanks so much!
