### ISSUE TITLE
Attendance report table columns do not align among rows due to colspan value(s) miss-calculated

### ISSUE THREAD

**Issue by xuwenbin** [danmarsden/moodle-mod_attendance#254]
In function get_user_rows(), user's extrafields are fetched to display user email address. That results in extra columns inserted into attendance report table. However, the first row and last summary row in the same table, doesn't count the number of extrafields into colspan. Consequently, the display for first row and last summary row is messed up a little bit.

The fix is straightforward, demo as below -

----------------------

$extrafields = get_extra_user_fields($reportdata->att->context);
**$colspan** = 1 + count($extrafields);
...
...
...
$row->cells[] = $this->build_header_cell(get_string('users'), false, false, **$colspan**);

----------------------

There're two places in the function requiring extra colspan property. One for the first row, the other is for the last summary row.

-wenbin

**Comment by danmarsden** [comment]
thanks for the report and patch! - not quite sure how I missed that - seems pretty obvious! - thanks!
