### ISSUE TITLE
Attendance report table column#1 is only 1px in width and user icon is collapsed

### ISSUE THREAD

**Issue by xuwenbin** [danmarsden/moodle-mod_attendance#255]
**Environment**
Moodle v3.2.2+ weekly build
Adaptable theme v1.3.1

**What it looks**
![error](https://cloud.githubusercontent.com/assets/19218275/25505931/ab49eeea-2bd6-11e7-9027-8de1120ff2ce.png)

**What's the potential fix**

In function get_user_rows(...),

1. Comments out dummy column creation code [total 3 lines]

`//$row->cells[] = $this->build_header_cell('');`

2. Combine user icon link with username link in the same cell

```
//$row->cells[] = $this->build_data_cell($this->user_picture($user));
//$text = html_writer::link($reportdata->url_view(array('studentid' => $user->id)), fullname($user));
//$row->cells[] = $this->build_data_cell($text, false, false, null, null, false);
$fullname = html_writer::link($reportdata->url_view(array('studentid' => $user->id)), fullname($user));
$fullname = $this->user_picture($user).$fullname; // Show different picture if it is a temporary user.
$row->cells[] = $fullname;
```

**What is looks after the fix**
![correct](https://cloud.githubusercontent.com/assets/19218275/25505941/b1568e9c-2bd6-11e7-8d96-8638fdc967fd.png)

**Comment by danmarsden** [comment]
thanks - what theme is that and what moodle version? - I haven't seen it do that in my testing so far.

**Comment by xuwenbin** [comment]
I'm using Moodle 3.2.2+, and Adaptable theme.


-wenbin


________________________________
发件人: Dan Marsden <notifications@github.com>
发送时间: 2017年4月28日 6:21
收件人: danmarsden/moodle-mod_attendance
抄送: xuwenbin; Author
主题: Re: [danmarsden/moodle-mod_attendance] Attendance report table column#1 is only 1px in width and user icon is collapsed (#255)


thanks - what theme is that and what moodle version? - I haven't seen it do that in my testing so far.

―

**Comment by danmarsden** [comment]
can you please switch to one of the standard themes - if you can reproduce it with a core theme I can take a look but if it's a 3rd party theme you will probably need to get the changes applied there. Nothing I can see in core css is making that first column 1px wide.

I've tested this on boost and clean on 3.3 beta and it works for me there.

**Comment by xuwenbin** [comment]
I'll try standard theme, and let you know the result.

In the meanwhile, I think the code change proposed above is worth considerable. Because, displaying user icon is a separate column seems unnecessary. In take attendance page (see the figure below), user icon is displaying together with user names. So, I copy/paste that idea in report page.

![good](https://cloud.githubusercontent.com/assets/19218275/25510334/fdb53cf0-2bf1-11e7-8771-0f96c7ef8328.png)

-wenbin

**Comment by danmarsden** [comment]
thanks - I can't reproduce this in 3.2(latest) with boost or clean either. 

Most reports in Moodle core use a different column for the user icon (assignment reports etc) so I'm not too keen to merge them - I'm more likely to split the one in the take attendance page at some point.

**Comment by danmarsden** [comment]
I've also tested in FF and Chrome on ubuntu and MS Edge on windows 10 with boost/clean on 3.2 and master but haven't been able to reproduce this.

**Comment by xuwenbin** [comment]
I tried Moodle 3.2.2+ with default theme, the issue couldn't be reproduced. I'll contact Adaptable theme developer to further investigate the 1px width problem.

**Comment by danmarsden** [comment]
cool - thanks! - let me know if there's anything else I can do to help! - thanks for the reports! - FYI there are a few improvements coming through very soon (the ability for a teacher to set password for a self-marking session landed today in the master branch) - I'm hoping to add some form of random password setting function before I push this through to the 3.2 stable branch.

**Comment by xuwenbin** [comment]
Attendance is very good plugin. Though i am new to noodle world, i notice that this plugin long exists, and over years, new improvements are pushed in continuously.

That requires a very strong passion and consistent resources. I admire your work.

Best Regards,
Wenbin Xu

在 2017年4月28日，11:00，Dan Marsden <notifications@github.com<mailto:notifications@github.com>> 写道：


cool - thanks! - let me know if there's anything else I can do to help! - thanks for the reports! - FYI there are a few improvements coming through very soon (the ability for a teacher to set password for a self-marking session landed today in the master branch) - I'm hoping to add some form of random password setting function before I push this through to the 3.2 stable branch.
