### ISSUE TITLE
Unable to undo group grouping access restriction on attendance setting page?

### ISSUE THREAD

**Issue by xuwenbin** [danmarsden/moodle-mod_attendance#256]
In Attendance settings, I accidentally clicked "Add group grouping access restriction" button. Now, I want to undo it, but cannot find a place to delete or revoke.

-wenbin

**Comment by danmarsden** [comment]
I'm pretty sure this is historical (like that when I took over maintenance of the plugin) - and we may need to implement a restriction to prevent changing the session type if any attendance data has been saved but we should probably allow it to be changed if no attendance data has been saved.

**Comment by danmarsden** [comment]
I've just tested this and it seems to work fine for me. feel free to ask for help in the community forums if you are still having issues with this. Thanks!
