### ISSUE TITLE
<Sessions> tab is not highlighted and Course intro box is missing in "take attendance page"

### ISSUE THREAD

**Issue by xuwenbin** [danmarsden/moodle-mod_attendance#257]
When user clicks a session to take attendance, the page is refreshed but the new page doesn't highlight which tab it belongs to, and course intro box is missing from the new page.

Code changes seem required in take.php to fix above issues.

Old code at line 70 - 
`$tabs = new attendance_tabs($att);`

Modified code at line 70 - 
`$tabs = new attendance_tabs($att, attendance_tabs::TAB_SESSIONS);`

Inserting new code at line 73 and 74 - 
```
$title = get_string('attendanceforthecourse', 'attendance').' :: ' .format_string($course->fullname);
$header = new mod_attendance_header($att, $title);
```

Inserting new code at line 78 - 
`echo $output->render($header);`

Removing code - 
`echo $output->heading(....);`

**Comment by danmarsden** [comment]
Thanks 
The "take attendance" page is not quite the same as the sessions tab - the "sessions" tab shows a list of all sessions and the navigation stays on the page so that the user can return back to the full sessions list by selecting the "sessions" link. I'm not too keen on disabling the navigation back to the "sessions" tab by making that tab live when viewing the take attendance screen.

Also - not sure what benefit ther is into adding the $header to the take attendance page? - the take attendance page should be as light as possible to make it easy to see all the students. (still room for improvement on that take attendance page though)

**Comment by xuwenbin** [comment]
What motivated me to post this feedback is more from usability point of view.

1. Through **Sessions** tab, user enters "session list" and then "take attendance" pages. So, in order to keep consistency and be a reminder of which page user resides, it is better to keep the **Sessions** tab selected / highlighted all the time until user leaves the context (by either switching to another tab or entirely different pages)

2. UI design usually prefers keep the header / footer structure unchanged (e.g. the course intro box and navbar), while the content contained could vary from time to time. Again, this is ought to provide a consistent context for users

3. About disabling the navigation back to the **Sessions** tab, usually, a cancel or back button is provided on the page (e.g. take attendance page) for users to go back to previous page. Today, there's only one **Save attendance** button.

**Comment by danmarsden** [comment]
hmm - I'm not yet convinced sorry.

It's important for the "take attendance page not to take up too much real-estate with extra stuff around the edges If we're seriously talking about usability I think we'd probably want to completely reformat the take attendance page. (and make it more usable on mobile devices etc.)

**Comment by xuwenbin** [comment]
Indeed. In order to support mobile devices (phone, pad, etc.), many of current UIs require a redesign. It would take many efforts and much time.

Not sure if a plan with timeline is put in place?

**Comment by xuwenbin** [comment]
@danmarsden btw, I'm having an issue on introducing new strings in attendance.php file. I added new strings following the format of existing strings; uploaded the new attendance.php file onto server side. By checking custom language pack content in Admin->Language settings, I can see the new strings. However, when I tried to access the new string in code, e.g. get_string('abc', 'attendance'), it returns null.

Any advice?

**Comment by danmarsden** [comment]
No timeline at this stage and it depends on funding or extermal contributions. Strings are cached, Check under admin Lang settings to turn cache off.

**Comment by xuwenbin** [comment]
Thanks! Purging cache does the trick.

**Comment by danmarsden** [comment]
closing this as won't fix. Making this change doesn't improve overall usability of the take attendance page. Thanks!
