### ISSUE TITLE
Notice: Undefined property: stdClass::$idnumber error in mod_attendance

### ISSUE THREAD

**Issue by crmpicco** [danmarsden/moodle-mod_attendance#259]
Hi Dan,

I got the following error when viewing the report in mod_attendance.

```
Notice: Undefined property: stdClass::$idnumber in /var/www/moodle33t/mod/attendance/renderer.php on line 978
```
I wasn't forced to enter an idnumber when creating the user so it would seem the code is complaining about this missing member variable because it was never set.
```
foreach ($extrafields as $field) {
    $row->cells[] = $this->build_data_cell($user->$field, false, false); // <-- line 978
}
```
See screenshot.

![screen shot 2017-05-04 at 10 53 27](https://cloud.githubusercontent.com/assets/2536923/25689485/0af9f356-30bb-11e7-9ce2-40ffadc9e13e.png)

![screen shot 2017-05-04 at 11 28 24](https://cloud.githubusercontent.com/assets/2536923/25689652/dbd4c658-30bc-11e7-9d04-4dee69d0f314.png)

----
Regards,
Craig R Morton <craig@moodle.com>
Analyst Developer
Moodle HQ (MoodleCloud)

**Comment by danmarsden** [comment]
thanks - I've managed to reproduce this with the latest code too. not sure why it got missed but I'll get it sorted tonight.

**Comment by danmarsden** [comment]
- it's an issue with displaying records for temporary users in the report.

**Comment by danmarsden** [comment]
should be sorted now in 3.2 and 3.3 branches - thanks for the report!
