### ISSUE TITLE
Detailed explanation about attendance permissions?

### ISSUE THREAD

**Issue by xuwenbin** [danmarsden/moodle-mod_attendance#260]
l came across "Changing Attendances", "Manage Attendances", "Taking Attendances" permissions, and hard to understand what's the difference among them.

I clicked their names and tried to find documentation about them, but no luck.

-wenbin

**Comment by danmarsden** [comment]
I think "changing attendances" is the ability to re-take attendance for a session that has already had the attendance marked. "taking attendances" allows the session attendance to be taken (first time) - and "manage attendances" allows the creation and editing of the sessions themselves. The define permissions page links to the moodledocs wiki - but the moodledocs entry for each capability seems empty. 

btw - the right place to ask general questions like this is the moodle.org community forums in the attendance forum. The github issue tracker is supposed to be for bug reports. Thanks!
