### ISSUE TITLE
Dependencies check failed for mod_attendance 

### ISSUE THREAD

**Issue by rajeevdubey007** [danmarsden/moodle-mod_attendance#261]
Hi I am getting error after unzip the attendence module inside mod folder in moodle.
My current version of moodle is '3.3.4'.
I am getting following issue:
![image](https://cloud.githubusercontent.com/assets/13365691/25799254/f30a19e8-3401-11e7-9335-22a9f31b2023.png)

in above error there is version mentioned 'Moodle 2017011900' i.e adaptiveQuiz. I also installed that module and also related theme (i.e. cerulean theme as it is required for adaptiveQuiz module ) but still I am getting the same issue.

Please help on this issue.

**Comment by danmarsden** [comment]
Moodle 3.3.4 doesn't exist yet. 3.3(3.3.0) will be released next week. It sounds like you have downloaded the attendance plugin code for 3.3 and installed it in your older moodle version. You should remove the attendance code from your site, obtain the correct moodle version number and then download the correct attendance code for your moodle version from the moodle.org plugins database.
