### ISSUE TITLE
Data and Time is not visible after creating session in sessions list

### ISSUE THREAD

**Issue by rajeevdubey007** [danmarsden/moodle-mod_attendance#262]
Hi Currently I am using attendance module version '2016121303'.
Date and Time are not shown in session list page:
![image](https://cloud.githubusercontent.com/assets/13365691/25849629/d78cb0a0-34dc-11e7-8136-832679e96d5a.png)

Is there any setting I need to set? Please help.

**Comment by danmarsden** [comment]
I haven't seen this before - have you made any changes to the language pack for the attendance plugin?

**Comment by rajeevdubey007** [comment]
No, I simply installed the attendance plugin and try to create a session but after creating session I am getting the list without date and time.

**Comment by danmarsden** [comment]
Probably a compatibility issue with the parameters we're passing to strftime (function used to convert unix timestamps to user readable times.) What operating system is your site hosted on? - is it a Mac OS? - I just noticed we're using %P in the strftime call which looks like it is not supported on Mac OS.

**Comment by rajeevdubey007** [comment]
Hi Danmarsden,

We are using "Windows Server 2008 R2 standard". 
Should I change timestamp in code somewhere in order to work on my server?
Or if you have any idea please suggest.
Thanks.

**Comment by danmarsden** [comment]
as much as I'd like to encourage you to use a different O/S I guess we should support those unfortunate souls forced to use Microsoft systems.... :-)

here are the strings that will need changing:
https://github.com/danmarsden/moodle-mod_attendance/blob/master/lang/en/attendance.php#L278
https://github.com/danmarsden/moodle-mod_attendance/blob/master/lang/en/attendance.php#L280
https://github.com/danmarsden/moodle-mod_attendance/blob/master/lang/en/attendance.php#L281

Try changing the capital P in those lines to a small p and then clearing site cache to see if that helps.

if that isn't it, try changing the lower case l(for lima) to a capital I (for India) - and clear site cache.

let me know which combination of those works.

**Comment by rajeevdubey007** [comment]
Hi Danmarsden,

I tried every combination but it didn't work. Even I also installed the same module in local system that uses windows 7 but there I am getting the same issue.

![image](https://cloud.githubusercontent.com/assets/13365691/25948973/7f1dd082-3673-11e7-9ecc-66493836ad17.png)

I also checked the database and found value is saving in timestamp format. I think something is missing in date conversion (timestamp to system date) or perhaps might be any setting I am missing in moddle. I am trying to find the proper php file where actual date conversion is happening so that can find the proper solution.
If you have any suggestion, please suggest me so that I can resolve this issue.
Thanks.

**Comment by danmarsden** [comment]
have you tried using one of the core themes instead of your custom theme? - also make sure you cleared the cache correctly after making changes to the language strings.

I'll try to find some time to set this up on a windows server at some point next week and see if I can make any progress on it.

**Comment by rajeevdubey007** [comment]
Hi Dan,

Thanks for your support.
I have done few changes according to my feasibility in attendance.php file of language file and it is working fine for now.
![image](https://cloud.githubusercontent.com/assets/13365691/25998754/0eb29288-3740-11e7-9a6b-b683d65155df.png)
 I replaced **"h" with "M" as in windows d,m,y works** as of now what I find. what I changed in attendace file is written below just for your reference:

$string['strftimedm'] = '%M %d';
$string['strftimedmy'] = '%d %M %Y';
$string['strftimedmyhm'] = '%d %M %Y %I.%M%p'; // Line added to allow multiple sessions in the same day.
$string['strftimedmyw'] = '<nobr>%a %d %M %Y</nobr>'; //'<nobr>%a %d %h %Y</nobr>';
$string['strftimeh'] = '%I%p'; //'%l%P';
$string['strftimehm'] = '%I:%M%p'; // '%l:%M%P';
$string['strftimeshortdate'] = '%d.%M.%Y';

Right now I am testing the date and time in all places for proper working.
**AND yes one Important Note** for me theme cache did not work properly so I went to "moodledata" directory(path mentioned in config file) and remove cache directory from there, only then I can able to see changes(the changes I have done in attendance file).

I think above parameter will help you to make it more configurable according to windows and mac.

Once again thank you so much for your help :)

**Comment by danmarsden** [comment]
Thanks - looks like %h should probably be %b instead - I'll make that change in the core code - thanks for the help tracking it down!

**Comment by rajeevdubey007** [comment]
Hi Dan,

%b works great now.
One more thing, I have taken your code for displaying session time for following places:
string['strftimedmyhm'] = '%d %b %Y %I.%M%P'; // Line added to allow multiple sessions in the same day.
$string['strftimeh'] = '%l%P'; 
$string['strftimehm'] = '%l:%M%P';


![image](https://cloud.githubusercontent.com/assets/13365691/26044402/bb917fbe-3961-11e7-8c72-eb1dbd1070a9.png)


but above lines did not work for me so I changed l(for lima) to I(for India) and P to p.
After fixing my code looks like:
string['strftimedmyhm'] = '%d %b %Y %I.%M%p'; // Line added to allow multiple sessions in the same day.
$string['strftimeh'] = '%I%p'; 
$string['strftimehm'] = '%I:%M%p';
those string parameter works for me

![image](https://cloud.githubusercontent.com/assets/13365691/26044473/2ca53c0e-3962-11e7-8209-5eb01f80ef8b.png)

Please look these parameters in order to work in windows also(might be this could be the issue of timezone or location). It is possible that we can use other parameters also in order to work in windows as well as mac(if it is mac or windows issue), if Yes please find for us.

**Comment by danmarsden** [comment]
thanks - will take a further look!

**Comment by danmarsden** [comment]
new patches in master/3.3/3.2 branches - thanks for the help!
