### ISSUE TITLE
Feature Request in export CSV: Can we show teacher name along with the session details in csv file?

### ISSUE THREAD

**Issue by rajeevdubey007** [danmarsden/moodle-mod_attendance#263]
Can we show teacher name along with the session details in csv file?

My Requirement is that when we export any attendance, teacher name and session date and time should also include in csv file.

**Comment by danmarsden** [comment]
I don't think we'd add "the teacher" to the content of the csv export - I don't like the current export format much - typically export files should be in a format that allows them to be imported/manipulated easily. The way the attendance export adds extra rows to the top of the file for course and group that are not related to the actual table data is not ideal IMO and in future we may remove them from the top of the export file.

**Comment by danmarsden** [comment]
closing as won't fix as I don't plan to work on this but I'm happy to receive pull requests to improve the export.
