### ISSUE TITLE
Radio buttons spacing issue

### ISSUE THREAD

**Issue by cybernotic** [danmarsden/moodle-mod_attendance#264]
Hi,

I have attached an image of the issue, the image was taken from the actual attendance Moodle plugin page and the problem exists in Moodle 3.1.2 and 3.1.5. The radio buttons are too close to the labels which can be a bit confusing, the attendance plugin version we are using is 3.1.0.3

Is it possible to add a style hack to the radio button (margin-left: 15px) specifically for that page?

Or has this issue been resolved in later versions? I did look through the issues reported but I couldn’t find anything.

![radiobuttons](https://user-images.githubusercontent.com/18535468/26939284-ce1e31fc-4c6e-11e7-9946-7de672fbcaea.png)

Thanks for your time.

Regards
David

**Comment by danmarsden** [comment]
thanks for the report - I've been doing all my recent testing in BOOST which doesn't have the margin-right like the clean theme. I'll see if we can tidy this up and make it easier to target those radio buttons using css.

**Comment by danmarsden** [comment]
I've fixed this in the github branches for all versions 3.1 and higher. Thanks!

**Comment by cybernotic** [comment]
Thanks a lot for that and the quick responce!
