### ISSUE TITLE
Duplicating an attendance item and then changing session info causing error.

### ISSUE THREAD

**Issue by emanuelbrunson** [danmarsden/moodle-mod_attendance#265]
We have come across the error that when an attendance activity is duplicated and then any changes to the sessions causes the the following error:

Can not find data record in database table event.
https://docs.moodle.org/32/en/error/moodle/invalidrecord

Currently running Moodle 3.2.

**Comment by danmarsden** [comment]
what version of the attendance code are you using?

**Comment by davidlanier** [comment]
Here is the Mod / Attendence version info.
`$plugin->version  = 2016121301;
$plugin->requires = 2016111800;
$plugin->release = '3.2.3';
$plugin->maturity  = MATURITY_STABLE;
$plugin->cron     = 0;
$plugin->component = 'mod_attendance';`

**Comment by danmarsden** [comment]
thanks - I've pushed a fix for this onto the 3.2, 3.3 and master branches here in github

**Comment by davidlanier** [comment]
Thanks Dan!

**Comment by emanuelbrunson** [comment]
Thanks Dan!
