### ISSUE TITLE
 Notice: Undefined property: stdClass::$groupmembersonly

### ISSUE THREAD

**Issue by rlorenzo** [danmarsden/moodle-mod_attendance#266]
Using the plugin in Moodle 3.1 we are seeing these notices:
 
Notice: Undefined property: stdClass::$groupmembersonly in /usr/local/moodle/releases/3.x/mod/attendance/classes/structure.php on line 58

The groupmembersonly flag was removed in Moodle 2.8 and replaced with conditional activties: https://docs.moodle.org/28/en/Available_for_group_members_only

The code is going to have to be refactored to enable grouping support again, I believe.

**Comment by danmarsden** [comment]
Hi Rex - what version of the attendance code are you using? - that line doesn't match up with anything current that I can find. The only usage of groupmembersonly (which still need to be removed) use the call:
!empty($CFG->enablegroupmembersonly) before the groupmembersonly call so I assume you still have enablegroupmembersonly set to true on your site?

**Comment by danmarsden** [comment]
I've pushed a fix through to 3.1 branches and higher to remove the groupmembersonly reference. I haven't had a change to test grouping support though - let me know if you manage to test it and let me know how you go.

**Comment by rlorenzo** [comment]
Thanks! We will let you know if there are any problems with grouping support.
