### ISSUE TITLE
Minutes are not displayed, when "0" selected

### ISSUE THREAD

**Issue by adpe** [danmarsden/moodle-mod_attendance#273]
Hello

It's not an big error, but it look's strange. Would be better when the minutes are always displayed, also 10:00 and not only 10. 

![image](https://user-images.githubusercontent.com/9467708/30016996-b729d8ce-9157-11e7-93ce-607d160f2b9c.png)

Kind Regards
Adrian

**Comment by danmarsden** [comment]
Those should have the text "pm" included in those strings (2pm - 10pm) - it could be an issue with your Language pack or the compatibility of the strftime strings we are using.
What Operating system is your web server running on (win/linux/MaxOS) - not your desktop - the server.
And what language are you currently using? - if you switch to using English in Moodle does it change to 2pm - 10pm or does it remain as 2 - 10 ?

thanks,

**Comment by adpe** [comment]
@danmarsden 
Thanks for your reply. Our moodle application 3.2.4 runs on a CentOS 7.0 server. The default system language is german with de_CH.UTF-8.

When I set the course and system language to english the failure remains.

**Comment by danmarsden** [comment]
thanks - just to confirm in english it shows "2 - 10" - not "2pm - 10pm" ?

Also probably good to confirm which version of the attendance plugin you have installed? - we made a few changes to the config of how those times show in a recent version.

**Comment by adpe** [comment]
We've installed the newest version of MOODLE_32_STABLE > 3.2.16 (2016121321). On our instance it's without am/pm. 

When I enter per example 5pm-7pm (17-19 in german) it shows only 5-7 in the english version. It's really confusing. I've noticed that it's also not working properly when using ":05" as minutes, it's also missing the "pm" part in the english version, in the german it's correct.

English:
![image](https://user-images.githubusercontent.com/9467708/30052257-3469ef5e-9225-11e7-957a-e79ca1286591.png)
German:
![image](https://user-images.githubusercontent.com/9467708/30052285-467752fe-9225-11e7-878e-d0165719c761.png)

I think the best solution is to provide always the minutes when selected ":00" and to fix the bug in the english version with the missing "am/pm".

**Comment by danmarsden** [comment]
thanks - it was changed to strip out the :00 based on community feedback (and from memory it was a community patch I merged to do it) but it's not very reliable so we'll need to look at it again. Thanks for the reports/screenshots.

**Comment by danmarsden** [comment]
I've just pushed a fix that should improve this when English is selected (it should add AM/PM when using a 12hr clock) - but the fix for the german lang pack which is set to use a 24hr clock should be adjusted within the lang pack itself on the AMOS site. Thanks!
