### ISSUE TITLE
lock the student names so they float. (like Moodle Gradebook)

### ISSUE THREAD

**Issue by reactor0138** [danmarsden/moodle-mod_attendance#274]
lock the student names so they float. On the attendance block, on the report tab, where it becomes near impossible to check attendance after you have add 20 or more slots (unless you have 2 screens or a really high res setting on your display). It would work like Gradereport does where the name stay as you scroll across the page.

**Comment by danmarsden** [comment]
you've asked about this before! :-) see #213 - closing this as a duplicate.

**Comment by reactor0138** [comment]
Cheers Dude. Thought I had but couldn't Find it. Might see you in Aus in a couple of weeks. We have some possible work that needs scoping so we can get more functionality out of our Moodle. All the best . Scott

**Comment by danmarsden** [comment]
Will be great to see you there! - will be interested to hear about the work you are looking at too!
