### ISSUE TITLE
wrong date in version for 3.4.1 ;)

### ISSUE THREAD

**Issue by nwp90** [danmarsden/moodle-mod_attendance#278]
It was September, not October...

**Comment by danmarsden** [comment]
haha - good spotting - was doing this quickly from the Moodlemoot in sydney between sessions and got that slightly wrong. Once it's been bumped it's quite hard to go back - and this relates to the "master" branch only which is for 3.4 which doesn't officially come out until November - hopefully you're not using this branch on an earlier release - thanks! :-)

It shouldn't cause any issues (other than looking like the plugin comes from the future if you install it in a 3.4 site)
