### ISSUE TITLE
Error when student tries to register own attendance

### ISSUE THREAD

**Issue by sleitao** [danmarsden/moodle-mod_attendance#279]
When a student tries to register his own attendance you get an error:
_Can't use function return value in write context in /var/www/html/moodle/mod/attendance/attendance.php on line 42_

MOODLE_31_STABLE

The problem is related to:
http://php.net/manual/en/function.empty.php
_Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false._ 

To avoid the error on php versions prior to PHP 5.5 empty(get_config(...)) should not be used.
Maybe something like:

> $configcanmark = get_config('attendance', 'studentscanmark');
>         if (!$configcanmark || ....))

**Comment by danmarsden** [comment]
thanks for the report - the current version doesn't officially support php 5.5 if you see the supported versions on the plugins db entry here:
https://moodle.org/plugins/pluginversion.php?id=14895

you really should be prioritising an upgrade to use PHP 7 or higher - the performance improvements are very noticeable with page-loads and overall server performance.

I'll push through a patch for this but please be aware that I do not regularly test with php 5.5 and you may run into other issues in future unless you upgrade.

**Comment by danmarsden** [comment]
in fact you're using php 5.4 right? - I definitely do not do any testing with that... you really need to upgrade your PHP version.

**Comment by danmarsden** [comment]
have pushed a patch into the 3.1 branch for this now.
