### ISSUE TITLE
Import or Restore marks attendance as taken

### ISSUE THREAD

**Issue by SWiT** [danmarsden/moodle-mod_attendance#287]
In v3.3.13 (2017050220), if you import an Attendance activity from another course with sessions that have been taken the sessions are marked as already be taken in the new course. The Teacher sees the "Change attendance" icon instead of the "Take attendance" icon. They won't have any students marked in the sessions though.

In addition, sessions that had not yet been taken prior to import will not import.

I feel all sessions should be imported but they need to be marked as not taken yet.

**Comment by SWiT** [comment]
After talking it over with co-workers. I've reconsidered my stance on importing the sessions. If user data isn't included then neither should sessions.  When a teacher is importing or restoring course content semester to semester the session dates and times aren't likely to be the same. The dates don't currently translate based on the start date of the course and I don't think they could if you consider the M,T,W,Th,F every X weeks until a certain date for repeating sessions settings. Since the teacher is going to need to delete all the sessions and recreate them then why import them?

**Comment by danmarsden** [comment]
Thanks for the report.

I'm not sure we could change the behaviour like this (preventing sessions from being restored) as there is probably a number of people that rely on this behaviour. The fact that people are noticing the sessions are already listed as "taken" suggests that they are trying to use the sessions that have been restored.

feel free to help us work on this issue further.

**Comment by danmarsden** [comment]
just pushed a fix to all supported branches that will prevent the restored sessions from doing this - we could look at preventing sessions from being restored at another time. Thanks for the report.
