### ISSUE TITLE
Multiple Sessions add error in 3.4

### ISSUE THREAD

**Issue by jtouw** [danmarsden/moodle-mod_attendance#292]
When I add multiple sessions allowing students to record their own attendance, with automatic marking set to YES, I get the following error:

Notice: Undefined property: stdClass::$studentpassword in C:\inetpub\wwwroot\moodle\mod\attendance\locallib.php on line 588 Notice: Undefined property: stdClass::$studentpassword in C:\inetpub\wwwroot\moodle\mod\attendance\locallib.php on line 588

The session then appears to add normally.

The ONLY time I get this error.  If I add a session with auto marking set to YES and it is a single session, no error.  If I add multiple sessions and Students NOT Recording their own attendance (box is unchecked), no error.

**Comment by danmarsden** [comment]
thanks for the report - found the issue and I've pushed a fix into github to tidy that up. I'll be updating the version in the plugins db soon.
