### ISSUE TITLE
Screen resize

### ISSUE THREAD

**Issue by maireanu** [danmarsden/moodle-mod_attendance#293]
Blocks is not rescaling to the size of the screen you're using. I am currently using Safari, with screen resolution 2560 x 1600 and the theme  which I am using on moodle is bootstrapbase . I have upload a picture on how it is displayed on the link

https://imgur.com/a/ycr0y

I have tested on Firefox, Chrome and there is displayed correctly

Using moodle version 3.4

**Comment by danmarsden** [comment]
I presume you closed this as you discovered it was an issue with your local theme or css you had applied to the site.

**Comment by maireanu** [comment]
Yes it was an CSS problem. Thank you for the support
