### ISSUE TITLE
Allow teacher to open sessions for self marking before session start.

### ISSUE THREAD

**Issue by emmarichardson** [danmarsden/moodle-mod_attendance#297]
We use courses as events.  Currently, I can only start the attendance session to begin five minutes after the start of class.  
We would like to be able to start the session before the start of class but this currently has the effect of hiding it never to be seen again...
It would be nice if there was a site wide setting that allows teachers to create sessions that start before the course start date.
We do not want students able to take attendance outside of the session time.

**Comment by danmarsden** [comment]
Thanks Emma, 
should this be a site-wide global duration setting that allows you to specify an "early open" duration for student marking sessions? - eg student marking available X min before session start? - or does it need to be at the individual session level to allow a teacher to decide per session?

**Comment by emmarichardson** [comment]
I would be more than happy with either but I imagine others might like it
at the course level... That would definitely give people more flexibility.
Thanks!

**Comment by emmarichardson** [comment]
Any chance of getting this added or do you have the code area I should hack?

**Comment by danmarsden** [comment]
here's the bit that does it:
https://github.com/danmarsden/moodle-mod_attendance/blob/fe76596b7cc48c9f5fa91e91966fad91832ae7d5/locallib.php#L439

**Comment by emmarichardson** [comment]
Thanks Dan!

**Comment by emmarichardson** [comment]
So reading that it looks like that is referencing the current time and not
the course start time? Am I wrong? Which is very possible as I am not a
code writer!! I am looking for the part that does not allow you to show a
session that starts before the course start...

**Comment by danmarsden** [comment]
yeah - sorry I misunderstood what you were asking for there - you'll need to find a developer with some time to modify the plugin to do this (feel free to get in touch if you want to fund the work) :-)

**Comment by danmarsden** [comment]
Emma - Teachers should be able to create sessions prior to the course start date - the add attendance session form will warn you that the session you have created is prior to the course start date, but if you just hit the "add" button in the form it will add it anyway.

Or am I missing something else here?

**Comment by emmarichardson** [comment]
I might be willing to fund…depending on what you would charge.  I have a
developer I use who is pretty cheap but would rather go through you
directly if we could get into the plugin core.

I think it might be beneficial for several people if we had a setting where
you could decide if you wanted to make attendance sessions available before
the official start of course - maybe a time selector (so many minutes/hours
for example).

Emma Richardson
Distance Learning Coordinator
Direct: 719-771-4022


From: Dan Marsden <notifications@github.com> <notifications@github.com>
Reply: danmarsden/moodle-mod_attendance
<reply@reply.github.com>
<reply@reply.github.com>
Date: July 26, 2018 at 4:41:05 PM
To: danmarsden/moodle-mod_attendance
<moodle-mod_attendance@noreply.github.com>
<moodle-mod_attendance@noreply.github.com>
Cc: emmarichardson <emmar@ecboces.org> <emmar@ecboces.org>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [danmarsden/moodle-mod_attendance] Allow teacher to set
sessions to start before course start. (#297)

yeah - sorry I misunderstood what you were asking for there - you'll need
to find a developer with some time to modify the plugin to do this (feel
free to get in touch if you want to fund the work) :-)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/danmarsden/moodle-mod_attendance/issues/297#issuecomment-408257143>,
or mute the thread

**Comment by danmarsden** [comment]
Did you see my last comment? Is your issue that you have to hit submit twice on the form? Or did you not notice that you can already do this?

**Comment by emmarichardson** [comment]
They can but they are hidden which makes them useless…
I am seeing if anyone objects to me allowing students to submit attendance
outside of session time - it is not perfect as I would prefer to shut it
down at the end of the course but it would work for now..


Emma Richardson
Distance Learning Coordinator
Direct: 719-771-4022


From: Dan Marsden <notifications@github.com> <notifications@github.com>
Reply: danmarsden/moodle-mod_attendance
<reply@reply.github.com>
<reply@reply.github.com>
Date: July 26, 2018 at 8:37:28 PM
To: danmarsden/moodle-mod_attendance
<moodle-mod_attendance@noreply.github.com>
<moodle-mod_attendance@noreply.github.com>
Cc: emmarichardson <emmar@ecboces.org> <emmar@ecboces.org>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [danmarsden/moodle-mod_attendance] Allow teacher to set
sessions to start before course start. (#297)

Emma - Teachers should be able to create sessions prior to the course start
date - the add attendance session form will warn you that the session you
have created is prior to the course start date, but if you just hit the
"add" button in the form it will add it anyway.

Or am I missing something else here?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/danmarsden/moodle-mod_attendance/issues/297#issuecomment-408293762>,
or mute the thread

**Comment by danmarsden** [comment]
You can change the default view for teachers under admin > plugins > attendance "Default view on login" and set it to "all" which might do what you need. If not, can you please make another attempt at describing what you are asking?

**Comment by emmarichardson** [comment]
What we need is to be able to have students submit their attendance 30
minutes prior to the start of the course.  This way, our attendees can
checkin before the start of the live training and not waste time once it
starts.  We use Moodle as an event management system and it is way more
convenient to not be limited to having sessions only show up if they are
created after the start of the course.  We cannot start the course early
because it is tied into the calendar and needs to have the correct start
time.  We do not want the students to be able to submit attendance anytime
- we want to shut it off at the end of the session so we cannot allow them
to submit anytime…

Currently if we create a session that starts before the course, it is
hidden.  Yes, teachers can view it, but students cannot. Even a permission
to allow students to see and submit hidden sessions might work…or an option
to allow teachers to show and open hidden sessions…I could even work with
an option to turn off hidden sessions altogether as they have no purpose in
any of my installations…

If any of this sounds like something you would want to bid or would be an
improvement to the plugin overall, please let me know.  I have been playing
a little bit on my own but haven’t got very far yet and would really prefer
to have something as part of the plugin rather than a hack that I
continually need to work on.

Thanks
Emma


Emma Richardson
Distance Learning Coordinator
Direct: 719-771-4022


From: Dan Marsden <notifications@github.com> <notifications@github.com>
Reply: danmarsden/moodle-mod_attendance
<reply@reply.github.com>
<reply@reply.github.com>
Date: August 27, 2018 at 2:47:50 PM
To: danmarsden/moodle-mod_attendance
<moodle-mod_attendance@noreply.github.com>
<moodle-mod_attendance@noreply.github.com>
Cc: emmarichardson <emmar@ecboces.org> <emmar@ecboces.org>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [danmarsden/moodle-mod_attendance] Allow teacher to set
sessions to start before course start. (#297)

You can change the default view for teachers under admin > plugins >
attendance "Default view on login" and set it to "all" which might do what
you need. If not, can you please make another attempt at describing what
you are asking?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/danmarsden/moodle-mod_attendance/issues/297#issuecomment-416363360>,
or mute the thread

**Comment by danmarsden** [comment]
Thanks Emma, 

To confirm - the session starts at the same time as the course start time, but students arrive early and you want them to start marking their attendance before the session starts?

If that is the case - one of the things I've wanted to do is provide the teacher a way to open a session for self-marking earlier than the session start time by giving them a setting in the session setup that defines a number of minutes prior to the start time at which point the students can enter the attendance and self-mark.

Does that sound like it would work in your situation too?

**Comment by emmarichardson** [comment]
That would be perfect actually!

**Comment by emmarichardson** [comment]
Give me an idea of cost - I might be able to fund if not too much.  If not,
I might see if my coder would be willing to do it and put in a pull request.

Emma Richardson
Distance Learning Coordinator
Direct: 719-771-4022


From: Dan Marsden <notifications@github.com> <notifications@github.com>
Reply: danmarsden/moodle-mod_attendance
<reply@reply.github.com>
<reply@reply.github.com>
Date: August 30, 2018 at 10:18:28 PM
To: danmarsden/moodle-mod_attendance
<moodle-mod_attendance@noreply.github.com>
<moodle-mod_attendance@noreply.github.com>
Cc: emmarichardson <emmar@ecboces.org> <emmar@ecboces.org>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [danmarsden/moodle-mod_attendance] Allow teacher to open
sessions for self marking before session start. (#297)

great - that makes a lot more sense and I've updated the subject of this
issue to reflect the intent. This is something I'd like to do at some
point, but I've got quite a bit of work on at the moment and it's unlikely
I'll have time to look into it in the short-term. If you are interested in
funding the work please get in touch and I can see if one of our other devs
has capacity to take this on, otherwise pull requests are always welcome!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/danmarsden/moodle-mod_attendance/issues/297#issuecomment-417547918>,
or mute the thread

**Comment by danmarsden** [comment]
drop me a private message and I can provide information on our rates etc.

**Comment by abhimanyuZ** [comment]
Is someone still working on this enhancement? If not I would like to work on it.

**Comment by danmarsden** [comment]
no one is actively working on this afaik.

**Comment by emmarichardson** [comment]
If it helps at all, I have hacked the following core files /classes/structure.php /classes/summary.php and add_form.php and simply added -7200 to the end of course start date anywhere I found a reference to the course start date in relation to the attendance session date.  Unfortunately, course start date is not named consistently across the files because I was hoping to create a variable that you could then reference with a setting that would add whatever number of seconds/minutes etc that you wanted to allow early attendance marking.  This is a pretty ugly hack but it works for my needs for now.  Of course, I have not upgraded the plugin in a while because I wasn't sure what changes might have been made that might break this hack.  I plan to download an updated version and try it again to see if I can then get upgraded on my live site.

**Comment by danmarsden** [comment]
This is now included in the version for Moodle 4.0 and higher - it allows the teacher to set a duration to open the session for marking when creating the session.

**Comment by emmarichardson** [comment]
Thanks Dan . That is awesome! No more hacking the code!!

**Comment by danmarsden** [comment]
I've only performed limited testing on it - would be good to hear if you get a chance to test and if it works for your case!

**Comment by emmarichardson** [comment]
Sadly, it still does not allow the session to open before the start of the course..

**Comment by danmarsden** [comment]
Whoops - should be a  easy fix, will try to come back k to this one soon.

**Comment by danmarsden** [comment]
Hi @emmarichardson,
If you have a course start at 5pm, and a session start at 5pm, but you have the "Open session early for marking" set to 2hrs, the students should be able to see the session for self-marking fine.

What this change doesn't do, is let you have a session set to start at 3pm, but a course start at 5pm - if you have the session start time set to "3pm" it will drop that from the page because it's before the course start date.

Do you still need a session listed as beginning "before" the course date itself? - can you give an example?

**Comment by emmarichardson** [comment]
Oh maybe I didn't understand the working of it. That scenario would
actually be better. I will play with it tomorrow again.

**Comment by danmarsden** [comment]
Hi Emma - do you think this is sufficient now? - or do we need to keep this open and look at something else there?

**Comment by emmarichardson** [comment]
No this works great. Thank you Dan. Now I just have to figure out how to
upgrade without having to recreate all the sessions I have.

**Comment by danmarsden** [comment]
Great!
