### ISSUE TITLE
Error 500 with Excell export

### ISSUE THREAD

**Issue by dngv** [danmarsden/moodle-mod_attendance#299]
I try to get MS Excell export report, and I got **error 500**, mod/attendance/export.php. Moodle v 3.4, version of mod - 3.4.4.,  apache 2.4, php 7.1, FreeBSD 11.

_in logs - - [24/Mar/2018:03:11:24 +0300] "POST /mod/attendance/export.php HTTP/1.1" 500 -
in brouser (Chrome, FF) - blank screen with ERR_INVALID_RESPONSE_

**UPDATE:** **if change php version to 7.0 all work correct.**

**Comment by danmarsden** [comment]
"error 500" is a generic error - you need to get more detailed information from your error log.

we use Moodle's core export lib for excel exports which are known to use a lot of memory - I'd guess you're running out of memory and your php 7 config is set to allow more memory. Does the CSV export work (it uses a lot less memory to generate)

Can you please confirm this and obtain more useful information from your error log.

**Comment by dngv** [comment]
CSV and OpenDocument on this system work correct, only Excel export with error 500. So error log has only one line for this error - like as

[26/Mar/2018:23:11:24 +0300] "POST /mod/attendance/export.php HTTP/1.1" 500 -
