### ISSUE TITLE
Sending warning messages by maximum possible percentage

### ISSUE THREAD

**Issue by ramarasty** [danmarsden/moodle-mod_attendance#301]
At my educational institution, attendance warnings are sent when students have an attendance percentage lower than a threshold over all the sessions for a course. For example, if the acceptable absence percentage is 10% for a course, then if a student has a maximum possible attendance of less than 90%, they could be sent a warning message.
Sorry if my English is not great.

**Comment by danmarsden** [comment]
Hi there, 

This is not something I plan to change at this stage, but feel free to get in touch if you want to fund further improvements to the plugin, alternatively pull requests are also welcome.
