### ISSUE TITLE
Please support Privacy API

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-mod_attendance#304]
Although there is a 3.5 version, it doesn't appear to provide support for the Privacy API

**Comment by danmarsden** [comment]
Thanks Howard. I'm planning to add null providers to the plugins I support that don't store any user data but I'm hoping that people who need gdpr support might contact me privately and offer to pay for the time to implement support. (Or submit a pull request) :-)

**Comment by danmarsden** [comment]
HQ moodlecloud team had some time and completed this for us  :-)
