### ISSUE TITLE
Display all instances of module when viewing index.php

### ISSUE THREAD

**Issue by rlorenzo** [danmarsden/moodle-mod_attendance#307]
It is expected behavior of the index.php page for course modules to list all the instances of that module in the course.

This is not currently happening in the current version of the plugin:

https://github.com/danmarsden/moodle-mod_attendance/blob/ccf59f35c6ae219a710c62f5f10272f87dbfb879/index.php

We expose the index.php path to our users in our lefthand nav and others do so through the Activities block. This page should follow the conventions of other modules

Right now it just displays the first instance of the module.

**Comment by danmarsden** [comment]
Hey Rex - looks like I noticed that when I took over maintenance and added a "todo" in 67909008d3db05ac59ed927af60438913aa4a328 but never fixed it. I can't see myself spending any time fixing this but pull requests are always welcome! :-)
