### ISSUE TITLE
Missing month. Date not change to PT format

### ISSUE THREAD

**Issue by dinism** [danmarsden/moodle-mod_attendance#308]
In English
![imagem](https://user-images.githubusercontent.com/14828021/41811197-fc3895a4-7702-11e8-9a35-e6e8fc27810e.png)

In Portuguese (Portugal)
![imagem](https://user-images.githubusercontent.com/14828021/41811199-0c00a530-7703-11e8-8573-424d1df8c29c.png)

**Comment by danmarsden** [comment]
Hi there,

I only maintain the English lang pack within this plugin. All other translations are maintained by the official Moodle translation site: https://lang.moodle.org/

Couple of things that might be useful - It uses the PHP function strftime:
https://www.w3schools.com/php/func_date_strftime.asp

and the english strings in attendance for these dates are defined here:
https://github.com/danmarsden/moodle-mod_attendance/blob/master/lang/en/attendance.php#L445

One of the issues with Strftime is that not all parameters work with all operating systems.
I suspect the PT lang string is using the %e parameter in the lang pack which is not supported on Windows based servers. (I'm also guessing you are hosting your Moodle site on windows?)

In any case - closing this as I do not control or manage the PT Translation - if you would like this to be modified you need to do this on the Moodle Translation site (https://lang.moodle.org)

thanks!

**Comment by dinism** [comment]
I'm a PT-PT Translator. The site is Linux Hosted.
SOLVED:  %p was incorrectly translated to %P. 
THANKS for this plugin.
