### ISSUE TITLE
Add option to Show Description on Course Page

### ISSUE THREAD

**Issue by pkgh** [danmarsden/moodle-mod_attendance#319]
For consistency with the core activities it would be nice to be able to force the Description of the activity to appear on the Course page. Below what it looks like for Chat:

![2018-08-05 16_15_53 - editing chat - google chrome](https://user-images.githubusercontent.com/6607293/43686733-01efc1a4-98cb-11e8-85e0-a550a0fbc03b.png)

**Comment by danmarsden** [comment]
makes sense - feel free to help us work on this. Thanks!

**Comment by pkgh** [comment]
I'm not much of a coder, I'm afraid. But if think of something, I'll certianly come back here :)

**Comment by SSH230** [comment]
Is there any update on this functionality? I'm interested in this as well. 
I believe the function attendance_support needs the following case added to its switch statement?  

> case FEATURE_SHOW_DESCRIPTION:        
>        return true;

But maybe I'm missing something as my PHP is not my forte. 
(relevant block: https://github.com/danmarsden/moodle-mod_attendance/blob/bc52a40f075a0b8a34a3f2ebda9051dc07de928d/lib.php#L35)

**Comment by danmarsden** [comment]
no updates, pull requests or funding to pay for my time for feature improvements are always welcome.

If you find the code change you mentioned worked for you, make sure you post back here to let us know.

thanks,

**Comment by abhimanyuZ** [comment]
Hello Sir,
I have 2 approach:
1.  Remove the checkbox "display description on course page" and in the code mark it as checked 
2.  Mark the checkbox by default. Disable it. And in the PHP code, mark it as checked.
I prefer option 2.
Your thoughts?

Thanks

**Comment by danmarsden** [comment]
this was recently completed in pull request #368 - I just forgot to close the issue here - thanks for the reminder!
