### ISSUE TITLE
Add new lang strings to AMOS

### ISSUE THREAD

**Issue by adpe** [danmarsden/moodle-mod_attendance#320]
Hello @danmarsden 

Can it be, that these new strings are missing in the official translating database? We need them for the German version.

- $string['calendarevent'] = 'Create calendar event for session';
- $string['calendarevent_help'] = 'If enabled, a calendar event will be created for this session. If disabled, any existing calendar event for this session will be deleted.';

The german versions would be:
- $string['calendarevent'] = 'Kalenderereignis für Lerneinheit erstellen';
- $string['calendarevent_help'] = 'Wenn dies aktiviert wird, wird ein Kalenderereignis für diese Lerneinheit erstellt. Wenn dies deaktiviert wird, wird jedes vorhandene Kalenderereignis für diese Lerneinheit gelöscht.';

Thank you
Adrian

**Comment by danmarsden** [comment]
Hi Adrian,

AMOS only gets updated when the version in the Moodle plugins db is updated. You will be using the version from github which is more up to date and contains the new calendar event feature.

I'll try to update the plugins db with the new versions soon. Thanks!
