### ISSUE TITLE
Sum of hours to date

### ISSUE THREAD

**Issue by Markibacsi** [danmarsden/moodle-mod_attendance#322]
Dear all

Fantastic plugin by the way.

My school would like to use the attendance plugin as a way of recording the teachers hours. Is there a way of reporting the total hours of classes where the attendance has been taken?

And/or any suggestions on where to pull the data (Teacher, Course, Hours) from using SQL?

Thanks in advance :)

**Comment by danmarsden** [comment]
Good to hear you find it useful!

That would require a developer to spend some time generating a report that does this for you. You could try asking in the community forums (more people read the posts there than will see comments in github issues.)
https://moodle.org/mod/forum/view.php?id=741

This isn't something I can help with for free though sorry!
