### ISSUE TITLE
Problem when students try to give themselves marks

### ISSUE THREAD

**Issue by iPintoBean** [danmarsden/moodle-mod_attendance#331]
We are having an issue where the attendance session is set to allow students to take their own attendance but when they navigate to the page it just shows question marks where the green dot used to be. They are not able to click on the question mark to record anything.

**Comment by danmarsden** [comment]
I'm closing this as there has been no response and there is not enough information here to consider this as a bug. If you are still having issues you might want to try asking for help here: 
https://moodle.org/mod/forum/view.php?id=741
