### ISSUE TITLE
Confirmation message for delete session is misleading

### ISSUE THREAD

**Issue by danielneis** [danmarsden/moodle-mod_attendance#332]
Hi,

currently when one tris to delete a session the module is using the "deletecheckfull" string from core/moodle, that reads:
Are you absolutely sure you want to completely delete the user Session, **including their enrolments, activity and other user data?**

This makes some users afraid of deleting sessions.
As this is not true (the enrolments, activities and other user data are not deleted) could we use a better wording there? =)

**Comment by danmarsden** [comment]
haha - yeah makes sense! - feel free to submit a pull request otherwise I'll get to this soon. Thanks for the report!
