### ISSUE TITLE
Confusing plugin settings

### ISSUE THREAD

**Issue by azito122** [danmarsden/moodle-mod_attendance#333]
I think that the current settings page is a bit confusing. There are settings represented in the main section that are duplicated in the Defaults section, but whose wording does not indicate the interaction between the settings. For example:

![image](https://user-images.githubusercontent.com/14895702/46420943-166cf680-c6ff-11e8-94f0-d5b7503fc7fc.png)
![image](https://user-images.githubusercontent.com/14895702/46420964-2553a900-c6ff-11e8-8bd8-f8615e9fa0e9.png)

Does the first setting only enable calendar event creation, and the default controls whether it actually happens?

Additionally, there is at least one setting that is _only_  in the Defaults section:
![image](https://user-images.githubusercontent.com/14895702/46421162-8c715d80-c6ff-11e8-9c20-0e5d9853e5fc.png)

This is confusing since many other default settings have corresponding base settings.

**Comment by danmarsden** [comment]
Feel free to submit a pull request to improve the settings page.

The default session settings are used when creating a new session - whatever the defaults are set here will be set in the add new session form (as with the default settings in other plugin settings pages.)

The settings higher in the page allow the admin to completely enable or disable certain functionality. If "create calendar events" is disabled, then the teacher will not be presented with the setting in the session creation form. 

Ideally if the top "Create calendar events" setting was disabled then the bottom default setting would be hidden in the form but the Moodle form settings lib doesn't allow for this sort of behaviour afaik.

Hopefully that helps to explain it. I'm closing this as there isn't a specific improvement suggestion here, but feel free to submit a specific change you think would help or a pull request to improve the structure to make this clear.

thanks!
