### ISSUE TITLE
Viewing single session table total counts in users who are unenrolled from course

### ISSUE THREAD

**Issue by t6nis** [danmarsden/moodle-mod_attendance#336]
Noticed a small bug. When session is entered and afterwards a user is unenrolled, the total counter at the bottom shows still the old number but the unenrolled user is not displayed in the table.

Steps to reproduce:
1. Create a course and enrol with 3 users.
2. Create attendance with one random session.
3. Enter "Present" for all 3 users and afterwards notice the Present = 3 at the bottom.
4. Unenrol one user from course
5. View the attendance session and see that 2 users are displayed in the report but at the bottom Present = 3.

Thats because mdl_attendance_log does not remove the user data when unenrolling from course.

**Comment by t6nis** [comment]
I made a pull request to fix this - https://github.com/danmarsden/moodle-mod_attendance/pull/337
Basically just check if log->studentid is existing in users.

**Comment by t6nis** [comment]
Hey! I removed the extra carriage. I hope its all good now.

**Comment by danmarsden** [comment]
merged into master and older supported branches - thanks!
