### ISSUE TITLE
Bad attendance report table formatting with Moodle 3.5.2

### ISSUE THREAD

**Issue by lshpani98** [danmarsden/moodle-mod_attendance#338]
we recently updated to Moodle 3.5.2 and updated this plugin to the latest version (3.5.3) which should be compatible. For the MORE theme, in the Attendance Report page the table of users split between the user names and the emails, just like shown in the image attached. This doesn't seem to be caused by our core code or custom css (we removed css customizations and it's still happening). 
![attendance](https://user-images.githubusercontent.com/35934121/46873970-02637c00-ce06-11e8-9370-17d48c184811.png)

I applied a css fix by making the position of the headcolumn inherit instead of fixed, but still added some left margin so it is a little shifted to the right like it was before the update. Also, the icon next to the -/+ icon next to "Users" was really close to the title so I added some left padding for that too. 

`#page-mod-attendance-report .attendancereporttable .headcol{
position:inherit !important;
}
#page-mod-attendance-report .attendancereporttable {
margin-left: 10px !important;
}
.attendancereporttable img.icon{
padding-left:5px; 
}`

After the fix: 
![screen_shot_2018-10-10_at_4 11 23_pm](https://user-images.githubusercontent.com/35934121/46874295-d399d580-ce06-11e8-8210-11ec9a3709bd.png)

However, this is a short-term solution and it would be nice to have a fix in the plugin. 
Thank you! 

Best,
Liana

**Comment by engrmshahzad** [comment]
but how i can show username (roll number) in attendance ?

**Comment by danmarsden** [comment]
@engrmshahzad please ask for help in the community forums - see: https://moodle.org/mod/forum/view.php?id=741

**Comment by danmarsden** [comment]
@lshpani98 - looks like this is just an issue with the more theme and your css changes prevent the floating user info on the right - I'll have a look to see if we can target this specifically for the more theme a bit.

**Comment by danmarsden** [comment]
@lshpani98 - I've just pushed a fix into the master branch that tides this up a lot. It could probably still do with some improved margins on the attendancereport table so that the headcol doesn't overlap on smaller windows, feel free to make any further suggestions and thanks for the report!

**Comment by danmarsden** [comment]
- if you get a chance to test the "master" branch here in git before I release this to the plugins db for Moodle 3.5 let me know!

thanks,

**Comment by lshpani98** [comment]
Hello Dan, 

Thank you so much for getting back to me. I tested the new master branch and removed my css fix and I took a screenshot: 
![screen shot 2018-10-19 at 9 29 49 am](https://user-images.githubusercontent.com/35934121/47221282-f5083d80-d381-11e8-9a2d-5627c04c7231.png)
The users' column doesn't float to the right anymore, but it is still detached from the rest of the table. 

Thanks,
Liana

**Comment by danmarsden** [comment]
Yeah - still needs some improvements to the position/margins but should be more usable. Feel free to suggest further improvements!
