### ISSUE TITLE
Calendar Events not removed entirely

### ISSUE THREAD

**Issue by tallthom** [danmarsden/moodle-mod_attendance#347]
Attendance version | 3.5.5 | 2018051407

Our university schedules all the class sessions using the Attendance module. In the most recent versions, Calendar events were generated for all the sessions. However, this makes the calendar useless now b/c there are course sessions every day every period. 

When unchecking the default to add events to the Calendar, we get asked to run the "reset Calendar" routine to remove the Attendance events. However, even after running that routine, it doesn't remove the events. I'm almost ready to go through the table and remove them manually, but wanted to post here first to see if others are having this issue.

I would like to help collect more information about the issue. If the developers can point me in a direction, I'll go dig around for more information.

<img width="242" alt="screen shot 2018-11-06 at 14 54 44" src="https://user-images.githubusercontent.com/1357329/48045533-0d76b580-e1d4-11e8-829b-ffaf68ae5e81.png">

Also, this made me think that there might be a need for a "Rebuild Calendar" routine in Moodle. Does anyone know if one exists?

To remove these sessions manually, I'm going to query the mdl_events table for any event listed with a modulename of "attendance" and remove them. Once I did this, the issue went away for me, but I wanted to report this here in case it was useful.

**Comment by danmarsden** [comment]
you mention "When unchecking the default to add events to the Calendar," - are you just changing the "default" value for new events or are you actually disabling the calendar events completely? - (those are 2 separate settings...)

**Comment by tallthom** [comment]
We disabled it in the plugin settings. We didn't want it to make those events in the first place, but must have missed the upgrade message telling us it would be done. So we disabled it in the plugin settings and then tried to remove the events from our calendar completely.

**Comment by danmarsden** [comment]
I vaguely remember a bug that occurred where calendar events were created but the link between the session and the calendar event was lost - the reset calendar function will only delete events that are "linked" to sessions via the caleventid field - you might just have to manually clean up the old events in the db sorry! - let me know if you work out anything else!

**Comment by tallthom** [comment]
I was able to remove the events. No worries. If you find anyone else having the issue, maybe this would help them resolve it.
