### ISSUE TITLE
No calender events are created after csv import

### ISSUE THREAD

**Issue by thomasdumm** [danmarsden/moodle-mod_attendance#349]
I was able to successfully import an attendance.csv with following record as admin:

course;groups;sessiondate;from;to;description;repeaton;repeatevery;repeatuntil;studentscanmark;passwordgrp;randompassword;subnet;automark;autoassignstatus;absenteereport;preventsharedip;preventsharediptime;calendarevent;includeqrcode
1044577;TLN;2018-12-11;17:00;19:00;Rechnungswesen 3;0;0;0;0;0;0;0;0;0;0;0;0;1;0

afterwards I checked in the mysql db the record that got created and noticed that the value caleventid=0 and calendarevent=0

Also a student enrolled in the affected course idnumber = 1044577 does not see a entry in the calendar

I checked that in the attendance plugin settings I selected the parameters enablecalendar, calendarevent_default

Systeminfo: I am testing on localhost and with German language with Moodle 3.5.2+ (Build: 20181031)

Any idea what might go wrong or what I am doing wrong?

**Comment by danmarsden** [comment]
Thanks for the report - sounds like a bug. Feel free to help us work on a fix!

**Comment by maksudr** [comment]
Hi @danmarsden, 

I investigated this issue and found that the logic to add the calendar event was missing. I have fixed it in this PR #377. 

Cheers!
