### ISSUE TITLE
Description is not changed in the calendar when editing a session

### ISSUE THREAD

**Issue by bendec** [danmarsden/moodle-mod_attendance#350]
We have an issue with the attendance plugin. When a session is created it appears in the calendar of the students. If we then edit the session and change the description, the event in the calendar is not updated with the new description. Only when a students clicks on 'Go to activity' then the correct description is shown. 
We are using Moodle 3.4 with version  3.4.4 (2017112006) of the plugin.

**Comment by danmarsden** [comment]
thanks for the report - sounds like a bug - feel free help us work on a fix.

**Comment by bendec** [comment]
Closed by accident. Sorry. I will ask our programmer to have a look at it and let you know if we find anything;.
