### ISSUE TITLE
The session date is prior to the course start date / Hidden sessions

### ISSUE THREAD

**Issue by Rabecerra** [danmarsden/moodle-mod_attendance#354]
Activity is generating an error message when a session is created on the course start date of a course. 

> The session date is prior to the course start date (dd/mm/yyyy) so that the new sessions scheduled before this date will be hidden (not accessible). You can change the course start date at any time (see course settings) in order to have access to earlier sessions.
Please change the session date or just click the "Add session" button again to confirm?

This is happening even when the session is created in the same course start date but after the course start time.

**Comment by danmarsden** [comment]
can you please provide screenshots of the time set as the course start time, and a screenshot of the session start time so we can look at this further?

also - which Moodle version are you using and which version of the attendance plugin do you have installed?

**Comment by Rabecerra** [comment]
Hi Dan, thanks for the quick response.

The course I'm testing has a start date for Dec 24 14:00, 

<img width="1364" alt="course date" src="https://user-images.githubusercontent.com/15114801/49946069-2ef64b80-febc-11e8-8c7c-63cedaaad266.png">

I'm creating a session for Dec 24 for 6:00 AM to 8:00 AM and the message is appearing as expected.

<img width="1462" alt="message new session previous time" src="https://user-images.githubusercontent.com/15114801/49946042-230a8980-febc-11e8-8a7d-c83575a08f40.png">

When creating a session in the same course start date (Dec 24), but for a later hour (19:00 - 20:00), the message is also being displayed.

<img width="1306" alt="message new session later time" src="https://user-images.githubusercontent.com/15114801/49946311-bcd23680-febc-11e8-9904-60aae34b1371.png">

As far as I can see, the unixtime for previoussessiondate in both cases is being set at 5:00 Am so the validation is throwing that message.

I'm using Moodle 3.5 and 2018051407 version of mod_attendance I just checked that it exists a new version of it but for 3.6.

Thanks again for your help.

**Comment by danmarsden** [comment]
That sounds like expected behaviour to me - you mention that the course start date is  Dec 24 14:00 (2pm)
but your session is before the course start - 5am/6am same day - so the warning is valid. You can just hit the "save" button again and it will create the session even though it is before your course start date.

**Comment by Rabecerra** [comment]
Ok, I understand that, but the second session created was for (19:00 - 20:00) a later hour of the day, way later than the course start (14:00), I know that doesn't have an impact over the functionality since you can create the session hitting the save button again, is just I think is an odd behavior.

Thanks again.

**Comment by danmarsden** [comment]
thanks - I'll try to add the "time" in use to the error message instead of just the date to see if that helps to diagnose why that is happening.

**Comment by danmarsden** [comment]
Just took another look at this and saw some issues with the logic there - I've just pushed a fix into the master branch here that should tidy that up! - thanks for the report.
