### ISSUE TITLE
Improvement: Use QR code icon for the QR code feature instead of the key icon

### ISSUE THREAD

**Issue by Kathrin84** [danmarsden/moodle-mod_attendance#357]
Hi Dan,

when you introduced the QR code functionality in your plugin, I had problems to find the QR code when using the feature.
I was searching for some icon that indicated to me that I could find the QR code there. It took me quite some time to press the key icon in order to find the QR code behind it:
![session](https://user-images.githubusercontent.com/4711883/50333936-0d721100-0507-11e9-8248-870e68a74941.png)
 
So my proposal is to use a QR code icon (e.g. https://fontawesome.com/icons/qrcode?style=solid&from=io) instead to make it more obvious for the user what he will find behind the icon.

Best, Kathrin

**Comment by danmarsden** [comment]
Thanks for the feedback - I'll keep it in mind when making further improvements!

**Comment by MonilBhavsar** [comment]
I can resolve this, where can I find the HTML Template for this pages ?

**Comment by danmarsden** [comment]
@MonilBhavsar - we're looking for GSOC students with initiative and the ability to research a problem themselves. If you aren't able to resolve this particular issue on your own it might be better to start with something else.

**Comment by maksudr** [comment]
Hi @Kathrin84 @danmarsden,

I think this is a great idea and actually ran into the same difficulty. I have implemented this in the PR above. Let me know your thoughts.

Cheers!

**Comment by danmarsden** [comment]
thanks @maksudr. I'll take a look at the pull request this week!
