### ISSUE TITLE
Upgrade error attendance_warning_done->notifyid_userid does not exist

### ISSUE THREAD

**Issue by lloydie-t** [danmarsden/moodle-mod_attendance#358]
Upgrade from version 3.2.4 to 3.5.5 on Moodle 3.5.3+ (Build: 20181220) produces the following error:
`mod attendance Index attendance_warning_done->notifyid_userid does not exist. Drop skipped`

Applying the following MySql query seems to resolve the issue and doing the upgrade again fixes the issue.
`CREATE INDEX notifyid_userid ON `moodle`.`mdl_attendance_warning_done`(notifyid, userid);`

Maybe the upgrade script can take the differig DB schema into account before dropping the index.

**Comment by danmarsden** [comment]
Thanks for the report - looks like a missing index_exists check there which I've added to the affected branches now.
