### ISSUE TITLE
Improve usability of "Save attendance" to make it clear it will load the next list of users.

### ISSUE THREAD

**Issue by derrynj** [danmarsden/moodle-mod_attendance#360]
Moodle 3.6.1+ (Build: 20181214)
Attendance plugin version: 3.6.3 (2018102600)

When taking attendance for a session, the totals at the bottom of the table do not update when you click 'Save attendance'. They only seem to update when you navigate away and then back to the same page.

**Comment by danmarsden** [comment]
Hi Derrynj - I've just had a look, and it seems to work ok for me. The totals at the bottom of the page are for the current page - what isn't always clear though, is hitting the "Save attendance" will take you to the next page of users and it will show you the totals for the "new page"

Can you please verify this and let me know?

thanks,

**Comment by derrynj** [comment]
Hi Dan,
That's exactly what's happening. It took me a few goes to figure out exactly what you were saying but yes that's what I'm seeing.
Is it possible to have some sort of indication there pointing out to the user that the totals are only applicable to the current page?
It's also extremely confusing behavior that it automatically pushes you onto the next page - especially if you only marked a few students attendance.
Cheers,
Derryn

**Comment by danmarsden** [comment]
yeah - this is behaviour that's been there since I took over the plugin, and I agree it's not very clear. There are a few things we can do to improve this - probably change the "save attendance" button text to something like "save and show next page" and tidy up the headers around the totals at the bottom makes sense too. I'll leave this open and try to get to that the next time I'm working on this.

**Comment by abhimanyuZ** [comment]
Hello Sir,
I was planning to work on this.
I'll edit the button text as "Save and Next". Also i'll add the heading "Totals for listed users:" before the totals at the bottom.

But here is a query:
> tidy up the headers around the totals
You meant?

Thanks

**Comment by danmarsden** [comment]
Hi there - I meant change the heading above the totals at the bottom like you suggest - I would probably go for a string like "Totals for this page" - instead of "Totals for listed users.

thanks!
