### ISSUE TITLE
Allow student to enter comments during marking of attendance

### ISSUE THREAD

**Issue by anapresa** [danmarsden/moodle-mod_attendance#361]
Hello,
I propose that when the student marks his own attendance, there is a field to put the observations.
Greetings and thanks for the great plugin.

**Comment by danmarsden** [comment]
Hi @anapresa - this has been requested before and is very similar to part of Issue #300 - there has also been a few people asking if the attendance can use 2 different status sets - one to mark attendance, and another status set for other feedback. 
There is quite a bit of work involved in doing this so it's not something I plan to do in my volunteer time.

If someone wants to fund my time to complete this work please get in touch privately.

I'm closing this as it is
