### ISSUE TITLE
API or web service Request 

### ISSUE THREAD

**Issue by TobiSam4** [danmarsden/moodle-mod_attendance#362]
Hi Dan,
I am working on a project whereby i am integrating RFID to moodle attendance system and i am to integrate them using either an API or web service but i cant seems to find any documentation to integrate to the moodle attendance system can you kindly assist me with the documentation or with code that can help with the integration process.

**Comment by danmarsden** [comment]
Hi @TobiSam4,

there are some webservices in the attendance code that might be able to do this but you may find they don't return all the information you need. 
Feel free to submit a pull request to improve/add-to the web services already provided, or get in touch privately if you would like commercial level support or if you would like to fund improvements.

thanks!
