### ISSUE TITLE
Upgrade failed due to Oracle syntax errors

### ISSUE THREAD

**Issue by beichapman** [danmarsden/moodle-mod_attendance#363]
I tried to upgrade the mod attendance in my 3.6.2 Moodle system from 3.1.1.2 (2016052204) to 3.6.3 (2018102600), and ran into some DB errors. We are the Oracle shop. There is a tiny syntax error in ../db/upgrade.php that Oracle is not happy about it, and my upgrade process failed. See the line with a fix below.

//Old line
389 $table->add_key('level_id', XMLDB_KEY_UNIQUE, array('idnumber, warningpercent, warnafter'));
//New line
//Need to wrap each field name with single quote
389 $table->add_key('level_id', XMLDB_KEY_UNIQUE, array('idnumber', 'warningpercent', 'warnafter'));

If this issue can be checked and addressed in your plugin code, that would be great.

Thanks,
Bei Chapman

**Comment by danmarsden** [comment]
thanks for the report - looks like an obvious bug there! - I've just patched that in all affected branches here in github.
