### ISSUE TITLE
when studentscanmark is disabled, automatic marking is still available but doesn't work.

### ISSUE THREAD

**Issue by danmarsden** [danmarsden/moodle-mod_attendance#365]
when studentscanmark is disabled, the session editing screen allows the teacher to select automatic marking, but the status set config page hides the "available to students" field so automatica marking cannot work.

we need to look at either hiding the automatic marking options, or showing the available to students field even when studentscanmark is off.

**Comment by gormster** [comment]
Alternatively: automatic marking should work even when studentscanmark is off… our use case is entirely webservice based, meaning that you often end up with partially complete attendance sheets. Currently we advise instructors to mark every student as absent before starting a class, but that's not an ideal solution for obvious reasons. Automatic marking seemed like a great answer for us… except that it doesn't work when self-marking is disabled.

I can't really see any reason why this would be the case - the aspect of automatic marking we really need is a default status that's automatically set for every student for whom no response has been marked, and that doesn't depend on self-marking at all.

What are your thoughts on this? If `update_user_status` had an option to specify an "automatic" status - that is, the status that would be applied if the student were marking themselves - then more-or-less all of automatic marking could be achieved through web services, from a device with no inputs (like our card readers).

**Comment by danmarsden** [comment]
I think the issue is mainly with the status set settings ui which simplifies when can mark is disabled. I suspect we just need to always show all options on that ui even if can mark is disabled. There may also he some ui/ux improvements to make the settings more clear.

**Comment by danmarsden** [comment]
We'll also need to improve the session add/update forms so that automatic marking can be set independently of the student marking. I'll see if I can get to that this week.

**Comment by lszeremeta** [comment]
Hi,
I have two suggestions:

**_There should be option to disable student marking but enable automatic marking only._**
Now you need to check "Allow students to record own attendance" for automatic marking.

**_Will be nice if automarking will check last student activity in the course/site within time frame defined in session settings, not just only log in history._**
For now, if student will log in before session start and keep log in there, auto marking will not mark this student.

**Comment by gormster** [comment]
I'm going to work on the idea of adding as much automatic marking as possible to non-student marking. Here's my roadmap:

- [ ] Get task\auto_mark to mark every student not manually marked by the end of the session with the default value
- [ ] Fix UI so that automatic marking can be enabled and disabled separately to student self-marking
- [ ] Allow callers of `attendance_webservices_handler::update_user_status` to pass -1 to `$statusid` meaning "set the status automatically" - i.e. what would have been set if the student marked themselves (presumably the result of `attendance_session_get_highest_status`)

Anything else anyone can think of?

**Comment by danmarsden** [comment]
Thansk @gormster, not quite clear what you mean by the first point? -that sounds like existing behaviour. 
The most difficult bit(not really difficult) is going to be getting the UI right when a teacher is modifying the settings. At the moment when studentscanmark is off it hides all the various related settings (which I like.)

I suspect we'll have to replace the existing "studentscanmark" checkbox with a select with the options:
Disabled
Auto marking only
Student can mark and automarking

The reason we'll need to use a select is that the hideif functions won't easily work with multiple checkboxes. 

I was hoping to get some time to tidy this up myself, but a pull request would be great!

**Comment by danmarsden** [comment]
@gormster - I've just knocked together a patch that should fix this but I haven't done much testing on it yet. Let me know if you get a chance to test it see pull request #385

**Comment by preney** [comment]
The last post to this issue was Jun 5, 2019. I am experiencing issues with automarking. Will this bug's fix be in this repo? Or will I have to switch to jonathanchan2's code (if that works) instead of the main repository? Thanks.

**Comment by danmarsden** [comment]
@preney the bug described here was fixed in the main branch in 2019 as part of #385 - if you are using the latest version of the attendance code and are experiencing a similar issue, please create a new tracker issue with details on the moodle version, version of attendance and information on the issue you are having.

thanks!
