### ISSUE TITLE
 Installation instructions

### ISSUE THREAD

**Issue by luisdev** [danmarsden/moodle-mod_attendance#366]
Please add installation instructions to the README.md file.

For manual installations where do you put the \attendance folder? In \moodle\mod\ ?

**Comment by danmarsden** [comment]
Please see Moodledocs for information on installing plugins:
https://docs.moodle.org/en/Installing_plugins

If you want to install plugins manually without using the moodle plugins db installers or the upload zip tool within your moodle site, you will need to have some prior knowledge on the types of plugins in moodle (local/mod/admintool/block) - usually the plugin repository name will give you a clue "mod_attendance" but this is also stored within the version.php file inside all plugins.

I don't have plans to include manual installation information in the readme at this stage.
