### ISSUE TITLE
Having HTML in session description causes webservice to error out

### ISSUE THREAD

**Issue by gormster** [danmarsden/moodle-mod_attendance#370]
Because `description` is declared in `get_session_structure` as `PARAM_TEXT` (rather than `PARAM_RAW`) any HTML in the description causes `validate_param` to throw an `invalid_parameter_exception`.

There are two fairly simple fixes: use `clean_param` on the description before returning it from the webservice handler, or change `description` to `PARAM_RAW`. The former ensures that any app can render the description, even if it can't render or parse HTML, but also means apps that can (like the Moodle official app) won't display it correctly if it contains formatting. The latter puts the responsibility for cleaning or rendering the HTML on the web service client, but is probably the most technically correct.

Either way, we need to make a decision. I'm inclined to say switch it to PARAM_RAW - after all, that's how the built-in modules do it (e.g. mod_assign).

**Comment by danmarsden** [comment]
+1 to do it the same way as core. We control the mobile app a bit in the attendance code, so if we need to adjust code there to make it display better that's cool too.

**Comment by danmarsden** [comment]
this was fixed in #589
