### ISSUE TITLE
Error writing database

### ISSUE THREAD

**Issue by imatotek** [danmarsden/moodle-mod_attendance#371]
Hi!

When adding Status set, I have filled column Acronym, Description and click Add but then I have received "Error writing to database". 
![error](https://user-images.githubusercontent.com/1871271/53489243-ff091e00-3a90-11e9-8aef-415690cf3287.jpg)

**Comment by danmarsden** [comment]
What version of Moodle are you using, and do you have the latest version of the attendance plugin for your site?

**Comment by imatotek** [comment]
Hi!

Moodle version is Moodle 3.6.2+ (Build: 20190215), Attendance version is 3.6.5, 2019022500.

Ivica

**Comment by danmarsden** [comment]
thanks - I can reproduce that too, although I'm probably just going to replace that with an error to say that you need to enter something into the grade field....

**Comment by danmarsden** [comment]
ended up pushing a patch to force it to 0 if not set by the teacher. Thanks.
