### ISSUE TITLE
Feature Request: Display user's attendance in percentage on report page

### ISSUE THREAD

**Issue by nadavkav** [danmarsden/moodle-mod_attendance#38]
This feature request is actually a regression relative to Moodle 1.9 version of this module.
![image](https://cloud.githubusercontent.com/assets/231168/3122154/f91bd7f6-e763-11e3-87f2-d32a542df617.png)

Please see if you can add this column to the user attendance report.

**Comment by danmarsden** [comment]
this has been completed as part of the work Antonio just completed - thanks Antonio!
