### ISSUE TITLE
Allow option to hide email addresses from register

### ISSUE THREAD

**Issue by kbowlerarden** [danmarsden/moodle-mod_attendance#386]
We would like to be able to hide student's email addresses from the register.  Perhaps there could be a setting added that when ticked would hide the email column.

Another option would be to integrate with the mdl_user's maildisplay setting.  If they have marked their maildisplay as "Hide my email address from everyone", we could blank out their email address in the register.

This would aid the data minimisation principle of GDPR by ensuring that only the information that is required to complete the task is visible on that page.

If the idea makes sense, I would happily submit a pull request with the feature in it.

**Comment by danmarsden** [comment]
Attendance uses the site wide showuseridentity setting for this and I'm not convinced that we need an attendance specific setting for this. If you are concerned about exposing the email address for gdpr purposes you should be disabling it in the site level showuseridentity setting.

**Comment by kbowlerarden** [comment]
Great, thank you! I will look into the showuseridentity setting. Thank you for your help and for such a great plugin!

Kevin.

**Comment by danmarsden** [comment]
no worries - I'm closing this for now, but if you still really think we need an attendance specific setting for this rather than the site level showuseridentity setting feel free to try and twist my arm.... :-)
