### ISSUE TITLE
issue with new Classic theme and report list

### ISSUE THREAD

**Issue by danmarsden** [danmarsden/moodle-mod_attendance#389]
The list of user names sits behind the blocks instead of within the report page when using the new core classic theme.

**Comment by Joni-Tuomi** [comment]
I was able to fix this issue using following custom CSS:

#page-mod-attendance-report .attendancereporttable .headcol {
	position: inherit;
}

#page-mod-attendance-report .attendancereporttable, #page-mod-attendance-report.has-region-side-pre .attendancereporttable  {
	margin-left: 0px;
}

**Comment by danmarsden** [comment]
thanks for the suggested fix!

**Comment by danmarsden** [comment]
pretty sure this is resolved with the latest changes, but any further issues please report with screenshots - thanks! :-)
