### ISSUE TITLE
Web service test having random failures.

### ISSUE THREAD

**Issue by jgg9026** [danmarsden/moodle-mod_attendance#390]
The test called **test_get_session_with_group** has a random failure, see the following stack trace:

`attendance_webservices_tests::test_get_session_with_group
Failed asserting that two strings are equal.
— Expected
+++ Actual
@@ @@
-'524000'
+'0'`

`PHPUN/mod/attendance/tests/attendance_webservices_test.php:174`

Plugin version: 2019022500

**Comment by danmarsden** [comment]
Yeah - I've seen those in our pipelines too - haven't looked closer at it though - feel free to help us work on this and submit a pull request - thanks!
