### ISSUE TITLE
Acronym translation

### ISSUE THREAD

**Issue by izendegi** [danmarsden/moodle-mod_attendance#394]
I've recently installed the plugin and it has thrown an error in the process; looking at the reason I've discovered that the issue was a INSERT error on {attendance_statuses} because in AMOS the translation of an acronym had more than 2 characters.

I don't really know what should be the best fix for this issue, as long as there is no way to restrict the length of strings in AMOS (AFAIK). I don't know if there is a way of checking it and defaulting the acronym to the one in English or something like that.

**Comment by danmarsden** [comment]
Thanks for the report - Does the translation look incorrect? - eg does it contain a full word?

I can add a check to make sure it's not bigger than 2 chars, but if there's a good reason to increase the acronym field size I could look at that instead.

**Comment by izendegi** [comment]
I did the translation to Basque myself with full words, and did it that way because two of the words are similar ("Present" --> "**Ber**taratua" and "Late" --> "**Ber**andu"), and also didn't know about the restriction of characters.

Now that I know about that restriction I found a synonym for one of them and trimmed them, but I don't know if the acronym can be confusing for some users...

**Comment by danmarsden** [comment]
Thanks - I'm learning towards closing this as won't fix. The Acronym is designed to be a very short representation of the actual status and is used when marking attendance for large numbers of users - The English lang pack uses a single character for all values, but we do support up to 2 chars. If we allowed the same value in the acronym and the fullname of the value it would display strangely (in some areas it would look like the value was just repeated), and the design of some areas relies on a very short acronym value. Increasing the allowed size of this value would result in a bit more work. 

Of course - I'm happy to receive a pull request to improve this further, but I think in this case - using the fullname in the acronym field is an incorrect translation.

I think I'd prefer it broke (like you found) than quietly replacing the strings with the english lang versions and making users think that the strings weren't translated.

**Comment by izendegi** [comment]
I'm OK with closing this (I've already fixed the Basque version of the acronyms in AMOS), I opened it to make you aware of the vulnerability. 

I can suggest some workarounds on the plugin, but the best fix to this may be a new feature in AMOS to restrict the string length or warn the translator about it in some way, you may suggest that feature in the [AMOS forums](https://lang.moodle.org/mod/forum/view.php?id=5) or directly create a issue [in the tracker](https://tracker.moodle.org/browse/MDLSITE-5849?jql=project%20%3D%20MDLSITE%20AND%20component%20%3D%20lang.moodle.org)...

**Comment by danmarsden** [comment]
thanks - closing this as won't fix for now, but I'm happy for someone to submit a sensible pull request for consideration.

thanks,

**Comment by danmarsden** [comment]
re-opening this as it's come up in the comments on the plugins db - as mentioned above, the Acronym is designed to be a very short representation of the actual status and is used when marking attendance for large numbers of users - The English lang pack uses a single character for all values, but we do support up to 2 chars.

I would like to hear from people that are experiencing this with their language packs, to find out if there is a valid reason why we should accept more than 2 chars, or if we just need to ask for fixes to be submitted to the lang pack on lang.moodle.org.

I have just pushed through a patch to github that prevents the fatal db error on install if using more than 2 chars - it falls-back to using the English version of the acronym on install.

**Comment by danmarsden** [comment]
closing as no-one gave further feedback and I added code to prevent the fatal error when the acronym is larger than 2 chars.

**Comment by twhiteimc** [comment]
Hi Dan, we have Moodle Workplace, 3.10 as of this week.  As we have a Moodle Workplace vendor, I've asked them to upload your attendance plugin before the upgrade from 3.9.  For some reason, I'm not seeing the csv enroll feature.  I am reaching out to the vendor, though would like to ask if there's anything else that I need to tweak.  If you have any questions, please let me know.  Thanks for your help.
![csv_bulk_enroll_featuremiss](https://user-images.githubusercontent.com/77847835/105512025-777cb780-5c85-11eb-96fd-eeb4ea40e024.jpg)

**Comment by danmarsden** [comment]
I haven't tested it on workplace - feel free to get in touch privately if you want to fund any work to test/improve it for workplace.
but also make sure you have the most up to date attendance plugin - you should be able to see what version is currently installed in the admin > plugins pages.

**Comment by demontech** [comment]
Hi Dan,

We're in a need to add a status for Leave of Absence (LOA) that will make more than the limit of 2 characters. Is there a way to increase the acronym to 3 characters?

Thanks!

**Comment by danmarsden** [comment]
not at this stage - please create a new issue and explain the requirement.
we'll need to increase the field size in the db level and update the UI to suit.

If we touch the size of these fields, we should also consider #645 at the same time.
