### ISSUE TITLE
Hide ID number on session attendance marking page

### ISSUE THREAD

**Issue by ecampbell** [danmarsden/moodle-mod_attendance#399]
When a teacher opens the session attendance marking page, student names and ID numbers are displayed. In our EU-based college which is subject to GDPR, lecturers who use a PC in a class have only a single monitor, and everything they do is visible to students on the main projector screen. The ID number is personal data so students shouldn't see other students ID numbers. In most cases, the ID number isn't necessary to identify students anyway, except if two students have the same name. 

So my request is to control the display of the ID number column in a setting. I think 3 options should be available.
1. Display the ID number column
2. Hide the ID number column
3. Obscure the ID number with a configurable mask, such as "*******N", so that an ID number of 12345678 would appear as *******8

**Comment by danmarsden** [comment]
I'm reluctant to add a specific attendance setting for this because it already uses the moodle setting show user identity, and if gdpr is the reason... surely show user identity should not be configured to include the idnumber in the first place?

**Comment by ecampbell** [comment]
The lecturers do still need to see the ID number in other contexts such as grading, so setting the site configuration to hide it everywhere isn't feasible.
However, I came up with a reasonable work-around, which will work on themes that allow the default CSS style to be overridden (e.g. Essential, Adaptable). I blurred the ID number column in the table using the following CSS directive:
/* Hide ID Number on Attendance Session attendance-taking page */
#attendancetakeform * .c2 { filter: blur(3px);}

**Comment by danmarsden** [comment]
Thanks - I'm closing this as won't fix as we already have a setting to control this in the show user identity settings, and if the idnumber is an issue for GDPR purposes it should really be turned off there.

Hopefully the reportbuilder stuff in Moodle for workplace will end up in the core release at some point - it has some nice methods of customising which columns appear in reports like this. 

I could have my arm twisted slightly if someone added a pull request for this, but it's not something I really think is needed - especially as there are workarounds available like using css as you have found.
