### ISSUE TITLE
Feature Request: Add User's name as a tooltip to each cell in the report table

### ISSUE THREAD

**Issue by nadavkav** [danmarsden/moodle-mod_attendance#40]
This could help when we have a very long table where it is difficult to know which line is referred to which student (since we scrolled to the left and the student's name is not visible anymore)

Somthing similar to the way Course Grades table is behaving.

**Comment by danmarsden** [comment]
I'm closing this one as "won't fix" as we now float the users name so you can now better see which user a row is associated with - let me know if you think we still need to do something like this though and we can re-open.
