### ISSUE TITLE
Attendance module shows no users 

### ISSUE THREAD

**Issue by marcmathys** [danmarsden/moodle-mod_attendance#402]
Although there are users/groups in the course and it was working before upgrade to 3.7.  The history is still reflected in the grading system.

**Comment by danmarsden** [comment]
Hi there - there isn't enough information here to consider this as a bug, and the best place to ask for "support/help" is in the community forums so I'm closing this.

I have heard of this happening in sites that use custom roles or have modified the core roles - make sure your student role stil has the "canbelisted" attendance capability. If you are still having issues, please create a new post in the attendance forum on moodle.org and make sure you provide a lot more information than you have here. thanks!
