### ISSUE TITLE
Support phpqrcode in addtion to Google Chart API

### ISSUE THREAD

**Issue by fishfree** [danmarsden/moodle-mod_attendance#403]
In China or an intranet enviroment, Google Chart API cannot be accessed. So, please also support http://phpqrcode.sourceforge.net/

**Comment by danmarsden** [comment]
I'm confused. What makes you think we are using Google chart api? Existing code uses the built in tcpdf lib to generate qr codes and does not rely on an external service.

**Comment by fishfree** [comment]
Sorry, I mistook. That's great to use built-in tcpdf!
