### ISSUE TITLE
Too easy to accidentally override existing marks with 'set status for all users' radiobutton.

### ISSUE THREAD

**Issue by nwp90** [danmarsden/moodle-mod_attendance#405]
We've found the "set status for all users" radiobuttons to be both essential and infuriating. It is normal for some students' statuses to be set to a state that indicates a "excused absence" in advance of a session, which means the "set status for all users" cannot be used to mark all those who are expected to be present as present at the time of the session.

We've implemented a fix so that the "set status for all users" will only set status for users whose status is not already set, unless shift-clicked, in which case it will set for all users and override existing statuses.

**Comment by danmarsden** [comment]
Hey Nick! - I like the "feature" but I'm not quite sure about the UX - it means that the user has to have prior knowledge and I can't think of any other interfaces that work this way in Moodle. This also doesn't work for mobile device usage or for the app.

I'm not quite sure what the solution is for that though - I'll have a think on it.

**Comment by nwp90** [comment]
Agree; don't have a good answer for that either. I'll update this with a similar fix for the grid layout once I've tested it (we never use grid)...

**Comment by danmarsden** [comment]
I've had a few ideas on how we might be able to provide this functionality but with a slightly better UX - @maksudr has some time at the moment so he is going to see if he can do something with this - we'll let you know how it goes!
