### ISSUE TITLE
key symbol to create QR codes is not visible when no password is set

### ISSUE THREAD

**Issue by webers-technikum-wien** [danmarsden/moodle-mod_attendance#407]
basically this: https://github.com/danmarsden/moodle-mod_attendance/issues/378

but from what i can see this issue was closed without opening a corresponding bug report that it actually does not work without setting a password

if no password is set, the key icon is not displayed

**Comment by danmarsden** [comment]
Pinging @maksudr here - does this sound familiar? - did we forget to check that the QR code could actually be accessed when no password is set?

**Comment by maksudr** [comment]
@webers-technikum-wien is this on the latest version of the plugin? I have created an attendance session with no password and "Include QR code" enabled and the QR code icon appears.

**Comment by webers-technikum-wien** [comment]
sorry, my bad, should have included version in this issue, i am indeed not on the latest version, but on 2019022500. will upgrade to latest and close this.
