### ISSUE TITLE
Attendance pageparams not initialised safely/sensibly

### ISSUE THREAD

**Issue by mhughes2k** [danmarsden/moodle-mod_attendance#41]
The current constructor for the attendance object is:

    public function __construct(stdclass $dbrecord, stdclass $cm, stdclass $course, stdclass $context=null, $pageparams=null) {

This defaults the $pageparams to null.

If I instantiate this without a $pageparams object I then start getting lots of notices as the code starts trying to access various properties & methods like startdate, enddate and get_current_sesstype().

For example the get_filtered_session() function is just doing:

    if ($this->pageparams->startdate && $this->pageparams->enddate)  {

which raises notices because the object that is meant to hold the startdate / enddate property is null.

If this is required or going to be expected to be available then it shouldn't have a default and /or should be initialised to something sensible!

I've got the case where I've got a web service that doesn't have UI and I want *all* the data so I've not passed any pageparams in.

(I was in the process of updating it as a contribution to this module as we've implemented access to attendance data via a web service call, when I found this)

**Comment by danmarsden** [comment]
@mhughes2k did you ever get round to fixing this one?
