### ISSUE TITLE
viewing attendance report for individual user does not generate a log entry

### ISSUE THREAD

**Issue by nwp90** [danmarsden/moodle-mod_attendance#411]
Viewing attendance report for individual user does not generate a log entry. I was looking to add an appropriate entry to the log when editing user attendance data from a user attendance report (working on PR#404), when I realised that merely viewing those per-user reports wasn't generating a log event either...

**Comment by nwp90** [comment]
@danmarsden - happy to deal with this if you let me know whether you have any specific requests/concerns re implementation, then I can also derive something from the "viewed" event to use for "updated".

**Comment by danmarsden** [comment]
go for it - sounds pretty straight forward adding a new event - thanks! :-)
