### ISSUE TITLE
log entry for report viewed generates incorrect URL

### ISSUE THREAD

**Issue by nwp90** [danmarsden/moodle-mod_attendance#412]
Log entries for "report viewed" events generate an incorrect URL, as the attendance instance id is passed to \mod_attendance\event\report_viewed::create as objectid, but report.php expects id to be a cmid.

I think report_viewed.php's get_url just needs to use this->contextinstanceid instead of this->id to generate the url. But *all existing* report_viewed log entries should probably be fixed too.

**Comment by danmarsden** [comment]
just fix it without changing the historical logs... making update calls on the logs tables makes me very nervous with the number of possible records that could be affected, and the fact that no-one has noticed this until now...

**Comment by nwp90** [comment]
OK, happy to do that. Wasn't so keen if all the updating was going to happen ;)

**Comment by danmarsden** [comment]
fixed in #413 - thanks!
