### ISSUE TITLE
Confusing UI: Show more... link in Add session tab > Student recording

### ISSUE THREAD

**Issue by mwithheld** [danmarsden/moodle-mod_attendance#420]
At URL /mod/attendance/sessions.php?id=1170100&action=1
In the "Add session" tab under the "Student recording" section
there is a "Show more..." link that appears to do nothing
*unless* you check "Allow students to record own attendance" first.

This will confuse some instructors.
Can you please hide the "Show more..." link unless the "Allow students to record own attendance" box is checked?

**Comment by mwithheld** [comment]
![Attendance-AddSession-ShowMore](https://user-images.githubusercontent.com/796986/62981237-96fb8980-bddd-11e9-8b9f-1071f8c07520.png)

**Comment by danmarsden** [comment]
thanks for the report - I suspect that's a problem with the core forms api and there might not be much we can do about it within the attendance code (we might need to fix this in moodle core.)

in any case - feel free to help us work on this - pull requests and or funding for improvements are always welcome!

**Comment by mwithheld** [comment]
Hm yeah that does look tricky.  I had a quick try at it based on
lib\formslib.php::addAdvancedStatusElement() logic and it's no good - I suspect there's no JS logic to pick it up.

```
            $mform->addElement('hidden', 'mform_showmore_' . 'subnetgrp');
            $mform->setType('mform_showmore_' . 'subnetgrp', PARAM_INT);
            $mform->setConstant('mform_showmore_' . 'subnetgrp', true); //also tried false
            
            $mform->addElement('hidden', 'mform_showmore_' . 'preventsharedgroup');
            $mform->setType('mform_showmore_' . 'preventsharedgroup', PARAM_INT);
            $mform->setConstant('mform_showmore_' . 'preventsharedgroup', true); //also tried false
```

**Comment by danmarsden** [comment]
closing as not much we can do about this in attendance - thanks!
