### ISSUE TITLE
Default exception handler: Exception - Call to undefined function Moodle 3.6.5

### ISSUE THREAD

**Issue by btaylorcsusm** [danmarsden/moodle-mod_attendance#421]
Hi everyone,

We just started getting this error today on 3.6.5 Thoughts on what needs to be done to resolve the issue?

Default exception handler: Exception - Call to undefined function file_rewrite_pluginfile_urls() Debug:
Error code: generalexceptionmessage
* line 972 of /mod/attendance/classes/structure.php: Error thrown
* line 944 of /mod/attendance/classes/structure.php: call to mod_attendance_structure->get_session_info()
* line 180 of /mod/attendance/classes/task/auto_mark.php: call to mod_attendance_structure->get_statuses()
* line 156 of /admin/tool/task/cli/schedule_task.php: call to mod_attendance\task\auto_mark->execute()

!!! Exception - Call to undefined function file_rewrite_pluginfile_urls() !!!

Thanks,
Barbara

**Comment by danmarsden** [comment]
interesting that it's only just started happening...
try adding:
require_once($CFG->libdir .'/filelib.php');

to the top of mod/attendance/classes/structure.php underneath the require for the calendar_helpers.php file.

**Comment by btaylorcsusm** [comment]
Hi Dan,

We tested this and it works. Will you be releasing an update addressing this issue? If so, do you know when?

Thanks,

Barbara

**Comment by danmarsden** [comment]
Thanks @btaylorcsusm, a fix for that has now landed in the github branches for supported versions here.

There will be a new release pushed to the moodle.org plugins db soon - probably in the next few weeks which will include this fix.
