### ISSUE TITLE
Attendance in Moodle App takes a long time to recover all the sessions

### ISSUE THREAD

**Issue by ColinBruneau** [danmarsden/moodle-mod_attendance#425]
We have 2450 sessions (14 groups) so it takes about a minute to display all the sessions even though we need only 1 session.
Would it be possible to load only today's sessions by default and have a button to display all sessions?

**Comment by danmarsden** [comment]
anything is possible! :-) Feel free to help us work on this.

Pull requests are always welcome. Alternatively feel free to get in touch privately if you want to fund the development time to make these improvements.

**Comment by ColinBruneau** [comment]
Hey Dan,
I did a little propsect about this bug and I found that the sessions listing were not limited in time, despite the comment saying it is... May I suggest a timeLimit variable and add it to the test...
/var/www/html/yourmoodle/mod/attendance/classes/output/mobile.php
line 130
        // Get list of sessions within the next 24hrs and in last 6hrs.
        // TODO: provide way of adjusting which sessions to show in app.
        $time = time() - (6 * 60 * 60);

        // Colin Bruneau: add 24hr limit
        $timeLimit = time() + (24 * 60 * 60);

        $data['sessions'] = array();

        $sessions = $DB->get_records_select('attendance_sessions',
            'attendanceid = ? AND sessdate > ? AND sessdate < ? ORDER BY sessdate', array($attendance->id, $time, $timeLimit)); // Colin Bruneau; and test limit

**Comment by danmarsden** [comment]
Wow - yeah, that was definitely unintended! - thanks for tracking that down. I'll see if I can get a new setting in there so it can be controlled by the site admin.

**Comment by danmarsden** [comment]
I've just pushed a fix into the master branch here that adds a new admin level setting to allow this to be controlled - I haven't tested it on a real app though, so before I look at backporting this to older branches it would be good if someone got a chance to test it and verify that it works!

thanks!
