### ISSUE TITLE
Missing AND in SQL statement causes error

### ISSUE THREAD

**Issue by lexxkoto** [danmarsden/moodle-mod_attendance#427]
Line 461 of locallib.php:

`$sql = 'sessionid = ? AND studentid <> ? ipaddress = ?';`

The missing `AND` before `ipaddress` causes an 'error reading from database' exception if the "Prevent students sharing IP address" feature is enabled.

**Comment by danmarsden** [comment]
Thanks for the report - surprised that hadn't been picked up already! - I'll push a fix through today.
