### ISSUE TITLE
Error sql when use ipaddress filter

### ISSUE THREAD

**Issue by darioroig** [danmarsden/moodle-mod_attendance#428]
In file www/mod/attendance/locallib.php go to row 462 and add clause 'AND' to sql
// Assume ATTENDANCE_SHAREDIP_FORCED.
            //DRG add AND to sql
            $sql = 'sessionid = ? AND studentid <> ? AND ipaddress = ?';

**Comment by danmarsden** [comment]
this is a duplicate of #427 which has already been fixed in the git repository. thanks.

**Comment by syusanjun** [comment]
I am using Moodle 3.7.3.
Activities: Attendance is 3.7.1 (2019072402).
I can't save if I select yes or no in the Prevent students sharing IP address setting.
Is it necessary to enter the number of the ip address when selecting Yes or No?
