### ISSUE TITLE
PHP notices when looking at reports where some of the students have not been marked 

### ISSUE THREAD

**Issue by pavelsokolov** [danmarsden/moodle-mod_attendance#43]
If you haven't done any decision about attendance of some of your students (P/L/E/A), and they are still marked with red font in a session view, then PHP throws a notice on each unresolved student when looking at Reports tab.

 Notice: Undefined offset: 1 in /var/www/ilearn2test/mod/attendance/renderer.php on line 840

Can be fixed by just implementing some isset or empty check before trying to access potentially empty array indexes.

**Comment by danmarsden** [comment]
This may have been fixed already - let me know if you are still experiencing this (patches are always welcome too!) :-)

**Comment by danmarsden** [comment]
I can't reproduce this with the latest code, let me know if I've missed something
