### ISSUE TITLE
update_user_status webservice broken

### ISSUE THREAD

**Issue by danmarsden** [danmarsden/moodle-mod_attendance#430]
in #409 it was refactored slightly but now it looks broken.

missing global $DB and an undefined var $attforsession

**Comment by kabalin** [comment]
Ah, what a shame, this one is not test covered. I will send PR later today containing fix and the test (just spotted some more issues in the tests).

**Comment by danmarsden** [comment]
cool thanks!

**Comment by kabalin** [comment]
Created PR #431 to fix this. Thanks Dan!

**Comment by danmarsden** [comment]
thanks heaps! - backported some of it to the 3.7 stable branch - just excluded the test improvements due to the old ws names..
