### ISSUE TITLE
RTL user interface - The locations of the hour and minutes dropdowns are incorrectly reversed

### ISSUE THREAD

**Issue by acquaalta** [danmarsden/moodle-mod_attendance#432]
Hi,
Thank you for this wonderful plugin.

It seems that in an RTL (Right-to-left) environment, the timing UI is the exact opposite of the the one in the LTR environment. Please see attached a relevant screenshot.
![Attendence - Hours and Minutes - RTL vs LTR](https://user-images.githubusercontent.com/51836675/65372845-ee630400-dc7d-11e9-8406-ef5b466833e5.png)

Even in RTL environments, we still use the time format in the same way as in LTR environments - we read the time from left to right. Is it possible to swap the locations of the hour and minutes dropdowns in each relevant segment of the UI?

Thanks in advance :-)

**Comment by danmarsden** [comment]
thanks for the report, feel free to help us work on this issue.

**Comment by danmarsden** [comment]
thanks to @nadavkav a fix for this is now in the 3.5 and higher branches here on github.
