### ISSUE TITLE
Enhancement - alternative image source for user picture

### ISSUE THREAD

**Issue by 2shediac** [danmarsden/moodle-mod_attendance#433]
Hi - we have a customer that wants add a setting to be able to have an alternative source for user pictures. This is needed when the the user profile image is stored on an external web site and they do not want it included in the user profile information (where it would be publicly available)   but only in the attendance register where teachers can see it.

if I do the work would you be willing accept the pull request..

**Comment by danmarsden** [comment]
This feels like the wrong approach to me. It would be better to store user pictures like normal and then implement a core moodle capability to allow users to view the users picture. I'd expect that as soon as you have the pictures showing for teaching staff in the attendance, they'll start asking to see it in other locations as well.

If you have a custom theme on the site, you could probably override the user_picture renderer to check a capability too.

Good luck!
