### ISSUE TITLE
Where you get these attribute or document to develop Moodle Mobile Plugin?

### ISSUE THREAD

**Issue by datnguyenthang** [danmarsden/moodle-mod_attendance#438]
I saw these in your code:
`
return [
            'templates' => [
                [
                    'id' => 'main',
                    'html' => $OUTPUT->render_from_template('mod_attendance/mobile_teacher_form', $data),
                    'cache-view' => false
                ],
            ],
            'javascript' => '',
            'otherdata' => $otherdata
        ];`

Where you get attribute, such as 'cache-view' or document to develop Moodle Mobile Plugin.
I snoop in this link : https://docs.moodle.org/dev/Mobile_support_for_plugins
and i can't get doc to descript that.

**Comment by danmarsden** [comment]
best place to ask for this sort of support is in the moodle community forums on moodle.org - I'm not able to provide free support to help you write or understand custom code sorry! - good luck!
