### ISSUE TITLE
Time format is inconsistent in a Non-English environment

### ISSUE THREAD

**Issue by acquaalta** [danmarsden/moodle-mod_attendance#440]
Hi,
When using the "Attendance" plugin, and setting s time-frame for a session:
- full hours are shown in a 12h format
- non-full hours are shown in a 24h format

Please see the following screenshot:
![image](https://user-images.githubusercontent.com/51836675/67150646-e3be7d80-f2c2-11e9-8bf7-d06c71352dff.png)

Is it possible to make the hours to always be in a 24h format, a full hour or not?

Although I assumed that it can't be the source of the issues, to be on the safe side I checked the time format values in langconfig.php and everything seems to be alright there.
Then I found this closed issue:
https://github.com/danmarsden/moodle-mod_attendance/issues/113
I'm not sure, but it seems that according to it the langconfig.php values don't affect "Attendance". Please correct me if I understood it wrong.

In any case, is this possible to fix this inconsistency? I agree that it's far from being a major issues, but it seems odd and I hope that it's easy to fix it.

Thanks in advance.

**Comment by danmarsden** [comment]
That will be coming from the language pack from your defined language which is defined in Moodle's AMOS tool - all the English language versions seem consistent to me. 
If you want this to be fixed I suggest you submit an update to AMOS (https://lang.moodle.org/)

thanks,
