### ISSUE TITLE
Error causing cronjob to fail globally

### ISSUE THREAD

**Issue by rschrenk** [danmarsden/moodle-mod_attendance#441]
Hello,
we use the most current version of mod_attendance from moodle.org. Unfortunately the plugin breaks our cronjob. The error is as follows:

> Execute scheduled task: Auf Lerneinheiten überprüfen, die automatische Markierung voraussetzen (mod_attendance\task\auto_mark)
... started 10:34:14. Current memory use 17.4MB.
0 session status updated
Default exception handler: Fehler: Call to undefined function file_rewrite_pluginfile_urls() Debug: 
Error code: generalexceptionmessage
* line 966 of /mod/attendance/classes/structure.php: Error thrown
* line 938 of /mod/attendance/classes/structure.php: call to mod_attendance_structure->get_session_info()
* line 180 of /mod/attendance/classes/task/auto_mark.php: call to mod_attendance_structure->get_statuses()
* line 105 of /lib/cronlib.php: call to mod_attendance\task\auto_mark->execute()
* line 67 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 61 of /admin/cli/cron.php: call to cron_run()

!!! Fehler: Call to undefined function file_rewrite_pluginfile_urls() !!!
!! 
Error code: generalexceptionmessage !!
!! Stack trace: * line 966 of /mod/attendance/classes/structure.php: Error thrown
* line 938 of /mod/attendance/classes/structure.php: call to mod_attendance_structure-&gt;get_session_info()
* line 180 of /mod/attendance/classes/task/auto_mark.php: call to mod_attendance_structure-&gt;get_statuses()
* line 105 of /lib/cronlib.php: call to mod_attendance\task\auto_mark-&gt;execute()
* line 67 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 61 of /admin/cli/cron.php: call to cron_run()
 !!
PHP Fatal error:  Uncaught coding_exception: Fehler in der Kodierung gefunden, den nur ein Programmierer korrigieren kann: A lock was created but not released at:

Kind regards

**Comment by danmarsden** [comment]
This was fixed in issue #421 - the latest code is always here in github but I hope to update the plugins db sometime soon. Thanks.
