### ISSUE TITLE
Attendance warning email variable issues

### ISSUE THREAD

**Issue by cbrherms** [danmarsden/moodle-mod_attendance#442]
Hi,

We've been testing the warning emails this year with a couple of our courses and one thing that has been noticed is that in sent warning emails the `%percent%` variable is instead showing as a decimal, which causes confusion for students.

e.g
`Your attendance in %coursename% has dropped below %warningpercent% and is currently %percent% - we hope you are ok!`

send an email out as:
`Your attendance in AV3410: Professional Specialism has dropped below 60 and is currently 0.200000 - we hope you are ok!`

Additionally, with this set to 6 decimal places, if the variable is instead corrected to be a percentage then 2 decimal places would be the most necessary

**Comment by danmarsden** [comment]
Thanks for the report! - great to hear you are testing this, thanks for the feedback! -
 looks like this line here should be changed for this:
https://github.com/danmarsden/moodle-mod_attendance/blob/202be77f64dd0e0a9a5738f53059a7df576b994e/locallib.php#L888

feel free to help by submitting a pull request to tidy this up.

**Comment by cbrherms** [comment]
On our local instance I've initially instead tweaked the `attendance_template_variables` function for the user notify as there is still a bit of post processing on the third party email's.

https://github.com/cbrherms/moodle-mod_attendance/commit/e77069af3b7273cc61e4e1dca97487f3b0acb78e

Heading on vacation in a couple of hours but i'll put in a PR that's tidier than my current code duplication when i get back.

**Comment by evaleries** [comment]
> feel free to help by submitting a pull request to tidy this up.

Can I submit a PR for this?
My solution is to replace this line with `ROUND(SUM(stg.grade) / SUM(stm.maxgrade), 2) AS percent`
https://github.com/danmarsden/moodle-mod_attendance/blob/202be77f64dd0e0a9a5738f53059a7df576b994e/locallib.php#L888
