### ISSUE TITLE
REST API for importing sessions

### ISSUE THREAD

**Issue by anjolaat** [danmarsden/moodle-mod_attendance#444]
I would like to import the dates from study information system (includes course registrations) to Moodle courses so the teachers can just click the attendance status to the plugin. This way the teachers doesn't need to manually create the sessions or ask admins to do that (not very useful way in big universities).

So there should be REST API for 
1) creating (multiple) session(s) based on external sources e.g. course registrations and for
2) editing the already imported sessions (delete or change dates/times)

**Comment by danmarsden** [comment]
I assume you haven't looked at the code? - this is already supported in 3.7 and higher branches. There is also a pull request in the queue to add support for csv import of sessions that i need to find time for!!
