### ISSUE TITLE
Trouble translating "time" string in sessions page.

### ISSUE THREAD

**Issue by dinism** [danmarsden/moodle-mod_attendance#445]
I'm PT-PT translator. Moodle 3.8 and attendance 3.8.1.
I can't explain this:
**The string in english:**
![imagem](https://user-images.githubusercontent.com/14828021/69587017-38e56180-0fdc-11ea-8274-98158817f116.png)

**The string in portuguese don't use translation:**
![imagem](https://user-images.githubusercontent.com/14828021/69587065-5c101100-0fdc-11ea-89ef-8add299f95d3.png)

**I think it's using this string:**
![imagem](https://user-images.githubusercontent.com/14828021/69587187-cde85a80-0fdc-11ea-9370-dafb3bdccc67.png)

**Comment by danmarsden** [comment]
sounds strange - I'm not able to dig this out right now, but have you seen:
https://docs.moodle.org/38/en/Language_customisation#Finding_the_component_and_string_identifier

Try turning that on and see if it's reporting as coming from time/attendance or if it's coming in from somewhere else?

If you don't manage to find it I'll try to look later this week!

thanks,

**Comment by dinism** [comment]
Thanks for rapid response. I have the debbug on.
**Here it goes. It use the core string not the attendance translation**
![image](https://user-images.githubusercontent.com/14828021/69610295-64d80580-1023-11ea-8d28-2f6039159943.png)
![image](https://user-images.githubusercontent.com/14828021/69610643-1f680800-1024-11ea-9abb-bd72df8b6f66.png)

**Comment by danmarsden** [comment]
I have pushed a fix for this into the 3.5 and higher branches here in github - thanks for the report!
