### ISSUE TITLE
Student password & QR code does not display in IE11 (FF/Chrome/Edge works fine)

### ISSUE THREAD

**Issue by aec2016** [danmarsden/moodle-mod_attendance#446]
Hi Dan,

The Student password and QR code displays fine on Firefox/Chrome/Edge, but does not show on IE11 with following error messages:
![Snipaste_2019-12-06_11-04-31_QRcode-IE11](https://user-images.githubusercontent.com/32948611/70292531-74bcca00-1819-11ea-9be6-4ace0f4dda68.png)

With Moodle version 3.7.3 and latest attendance version 3.8.1 installed.
Hope it is helpful on debugging. Many thanks!

**Comment by danmarsden** [comment]
thanks for the report - feel free to help work on this - I have to admit I don't feel overly motivated to work on something that relates to Internet exporer... :-) - but I might take a look at next year sometime....

**Comment by nwp90** [comment]
Moodle itself no longer supports IE at all. This could probably be closed.

**Comment by danmarsden** [comment]
sounds good to me :-)
