### ISSUE TITLE
Error Prevent students sharing IP address

### ISSUE THREAD

**Issue by syusanjun** [danmarsden/moodle-mod_attendance#448]
I am using Moodle 3.7.3.
Activities: Attendance is 3.7.1 (2019072402).
I can't save if I select yes in the Prevent students sharing IP address setting.
Is it necessary to enter the number of the time when selecting Yes ?

If I select No, I can save without entering the IP time number.

**Comment by danmarsden** [comment]
This is expected behaviour. You must define a timeframe - you can set the default value under admin > plugins > attendance so that you don't have to enter a value each time you use this.
Thanks.

**Comment by syusanjun** [comment]
Thank you for the polite explanation
