### ISSUE TITLE
Limit self-recording period

### ISSUE THREAD

**Issue by mhughes2k** [danmarsden/moodle-mod_attendance#449]
I'm floating the idea, hopefully I can contribute some code to do this, but thought it would be good to share...

It would be really nice if were possible to specify a time-limit for the self recording period.

We can have quite sessions and have a large number of students in them. With students being able to share the password / QR (ie. text the password /picture of the QR code) for the self-recording it would be nice if we could configure the self-recording period to be less / different from the session itself. 

For instance we may only allow self-recording during the first 10 minutes of a session, after that the student would need to explicitly speak to the member of staff.

This also helps with Issue #297 as the self-recording period start could be *before* the session start.

**Comment by danmarsden** [comment]
Hey Michael - isn't this already possible using the status set configuration? - you would only make a single status item available for the first 10min?

**Comment by mhughes2k** [comment]
So it is, hadn't seen that option. Could something similar be used for #297 to allow self-recording before the start of a session too?

**Comment by danmarsden** [comment]
maybe... although I suspect early opening should be a setting within the session or the attendance rather than the status set.

closing this one but feel free to suggest a way to acheive #297 on that issue - thanks!
