### ISSUE TITLE
word translation

### ISSUE THREAD

**Issue by frbb** [danmarsden/moodle-mod_attendance#455]
Hi Dan, I transcribe what was stated in the forum:

- On lines 132 and 529 of the renderer.php file, the translation of the words 'page' and 'of' should be allowed.
- And on line 82 of the export.php file for the word 'Attendances' and line 512 of the locallib.php file for the same word.

Thanks you very much.
Best regards.
Verónica.

**Comment by danmarsden** [comment]
Thanks for adding it here Verónica - I'm surprised no one has reported this before!

**Comment by danmarsden** [comment]
I've pushed a fix into github and updated the plugins db entries to make sure AMOS gets the new strings.

I didn't bump the plugin version in the plugins db, so it won't notify all site admins - the only changes in this release are to the lang strings. Thanks for the report!!
