### ISSUE TITLE
Please use fullname() for display user name

### ISSUE THREAD

**Issue by tatsuvalue** [danmarsden/moodle-mod_attendance#456]
The order of user names in Japanese is surname followed by first name.
for example, My name is "白井(Shirai) 達也(Tatsuya)"．Shirai is surname(last name, family name), Tatsuya is first name.

In attendance report, the order of user names are right, however user name is printed out wrong order for example "達也 白井" in attendance form.

You need to modify a little bit; student_attendance_form..php, class mod_attendance_student_attendance_form, public function definition(), LINE=100,

            $radiogroup = $mform->addGroup($radioarray, 'statusarray', $USER->firstname.' '.$USER->lastname.':', array(''), false);

change to:

            $radiogroup = $mform->addGroup($radioarray, 'statusarray', fullname($USER).':', array(''), false);

This fix has no side effects in Latin-speaking countries.

![image](https://user-images.githubusercontent.com/25736106/75948983-3f8f4900-5ee8-11ea-9c3e-40b39088caaa.png)
![image](https://user-images.githubusercontent.com/25736106/75949063-74030500-5ee8-11ea-8d42-6dfa5dd06816.png)

**Comment by danmarsden** [comment]
Thanks for the report - that should definitely be using fullname there - I'll get that fixed soon.
