### ISSUE TITLE
Separate linked strings

### ISSUE THREAD

**Issue by tatsuvalue** [danmarsden/moodle-mod_attendance#457]
mod/attendance/renderer.php, protected function render_view_controls(attendance_filter_controls $fcontrols), LINE219,

        foreach ($views as $key => $sview) {
            if ($key != $fcontrols->pageparams->view) {
//              $link = html_writer::link($fcontrols->url(array('view' => $key)), $sview);
                $link = html_writer::link($fcontrols->url(array('view' => $key)), $sview."&nbsp;");
                $viewcontrols .= html_writer::tag('span', $link, array('class' => 'attbtn'));
            } else {
//              $viewcontrols .= html_writer::tag('span', $sview, array('class' => 'attcurbtn'));
                $viewcontrols .= html_writer::tag('span', $sview."&nbsp;", array('class' => 'attcurbtn'));
            }
        }

![image](https://user-images.githubusercontent.com/25736106/75953705-48d2e280-5ef5-11ea-8b33-db341caa196f.png)

**Comment by danmarsden** [comment]
closing this one - looks like it was a css issue with the theme in use - hopefully should be sorted now! - thanks!
