### ISSUE TITLE
The New Rotate Option is not working with MS SQL 

### ISSUE THREAD

**Issue by mohamedmohamedatia** [danmarsden/moodle-mod_attendance#459]
The new Rotate Option is not working with MS SQL Server where the 'LIMIT' is not valid syntax in MS SQL Server, it gives the below error

Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'LIMIT'.

SELECT * FROM mdl_attendance_rotate_passwords WHERE attendanceid = '10793' AND expirytime > '1585156464' ORDER BY expirytime ASC LIMIT 2
[array (
0 => 10793,
1 => 1585156464,
)]

**Comment by mohamedmohamedatia** [comment]
I am not sure if the below Query can fix the issue, just a suggestion 

SELECT * FROM (
  SELECT *, ROW_NUMBER() OVER (ORDER BY expirytime ASC) AS RowNum FROM mdl_attendance_rotate_passwords WHERE attendanceid = ? AND expirytime > ?
) AS MyDerivedTable
WHERE MyDerivedTable.RowNum BETWEEN 1 and 2

**Comment by danmarsden** [comment]
thanks for the report, we probably need to use the "limit" parameter that is provided by most Moodle DB functions to do this. I'll try to get to this at some point, but typically MS Sql and Oracle support is 100% reliant on community contributions.
