### ISSUE TITLE
The Rotate option is enabled by default

### ISSUE THREAD

**Issue by mohamedmohamedatia** [danmarsden/moodle-mod_attendance#460]
The Rotate option is enabled by default, and there is no option in plugin admin settings to uncheck it by default. 
this should be added as the current version causes an error with MS SQL

**Comment by syusanjun** [comment]
I'd be happy if the initial setting could be turned off.

**Comment by danmarsden** [comment]
Feel free to help by submitting a pull request or contact me privately if you would like to fund development on improvements. Thanks
