### ISSUE TITLE
Hardcoded admin directory on setting tab

### ISSUE THREAD

**Issue by adamtppaw** [danmarsden/moodle-mod_attendance#461]
Link to tab Settings has hard coded admin directory.
Since directory admin may be renamed to something else,  $CFG->admin should be used.
In file lib.php line 478 should be changed to
```
 $tabs[] = new tabobject('settings', "{$CFG->wwwroot}/{$CFG->admin}/settings.php?section=modsettingattendance",
        get_string('settings', 'attendance'), get_string('settings'), false);
```
To reproduce the problem:
1. Rename admin directory to moodleadmin
2. in config.php change $CFG->admin to "moodleadmin"
3. in administration od plugin change click tab "Default status set"
4. click tab "Settings"
You got 

> Not Found
> The requested URL /admin/settings.php was not found on this server.

**Comment by danmarsden** [comment]
Thanks for the report - feel free to submit a pull request with that change, otherwise I'll try to get to it at some point.
