### ISSUE TITLE
Update automatic attendance when teacher access to attendance list without having to wait for the cron (or at least add a button to do it)

### ISSUE THREAD

**Issue by matheod** [danmarsden/moodle-mod_attendance#463]
By default, automatic attendance are only marked every hours. It would be nice if attendance was automatically updated when the teacher is opening the attendance list of the session.

Having a button to manually update automatic attendance could also be a solution.

Thanks

**Comment by danmarsden** [comment]
feel free to help us work on this by submitting a pull request. Thanks.

**Comment by matheod** [comment]
So I looked at code and I might be able to do it. However as I never coded anything on moodle it might be messy and require some cleaning by someone more expert :D
