### ISSUE TITLE
Deprecated core strings used on messaging page

### ISSUE THREAD

**Issue by NeillM** [danmarsden/moodle-mod_attendance#467]
Found under Moodle 3.8

String [backtoparticipants,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7306 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 159 of /mod/attendance/messageselect.php: call to get_string()

String [previewhtml,core] is deprecated. Either you should no longer be using that string, or the string has been incorrectly deprecated, in which case you should report this as a bug. Please refer to https://docs.moodle.org/dev/String_deprecation
line 394 of /lib/classes/string_manager_standard.php: call to debugging()
line 7306 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 134 of /mod/attendance/messageselect.php: call to get_string()

**Comment by danmarsden** [comment]
Thanks Neil - I saw that recently but forgot to fix it! 

We copied the old UI for bulk messaging from Moodle 3.3 code but should have copied the strings over at the same time.

I'll push through a fix shortly.
