### ISSUE TITLE
Causes core_calendar unit test to error

### ISSUE THREAD

**Issue by micaherne** [danmarsden/moodle-mod_attendance#473]
Version: 2019112500

On running the unit test core_calendar_container_testcase::test_delete_module_delete_events there is an error caused by mod_attendance:

    core_calendar_container_testcase::test_delete_module_delete_events
    Undefined property: mod_attendance_structure::$cmid

    /var/lib/jenkins/workspace/c2-build/moodle/calendar/tests/container_test.php:454
    /var/lib/jenkins/workspace/c2-build/moodle/lib/phpunit/classes/advanced_testcase.php:80

    To re-run:
     vendor/bin/phpunit "core_calendar_container_testcase" calendar/tests/container_test.php

This seems to be because the test generator for mod_attendance unsets the cmid property expected by the unit test (introduced by the fix for #431: https://github.com/danmarsden/moodle-mod_attendance/commit/a0d198b084db503fda0602314203de83468742ae)

**Comment by micaherne** [comment]
Just to say, normally I'd provide a patch for this, but I don't understand why the cmid was explicitly removed, so I'm not sure what issues may be introduced by reversing it.

**Comment by danmarsden** [comment]
hmm - that does look weird... not sure why @kabalin added that unset there... will need to find some time to go digging...

**Comment by kabalin** [comment]
Hi, that unset was in place before that code moved to generator: https://github.com/danmarsden/moodle-mod_attendance/commit/a0d198b084db503fda0602314203de83468742ae#diff-30b491967780eb6b876fd01cae33c43dL95

But I am not 100% sure removing that unset will fix the issue, as it looks like, if you leave that properly, class instantiation will fail here https://github.com/danmarsden/moodle-mod_attendance/blob/master/classes/structure.php#L124

**Comment by micaherne** [comment]
It looks like that might be the root of the issue, returning a custom class from the generator. In the generator base class the create_instance return type is defined as:

    @return stdClass record from module-defined table with additional field
            cmid (corresponding id in course_modules table)

I wonder if it would work to change create_instance() to return the $att object as expected, and introduce another method to get the whole mod_attendance_structure if needed?

**Comment by danmarsden** [comment]
I'm currently just thinking that I'll add a cmid to the class and set it to the $cm->id if not set.
