### ISSUE TITLE
Installation on localhost breaks Xampp

### ISSUE THREAD

**Issue by maxx37** [danmarsden/moodle-mod_attendance#474]
Hello,
I had a working moodle 3.8.1 runnig locally on xampp, Windows 10.
All went well until I tried to install this attendance plugin.
Installation ends with a sudden "connection reinitialized" error in Firefox (in Dutch however).

Not only I can't start Moodle anymore after this, I can't even reinstall it: same error persists.

No big deal, since this local installation is meant to try out new things, fortunately it's not a production server. But the results of trying to install this plugin are disappointing to say the least.
After deleting and reinstalling both xampp and moodle, both are running again.
But I will think twice before I do another attempt with the attendance plugin.

Any idea what happened here? I did not have any other similar problems before.

Beste regards, Marc

**Comment by danmarsden** [comment]
Hi Max - typically this suggests something went wrong with your installation process and there isn't really enough information here to suggest this is a problem with the attendance plugin.
There is some good info here on installing plugins:
https://docs.moodle.org/38/en/Installing_plugins

If that doesn't help, try asking for further help in the moodle community forums - good luck!
