### ISSUE TITLE
Date Format is inconsistent 

### ISSUE THREAD

**Issue by demontech** [danmarsden/moodle-mod_attendance#477]
Hi Dan,

I'm using en_us language and I noticed that date format is not consistent throughout the plugin. English_US format should be %m/%d/%Y but it's taking it as %d.%m.%Y in some areas.

![image](https://user-images.githubusercontent.com/8148238/86038526-eea2e380-b9f5-11ea-912d-928a6bf3651c.png)

![image](https://user-images.githubusercontent.com/8148238/86038716-3590d900-b9f6-11ea-940a-5700bb14dd44.png)
![image](https://user-images.githubusercontent.com/8148238/86038843-6b35c200-b9f6-11ea-9184-f52b88f2851a.png)

I have changed the strings on the language for the plugin. I have also deleted the strings hoping that the system will take over, but nothing.

Can you direct me or help me on how to fix this ?

Users are getting confused

Thank you for this great plugin!

**Comment by danmarsden** [comment]
Language strings are cached - to change the format of strings you should be using the details here:
https://docs.moodle.org/39/en/Language_customisation

also - if you believe the en_us lang pack is incorrect - feel free to submit a suggested change here:
https://lang.moodle.org/

For more help on customising lang strings, please ask for help in the community forums on moodle.org - thanks!
