### ISSUE TITLE
is there a web service to record attendance

### ISSUE THREAD

**Issue by m7mdyahia** [danmarsden/moodle-mod_attendance#478]
I am building an integration with zoom to get the online attendee email form api I would like to record this in the plugin,

**Comment by danmarsden** [comment]
Hi there. the best place to ask questions is the moodle community forums here:
https://moodle.org/mod/forum/view.php?id=741

If you are not able to rread the code to see the webservices that are currently supported you should look at the web services documentation built-in to Moodle.
Install the attendance plugin in your site, and then view the webservices documentation available within the admin interface.

more info on this here:
https://docs.moodle.org/dev/Web_services#Developer_documentation

If you have any further questions, please use the forum linked above - thanks! :-)
