### ISSUE TITLE
Late or Absent sent email notification to student

### ISSUE THREAD

**Issue by ArslanKathia** [danmarsden/moodle-mod_attendance#480]
Is there any function in this plugin to send an email notification to students because you are late or absent from the class...
please let me know I am waiting for your response.
Thanks in advance,

**Comment by danmarsden** [comment]
questions that start with "is there" or " can I" are typically best asked in the moodle community forums:
https://moodle.org/mod/forum/view.php?id=741

Short answer is - there is an absentee report with the ability to set "warning sets" which allow students to be emailed - but please use the forums to ask for help setting this up.
