### ISSUE TITLE
prevent student sharing IP address

### ISSUE THREAD

**Issue by pvella73** [danmarsden/moodle-mod_attendance#482]
When creating an Attendance activity in a course and saving the setting 'prevent student sharing IP address' to No, this setting is  changed when you edit the activity, and now the setting 'prevent student sharing IP address' is showing as 'Specified time in minutes to release IP' Require network address is also enabled.

Not sure if this is intended or a bug.

Steps to replicate:
1. Create an attendance activity,
2. Change the following settings; set the setting 'prevent student sharing IP address' to "No",
3. Edit the newly created session,
4. Note the setting 'prevent student sharing IP address' is now showing as 'Specified time in minutes to release IP'
Require network address is also enabled, even if disable in previous steps.

**Comment by danmarsden** [comment]
I couldn't reproduce this - what version of Moodle and what version of the attendance plugin are you using here?

there are a number of places that set those settings including the "default" settings you make at the site level under admin > plugins > attendance

**Comment by pvella73** [comment]
Hi Dan,
Thanks for getting back to me.
Below are the version of Moodle and the Attendance module we have in our systems.

Moodle 3.8.3 (Build: 20200511)
mod_attendance 3.8.1  2019112500

I can also see this is not changing now, so not sure if this was fixed when we moved from 3.7.3 to 3.8.3, but I can no longer replicate it either.

**Comment by danmarsden** [comment]
Great! :-)
