### ISSUE TITLE
DB schema alignment issue: Missing index 'caleventid' after upgrade

### ISSUE THREAD

**Issue by kristian-94** [danmarsden/moodle-mod_attendance#484]
I did an upgrade from this old commit to this new one  on the `MOODLE_37_STABLE` branch:
```
-Subproject commit 833a38f27f0693a22675006d686b6dec2996d044
+Subproject commit 14773cb85ac457dcb143b6cb4dea117aa471214b
```
and the schema check gives me:
```
+ php admin/cli/check_database_schema.php
-------------------------------------------------------------------------------
attendance_sessions
 * Missing index 'caleventid' (not unique (caleventid)). 
CREATE INDEX mdl_attesess_cal_ix ON mdl_attendance_sessions (caleventid);
-------------------------------------------------------------------------------
```
I don't see any adding of this index in the upgrade.php script so I am thinking that's the issue.

**Comment by danmarsden** [comment]
weird - that's 4 years old... I can't see the index being added anywhere in the upgrade script either. Feel free to submit a pull request to fix this otherwise I'll try to get to it at some point!

thanks,
