### ISSUE TITLE
invalid respon in webservice mod_attendance_get_courses_with_today_sessions

### ISSUE THREAD

**Issue by irawand07** [danmarsden/moodle-mod_attendance#488]
get today session by userid invalidresponse if one course have 2 attendance,
sample : 
attendance 1 have one session in today and attendance 2 session is empty

`{
  "exception": "invalid_response_exception",
  "errorcode": "invalidresponse",
  "message": "Invalid response value detected",
  "debuginfo": "attendance_instances => Invalid response value detected: Error in response - Missing following required key in a single structure: today_sessions"
}`

**Comment by danmarsden** [comment]
Thanks for the report - feel free to work on this by submitting a pull request or suggesting a code change that would fix this.

thanks!

**Comment by pascaleandrei** [comment]
I've made a pull request #570  to solve this issue. Can you please take a look?

**Comment by danmarsden** [comment]
thanks -the fix made sense - merged it in.

**Comment by pascaleandrei** [comment]
Thank you!
