### ISSUE TITLE
Add Session Descriptions to excel export

### ISSUE THREAD

**Issue by Jessica-eWC** [danmarsden/moodle-mod_attendance#493]
Hi, we are loving the attendance module for daily attendance tracking, but we'd like to be able to include the session descriptions in the export to excel. Is this something that can be implemented? 

We use the session description to list each unit covered in that session and for our Govt. funding contract we need to retain that data even after a student withdraws. If we could export the session description in the excel export we could fulfil that requirement easily and remove the student from the group so they no longer appear on the class roll.

**Comment by danmarsden** [comment]
Sure - would it be sufficient to add the description to the end of the date/group? - eg in the header column you currently get a column with the text "8 May 2020 1.00AM All students" - I'm guessing we'd add a checkbox under the "include remarks" option on the export page called "include session description" and then it would just add the description to the end of the text in that column so you'd have "8 May 2020 1.00AM All students - Big long session description to keep funders happy" - potentially getting a bit long, but might be all you need?

**Comment by Jessica-eWC** [comment]
Hi Dan,

Yep, that's exactly what I'm hoping can be done!

**Comment by danmarsden** [comment]
cool - I've just dropped a simple version of this into the main branch (supports 3.8 and higher) - unfortunately the export form is one that doesn't have the ability to control which items are selected by default so you'll need to rememeber to always tick the box to include the description at the moment. one day I might add export form default control to the site-level settings.
