### ISSUE TITLE
Attendance session import: support repeating sessions

### ISSUE THREAD

**Issue by danmarsden** [danmarsden/moodle-mod_attendance#494]
As per discussion here:
https://moodle.org/mod/forum/discuss.php?d=358298#p1506714

We need to restructure the session creation code so that it can re-use the same process as the normal individual form.

**Comment by samadkariot** [comment]
Great..Waiting for some one solve this

**Comment by iamgregf** [comment]
Would love if the "repeaton" function was working.  Thanks!

**Comment by danmarsden** [comment]
pull requests always welcome or feel free to get in touch privately if you would like to fund specific feature development :-)

**Comment by danmarsden** [comment]
should be fixed in latest code.
