### ISSUE TITLE
English string hardcoded

### ISSUE THREAD

**Issue by sleitao** [danmarsden/moodle-mod_attendance#495]
The english string "Time left:" is hardcoded on /js/password/attendance_QRCodeRotate.js line 46.

```
    updateTimer(timeLeft) {
        this.timerHTMLElement.innerHTML = '<h3>Time left: '+timeLeft+'</h3>';
    }
```
Thank you for this module!!!
susana

**Comment by danmarsden** [comment]
thanks for the report - I'd really like to convert that js into ES6 at some point, but feel free to help by submitting a pull request to fix this (either by converting to es6 or some other method until I get round to that.)
