### ISSUE TITLE
Data generator returns mod_attendance_structure object instead of stdClass

### ISSUE THREAD

**Issue by golenkovm** [danmarsden/moodle-mod_attendance#496]
Hi,

Looks like its parent method returns stdClass https://github.com/moodle/moodle/blob/master/lib/testing/generator/module_generator.php#L224 while after #431 mod_attendance generator returns mod_attendance_structure object.

In PHP7.4 environment this block of code
```
$attendancemodule = $this->getDataGenerator()->create_module('attendance', ['course' => $course, 'section' => 2]);
$handler = mod_handler::create(0, 'attendance');
$instance = clone $attendancemodule;
$instance->id = $attendancemodule->cmid;
$instance->customfield_previewdescription = 'Hello World!';
$handler->instance_form_save($instance);
```
explodes with an error
`TypeError: Argument 1 passed to core_customfield\handler::instance_form_save() must be an instance of stdClass, instance of mod_attendance_structure given`

Apparently it can be fixed by replacing `$instance = clone $attendancemodule;` by `
`$instance = new stdClass();`, but for the consistency it looks to me that mod_attendance generator should retrun stdClass like its parent.

**Comment by danmarsden** [comment]
Thanks Misha, 

This is triggering a failure in a 3rd party plugin which uses the generator to create an attendance - probably something worth looking at fixing but it sounds like you've fixed it in the 3rd party plugin for now.

Feel free to submit a pull request to fix it in the attendance side :-)
