### ISSUE TITLE
mod_attendance: Error message displayed on Report tab when an Outcome is selected

### ISSUE THREAD

**Issue by kiratskitizing** [danmarsden/moodle-mod_attendance#501]
Environment:
Moodle- 3.9.2+ (Build: 20201028)
Attendance- 2020082500

Setup
1. Go to Site administration > Advanced features
2. Tick the Enable outcomes checkbox
3. Save changes

Replication
1. Create a course.
2. Click Cog icon / Outcomes.
3. Click "Edit outcomes"
4. Click "Add a new outcome"
fullname: test1
shortname: test1
scale: default competence scale
5. Save the changes.
6. Go back to course contents page and turn editing on.
7. Add an Attendance activity.
8. In the Outcomes section, click/tick "test1".
9. Click "Save and display".
10. Click the "Report" Tab.
RESULT
```
Found more than one record in fetch() !
Debug info:
Error code: morethanonerecordinfetch 
Stack trace:
* line 498 of /lib/setuplib.php: moodle_exception thrown
* line 163 of /lib/grade/grade_object.php: call to print_error()
* line 361 of /lib/grade/grade_item.php: call to grade_object::fetch_helper()
* line 1329 of /mod/attendance/classes/structure.php: call to grade_item::fetch()
* line 214 of /mod/attendance/renderer.php: call to mod_attendance_structure->get_lowgrade_threshold()
* line 70 of /mod/attendance/renderer.php: call to mod_attendance_renderer->render_view_controls()
* line 461 of /lib/outputrenderers.php: call to mod_attendance_renderer->render_attendance_filter_controls()
* line 85 of /mod/attendance/report.php: call to plugin_renderer_base->render() 
```
![Screenshot_20201030_122158](https://user-images.githubusercontent.com/16247613/97650958-dbd71300-1aaa-11eb-8562-2b4707ac87c0.png)

**Comment by danmarsden** [comment]
Thanks for the detailed report. Feel free to help work on this by submitting a pull request with a patch.
