### ISSUE TITLE
Ability to add summary for session

### ISSUE THREAD

**Issue by nicktones** [danmarsden/moodle-mod_attendance#502]
It would be useful to be able to add an overall summary for the session, and for this to appear in reports. This would be useful for a teacher to record general progress of the class, etc. With that in mind, should only be shown to teacher.

**Comment by danmarsden** [comment]
have you seen the "showsessiondescriptiononreport" setting ? - does that do what you're wanting?

**Comment by nicktones** [comment]
Not exactly. I'm looking for a section for each session in which the teacher can add a summary of what happened in that session (learning objectives, success, challenges, etc). This would not be shown to students, in the way the session description is, but would be available to other staff and with the ability to include in reports.

**Comment by nicktones** [comment]
Is this something that could be implemented?

**Comment by danmarsden** [comment]
Sure - anything is possible :-) - I can't see myself spending time on implementing this as a volunteer though. If you have internal development capabilities, Pull requests are always welcome - otherwise feel free to get in touch privately if you would like to fund feature development on the attendance plugin.

thanks!

**Comment by nicktones** [comment]
This shouldn’t be closed, as the new custom fields feature while great, does not allow teachers to enter values containing evaluations of their sessions.

**Comment by danmarsden** [comment]
You can add a text based custom field called 'summary' then when session is over you can edit the session and put your summary into the box provided. Perhaps you could explain further how that doesn't meet your needs or how it could be improved to meet them?

**Comment by danmarsden** [comment]
@nicktones - did you have any further feedback - what do you think is still missing there?

**Comment by nicktones** [comment]
Sorry for the delay, I was checking this out a little more. Honestly, it's pretty close, though we would need to further changes to make this work for us...

- The additional boxes for the fields should show on the register page itself, rather than in settings.
- When setting the additional fields to 'required' the registers can't actually be created without the something going into the boxes at time of creation. We need a 'required for teachers to complete' option.

The reason for both of these items is that (and I assume this isn't uncommon) our registers are setup for a full course by our administrators. A teacher simply completes them at the beginning (attendance) and end (session notes) of the session. Also, the 'required' for the custom field option, means that even if a teacher does create the register, they need to enter something into these boxes at the time of creation. When seeking to capture session notes / evaluations, etc. these obviously can't be written until after the session is complete.

I appreciate that we actually don't really need the required option - we can just enforce this through policy. Though it does make sense to display the custom fields on the register itself, rather than in settings. This would make for a better flow, and for teachers not to be bothered by the other settings.

**Comment by danmarsden** [comment]
thanks - I've just added a new issue in the tracker #635 to cover this requirement - not sure I'll get to it myself, but good to have it in mind for future work. as always, pull requests (and or funding to improve the plugin) are always welcome.
