### ISSUE TITLE
Feature request: add API for "all module sessions"

### ISSUE THREAD

**Issue by mikeleikele** [danmarsden/moodle-mod_attendance#504]
I need read all sessions id for the attendance module, and I don't find any method to retrieve them.
It's possible to add to "mod_attendance_external" class a method that, **given the id** (cmid) of "moodle-mod_attendance" module **returns all sessions id**?

**Comment by danmarsden** [comment]
Sure - Pull requests are always welcome. :-)

**Comment by danmarsden** [comment]
this landed in commit id: c349f489d9579ecfc60e2c22aca4ff2e06f869a5
