### ISSUE TITLE
Maintain or drop changelog

### ISSUE THREAD

**Issue by abias** [danmarsden/moodle-mod_attendance#509]
Hi Dan,

this is just a quick note that your changelog in https://github.com/danmarsden/moodle-mod_attendance/blob/main/CHANGELOG.md is completely outdated and I don't see another location where you maintain a changelog.

For admins, it would be really helpful to be able to check a changelog before updating the plugin. Currently, I have to check the Git commits before every update.

Would you be able to pick up maintaining the changelog again - or, if not, drop the file to avoid confusion at least?

Cheers,
Alex

**Comment by danmarsden** [comment]
I've been thinking about this for a while - thanks for the prompt.

I used to post an update in the attendance forum on each plugin db update with a list of the new features, but it would be good to document this better.... it's just more fun writing the code than doing the documentation ;-) 

I think it probably makes sense to maintain the changelog a bit better, I'll see if I can motivate myself to writing something in there sometime after christmas! :-)
