### ISSUE TITLE
Scales not working?

### ISSUE THREAD

**Issue by t6nis** [danmarsden/moodle-mod_attendance#51]
Hey,

It appears that the scale option is not working?? Is it meant to be like this or this can be improved?

Use case: When scale is selected then in mdl_attendance the grade field is marked with "-[scaleid]".
Now when marks are added to users then they are not saved in gradebook. Because in locallib around line 890 is:
        if ($this->grade != 0) {
            $this->update_users_grade(array_keys($sesslog));
        }

If the attendance module is not intended to support scales then the scale option in mod_form should be removed to avoid confusion.

**Comment by SWiT** [comment]
I think the scale option should be removed until scales are implemented properly.  I'll make an attempt at a patch at some point soon.

**Comment by cedict** [comment]
We just figured this out as students were getting 'Failed' / 0 in the gradebook. I believe the Attendance module was hidden from student view and gradebook was the reporting method. We had 35 Attendance modules in the system with a scale selected

**Comment by danmarsden** [comment]
Thanks Greg - flagging this as finished, would be good if any of the other reporters on here could verify with the patch I've just merged from Greg.

**Comment by danmarsden** [comment]
Greg's patch caused a regression so I've reverted it and re-opened this. Greg let me know if you'll have a chance to take another look at this.
