### ISSUE TITLE
Fails to set password when importing CSV

### ISSUE THREAD

**Issue by nwp90** [danmarsden/moodle-mod_attendance#510]
The CSV import process fails to set the student password if it is specified in a CSV to import.
The reason for this is that classes/import/sessions.php uses the form attribute "passwordgrp" to hold the password while the attendance_construct_sessions_data_for_add function in locallib.php expects it to be in the attribute "studentpassword".

Changing attendance_construct_sessions_data_for_add (in several places) to get the password from $formdata->passwordgrp instead of $formdata->studentpassword does fix this problem, but I don't know offhand what else this might break, and hence whether to make the change in that function or in classes/import/sessions.php (and I don't know what else that might break, either).

Cheers,

Nick

**Comment by danmarsden** [comment]
Thanks Nick - I'll go digging with this one - sounds like a rewrite of that handling is probably due...

**Comment by danmarsden** [comment]
should be fixed now.
