### ISSUE TITLE
Export button disabled after downloading a file, should re-enable on setting change.

### ISSUE THREAD

**Issue by windadev1** [danmarsden/moodle-mod_attendance#511]
When I use the export function everything works fine but the OK button gets disabled and this prevents me from exporting a second time with different settings. The only workaround is reloading the page and to set all settings again. 
Can you remove the disable function of the ok button after the first export ? 

Thank you in common! 
![export_disabled](https://user-images.githubusercontent.com/20618772/108494065-64baca00-72a7-11eb-962f-4e2430c2df14.png)

**Comment by danmarsden** [comment]
Thanks for the report - sounds annoying! - I'll keep this in the backlog but pull requests are always welcome too.

**Comment by danmarsden** [comment]
this looks to have been fixed - I suspect it was something related to the upstream API we were using.
