### ISSUE TITLE
intermittent unit test failure - timezone related?

### ISSUE THREAD

**Issue by danmarsden** [danmarsden/moodle-mod_attendance#512]
There was 1 error:

1) mod_attendance_external_testcase::test_get_courses_with_today_sessions_multiple_instances
invalid_response_exception: Invalid response value detected (attendance_instances => Invalid response value detected (Error in response - Missing following required key in a single structure: today_sessions): Error in response - Missing following required key in a single structure: today_sessions)

/var/www/html/lib/externallib.php:459
/var/www/html/lib/externallib.php:474
/var/www/html/mod/attendance/tests/externallib_test.php:130
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit --colors "mod_attendance_external_testcase" mod/attendance/tests/externallib_test.php

--

There was 1 failure:

1) mod_attendance_external_testcase::test_get_session_with_group
Failed asserting that 0 matches expected '266000'.

/var/www/html/mod/attendance/tests/externallib_test.php:200
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit --colors "mod_attendance_external_testcase" mod/attendance/tests/externallib_test.php

**Comment by NeillM** [comment]
I haven't looked at it, but just based on the name of the test I imagine it is a midnight issue, i.e. data generation too place on one side of it and the call on the other (then the event would not be in the same day)

**Comment by danmarsden** [comment]
Yeah that was my guess too - we had a few pipelines fail last night on this and I'd seen it before but forgotten to create an issue to remind me to come back to it - didn't have time to look into it today but wanted to make sure I remembered!  It's a pain when stuff like this blocks our CI.
