### ISSUE TITLE
backup/restore of courses or mod attendance activities generate ghosts calendar events

### ISSUE THREAD

**Issue by jumabgz** [danmarsden/moodle-mod_attendance#517]
Hi Dan,

When restoring a course backup that includes _mod_attendance_ with calendar events, additional events appear in the course calendar that are not related to specific sessions and cannot be deleted.

Once you have this ghosts events, they remain even if you delete all sessions.  They only disappear if the attendance activity is deleted.

The same problem occurs if a _mod_attendance_ activity with ghosts events is duplicated in the course.

I have tested it with Moodle 3.9.4+ and mod_attendance 3.9.1 (2020120300).

Maybe I am doing something wrong?

Thank you!

**Comment by danmarsden** [comment]
Hi @jumabgz - any chance you could email me a copy of a backup file that allows me to reproduce this? - you should be able to work out an e-mail address that works by sending to my first name at danmarsden.com

I have heard other reports of weird events like this ending up in the calendar but I haven't worked out how to reproduce it yet!

**Comment by jumabgz** [comment]
Hi Dan,

No problem, I am sending you a backup of a course with an attendance activity and phantom calendar events. 

Sorry, I should have described better the steps to reproduce the problem.

To reproduce the problem in a clean Moodle 3.9.4+, only with mod_attendance 3.9.1 (2020120300):

1. Create new course.
2. Add the calendar block to the course.
3. Create an attendance activity.
4. Create a session.
5. Check that the event of the session appears in the calendar block.
6. Create a backup copy of the course.
7. Restore to a new course.
8. Check that two sessions appear in the calendar block on the day on which the session of point 4 was created.
9. Go to the attendance activity and delete the session.
10. Check that the phantom event is still in the calendar.

* If this is done with a backup copy of the activity, it is also reproduced.
* If duplicates of the attendance activity are made in the restored course, new phantom events are generated.

Thank you,
Regards

**Comment by danmarsden** [comment]
got that thanks - quite busy this week but will try to find some time to reproduce and track that issue down!

**Comment by danmarsden** [comment]
Thanks for sending that backup file through - it made it much easier to reproduce and I've just pushed through a patch to prevent it from happening again, and an upgrade script to clean up any orphaned events.

let me know if you get a chance to test it!

thanks,

**Comment by jumabgz** [comment]
Hi Dan, thank you for working on this issue, I can confirm it is working fine. I've been using the latests version from quite some time now.

Regards
