### ISSUE TITLE
Missing text wrapping

### ISSUE THREAD

**Issue by jleyva** [danmarsden/moodle-mod_attendance#519]
Ionic columns should include the text-wrap attribute to avoid the text overlay the next column in mobile devices:

https://github.com/danmarsden/moodle-mod_attendance/blob/3420afac37573c621df17a365ca4cc2933fe837e/templates/mobile_view_page.mustache#L77

See example:

<img width="202" alt="imagen" src="https://user-images.githubusercontent.com/615556/110467997-fc0d8300-80d7-11eb-8ec7-335ada7b1381.png">

**Comment by danmarsden** [comment]
cool - thanks @jleyva
