### ISSUE TITLE
Feature request: Create Sessions with CSV Import

### ISSUE THREAD

**Issue by minetonight** [danmarsden/moodle-mod_attendance#52]
By creating a CSV file to import sessions we can easily produce large amounts of sessions without mistakes. Currently it's a little counter-intuitive. Any update to the session creation options might consider simplifying this step.

**Comment by danmarsden** [comment]
The latest version in github for Moodle 3.2 and higher now provides a tool that lets you create sessions using a csv. Thanks to Xi’an Jiaotong Liverpool University for providing the funding to complete this.

**Comment by gemguardian** [comment]
Hi Dan,

Will this version also be published towards Moodle.org? 
Thank you 

Gemma

**Comment by danmarsden** [comment]
typically I wait for a bit when new features land - allowing for a few people to test before I release it to the masses in the plugins db. I've just had some feedback related to this feature this week so there are probably going to be a few more changes incoming.
