### ISSUE TITLE
qr_pass_wrong

### ISSUE THREAD

**Issue by alamo47ivan** [danmarsden/moodle-mod_attendance#522]
Hi @danmarsden Since the update to Moodle 3.10.2, the QR Rote functionality has stopped working for me.

It shows the students the error "qr_pass_wrong" even though the QR password has started to show again. It always throws the same error. I have tried modifying the intervals and it keeps showing the same error. If it works if I deactivate the QR rotate functionality, that is, that the QR remains static. 

![image](https://user-images.githubusercontent.com/75943822/111543847-ea7d4880-8773-11eb-9bdb-d934a96fd7c1.png)

**Comment by danmarsden** [comment]
have you modified the rotateqrcodeinterval setting? - what do you have that set to?

**Comment by alamo47ivan** [comment]
Yes, I had to change it since initially when it was in 2s I got a different error "qr_cookie_error".

![image](https://user-images.githubusercontent.com/75943822/111545977-3e3d6100-8777-11eb-84e6-2d35d4ca724e.png)

**Comment by danmarsden** [comment]
I can't remember if the JS required your local time to be correct? - I assume your server time is correct and you have it set correctly on your local machine too? - Otherwise I haven't seen this issue before and would need to go digging around to see if I can reproduce this (and I'm quite busy at the moment)

**Comment by alamo47ivan** [comment]
I have checked this that you have told me about the hours, and it is the same on the server where I have my moodle mounted and the device that I used to replicate the error. It is quite strange, and the debug does not give any more information either except for the error I fixed at the beginning of the message. Tomorrow I will try to replicate the error in another moodle that I have in 3.9.

**Comment by danmarsden** [comment]
Did you make any further progress on this one?

**Comment by alamo47ivan** [comment]
None. I have finally decided to leave it static.

**Comment by alamo47ivan** [comment]
Any progress on this? I have tried another Moodle with the same version of the plugin and it keeps giving the same error. (qr cookie error). I would only have to try updating to Moodle 3.11 and testing with the new version of the plugin.

**Comment by danmarsden** [comment]
Hi @alamo47ivan - as you can imagine - everyone in the online learning space is crazy busy at the moment - I will come back to this at some point, but hard to prioritise volunteer time on things over family/work committments.

**Comment by danmarsden** [comment]
HI @alamo47ivan - not sure if you got this sorted, but I've just pushed in some extra debugging code to help diagnose this in to the Moodle 4.0 version of this plugin. If you are still having issues, please make sure you upgrade to the latest 4.0 version in github here, and turn "developer" debugging level on. - if developer mode debugging is set, it will display an error like:
```
The current server time is: 29 August 2022, 2:02:39 PM and this QR Code expired at: 29 August 2022, 12:55:44 PM
