### ISSUE TITLE
Only admin user can select hidden/restricted custom user profile fields for export

### ISSUE THREAD

**Issue by stonerl** [danmarsden/moodle-mod_attendance#525]
I have defined some custom user profile fields, like telephone number and other sensitive data, that only the user themselves and admin/manager/editing teachers are allowed to see.

When exporting the attendance list, a non admin user (manager/editing teacher) can't select these custom fields because they are hidden from them. Although they are allowed to see these fields in Moodle.

Moodle 3.9.6+ (Build: 20210416) | Version 2020061506.03
mod_attendance Release 3.9.1

**Comment by danmarsden** [comment]
The admin user can control which custom fields show in the attendance export - have you had a look at the settings under > admin > plugins > attendance to see if anything there helps?

**Comment by stonerl** [comment]
@danmarsden I'll attach some screenshots to show you the issue.

Here are the custom fields, I enabled.
<img width="621" alt="image" src="https://user-images.githubusercontent.com/2091312/115518328-5168b280-a288-11eb-8df4-1291c33b877f.png">

Here is what I see as an admin when I want to export a list.
<img width="621" alt="image" src="https://user-images.githubusercontent.com/2091312/115518482-7f4df700-a288-11eb-88b8-d7afb4650be9.png">

Here is what a manager/teacher sees.
![Screenshot 2021-04-21 113429](https://user-images.githubusercontent.com/2091312/115532190-dad2b180-a295-11eb-8d58-4ed06b8cefbb.png)

**Comment by stonerl** [comment]
This cannot be replicated when using Moodles "Switch role to..." functionality. One has to log in as site manager or course teacher.
