### ISSUE TITLE
Automarking attendance simply does not work...

### ISSUE THREAD

**Issue by preney** [danmarsden/moodle-mod_attendance#529]
While I had thought #385 might have been the fix but apparently it is in mainstream so this is a different issue? I am running:

- Moodle v3.11 stable (build 20210517)
- Attendance module: mod_attendance | 3.11.12021060700

but this issue occurred with v3.10 as well. I am trying to use automarking (i.e., I want the attendance tool to see if the student access the course within the time period and if so assign the highest mark (i.e., present) for that time interval). It seems that the code should do this --but it does not no matter what I set or unset things to: using the defaults, turning off the ability for students to record their own attendance, etc., etc.

NOTE: The automarking feature will only set "Automatically set when not marked" to all students (i.e., it is useless). I have been trying this with various settings for periods for new "test" sessions and manually running the scheduled task to have it run again. No matter the settings it simply refuses to set anything other than the lowest mark,

The status set I am using is:

- P, Present, 2.00
- L, Late, 1.00
- E, Excused, 1.00
- A, Absent, 0.00
- N, Not set/selected, 0.00, Available for students (minutes): 0, Automatically set when not marked: checked

I am not using any IP settings or passwords at all.

How can I make this work --even the default settings don't work? Similarly, what can I do to help facilitate debugging? If I should check any database field values, please let me know what I should check. (I have been manually doing attendance for hundreds of persons and really want to fix whatever the problem is. :-) )

Thanks for any help that can be given.

Paul

**Comment by danmarsden** [comment]
is Available for students (minutes): set to 0 for all status values? - you need to have a status that is "available" for it to be used in auto-marking.

eg - If you set avaialble for students for Present to 30min, anyone viewing the course 30min after the start will be flagged as present.

**Comment by preney** [comment]
I updated is available to 0 for all fields to be zero (in the course and globally). I recreated the session in the course and manually ran the "attendance sessions that require auto marking" scheduled task with the same result: all persons are set to N (i.e., not set/selected). Setting Present to a larger value, e.g., 1, 15, or 30 does not work either.

**Comment by preney** [comment]
I've done a diff of mod/attendance relative to what is in the git repository and everything matches. While I do hope it is simple to fix, I am at the point of diving in to code to figure out what is going on. At least I know I can trigger the code to run --it just appears to place the wrong values in.

**Comment by danmarsden** [comment]
you're not using login-as to test this with students are you? - I suspect the code doesn't support that?

**Comment by preney** [comment]
No, I am using already recorded data from earlier today. The Attendance activity is hidden so students cannot see it. I am trying to get it to automatically record the attendance. (Previously I had students do it manually and I proofed everything manually since things weren't working --but I don't want to continue doing that!) So creating a session within the Attendance activity in the past (i.e., earlier today) and then manually running the Scheduled task causes it to run and update things. The task will not update anything automatically until the session is over so I don't see how doing this would break anything. That said, any and all help / ideas you may have are very much appreciated!

**Comment by preney** [comment]
As for account usage... I am logged in as myself and I am not using login as features, etc. The students are all independent persons.

**Comment by danmarsden** [comment]
I suspect this might be where the issue you're seeing is:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/classes/task/auto_mark.php#L154-L156

If the auto-mark process runs "after" the session is finished, it looks like it's not checking the time correctly.
it might need to be reversed like this:
                            if (!empty($userfirstaccess[$log->studentid])) {
                                $log->statusid = $att->get_automark_status($userfirstaccess[$log->studentid], $session->id);
                            } else if ($sessionover) {
                                $log->statusid = $setunmarked;
                            }

I haven't tested that though - so let me know if it works.

**Comment by danmarsden** [comment]
same issue here with the order incorrect.
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/classes/task/auto_mark.php#L185

bit of code duplication there that would be nice to clean up one day...

**Comment by preney** [comment]
Okay reversing those to if checks mentioned caused many to remain unselected and the rest were selected as N (i.e., 0 score) --not the highest score available. The ones that are marked as zero appear to not have attended --so that is good. Yay!

To have any values set for P (present, value 2) the is available setting must be > 0. Additionally, those students must have accessed the course starting from the session start + is available --or they don't get set. I will work with this. (That said, it looks like your hypothesis is correct: the if statements appear to need to be swapped. Tomorrow I will see if this will update as the accesses take place. Right now I am after-the-fact creating sessions.)

ASIDE: A key issue with Zoom (LTI external tool activity) is that users will enter in to the course to access the Zoom link and then will wait in the waiting room until the Zoom session starts. Little can be done about this except to place restrictions on the ability to access such to within a time frame that matches the attendance plug-in session time (when the primary accesses are Zoom as opposed to other items in the course).

**Comment by preney** [comment]
I can confirm that the code change appears to work. This morning a class was done (>100 persons) with self-registration + auto marking and it appeared to work properly. :-) 

```
--- auto_mark.php 2021-05-26 01:57:42.962620062 +0000
+++ ../../../attendance.pristine-code/moodle-mod_attendance/classes/task/auto_mark.php  2021-05-26 00:54:02.814620062 +0000
@@ -151,10 +151,10 @@
                     if (empty($log->statusid)) {
                         if ($sessionover || !empty($userfirstaccess[$log->studentid])) {
                             // Status needs updating.
-                            if (!empty($userfirstaccess[$log->studentid])) {
-                                $log->statusid = $att->get_automark_status($userfirstaccess[$log->studentid], $session->id);
-                            } else if ($sessionover) {
+                            if ($sessionover) {
                                 $log->statusid = $setunmarked;
+                            } else if (!empty($userfirstaccess[$log->studentid])) {
+                                $log->statusid = $att->get_automark_status($userfirstaccess[$log->studentid], $session->id);
           } 
                             if (!empty($log->statusid)) {
                                 $log->timetaken = $now;
@@ -182,10 +182,10 @@
                 $added = 0;
                 foreach ($users as $user) {
                     if ($sessionover || !empty($userfirstaccess[$user->id])) {
-      if (!empty($userfirstaccess[$user->id])) {
-                            $newlog->statusid = $att->get_automark_status($userfirstaccess[$user->id], $session->id);
-                        } else if ($sessionover) {
+                        if ($sessionover) {
                             $newlog->statusid = $setunmarked;
+                        } else if (!empty($userfirstaccess[$user->id])) {
+                            $newlog->statusid = $att->get_automark_status($userfirstaccess[$user->id], $session->id);
       } 
                         if (!empty($newlog->statusid)) {
                             $newlog->studentid = $user->id;
```

**Comment by gabrielrodrigodesbesell** [comment]
@preney you managed to solve your presence tagging problem automatically?

**Comment by preney** [comment]
So far so good! I've not had any problems since that fix.

**Comment by gabrielrodrigodesbesell** [comment]
> So far so good! I've not had any problems since that fix.

Understand. 
Here I can't make the student be marked as present automatically as soon as he enters the platform or course, he always needs to click on the presence button, this process I would like to eliminate. Would it be some special parameterization? 
Could you tell me how you parameterize your courses to make this work?

**Comment by preney** [comment]
I am not "automagically" making them present. Originally I wanted to automatically mark things but there are too many issues. Instead (i) I an using the plugin note anyone that has accessed course content within the time period (which it does) and I also have (ii) persons marking their own attendance since item (i) isn't perfect. It is not that hard to "train"/incentivize students to mark their attendance + have something they need to do at the start accessing the web site to also get some auto-marking (because there are always persons that don't mark their attendance) to significantly minimize the number of post-class issues dealing with correcting issues with the attendance.

WRT "automagically" marking things. I am increasingly thinking while things could be done to improve things, ultimately full automarking is not feasible/practical/possible. If one is using Moodle as part of a class, e.g., an in-person class, then students might not even open a browser to Moodle to mark their attendance. If one is using Moodle for remote teaching, then other problems can surface, e.g., I have found that students will open the pages before the class starts (sometimes well before), i.e., they won't be accessing the course during the opening of a course for automarking to work (as is currently implemented). That said, students who are that organized have no issues also marking their own attendance --so they aren't really a problem if one permits students to mark their own attendance.

Another thing I have found useful is to have something students need to do/click on at the very start of the class (with a time restriction on it to prevent them from opening it in advance) to ensure they have clicked on course content at the start of the class for automarking their attendance (if they didn't mark it on their own).

That said, there seems to be one or two persons in sufficiently large classes that were present that didn't mark their attendance and were recorded improperly as absent/late, so I do review the attendance roster after the class if possible when such is possible (e.g., Zoom logs, in person attendance roster sheet). This task is easier and quicker to do if the majority of persons are already correctly recorded (which, in my experience, tends to be the case if one enables both automatic and students recording their own attendance).

**Comment by gabrielrodrigodesbesell** [comment]
> I am not "automagically" making them present. Originally I wanted to automatically mark things but there are too many issues. Instead (i) I an using the plugin note anyone that has accessed course content within the time period (which it does) and I also have (ii) persons marking their own attendance since item (i) isn't perfect. It is not that hard to "train"/incentivize students to mark their attendance + have something they need to do at the start accessing the web site to also get some auto-marking (because there are always persons that don't mark their attendance) to significantly minimize the number of post-class issues dealing with correcting issues with the attendance.
> 
> WRT "automagically" marking things. I am increasingly thinking while things could be done to improve things, ultimately full automarking is not feasible/practical/possible. If one is using Moodle as part of a class, e.g., an in-person class, then students might not even open a browser to Moodle to mark their attendance. If one is using Moodle for remote teaching, then other problems can surface, e.g., I have found that students will open the pages before the class starts (sometimes well before), i.e., they won't be accessing the course during the opening of a course for automarking to work (as is currently implemented). That said, students who are that organized have no issues also marking their own attendance --so they aren't really a problem if one permits students to mark their own attendance.
> 
> Another thing I have found useful is to have something students need to do/click on at the very start of the class (with a time restriction on it to prevent them from opening it in advance) to ensure they have clicked on course content at the start of the class for automarking their attendance (if they didn't mark it on their own).
> 
> That said, there seems to be one or two persons in sufficiently large classes that were present that didn't mark their attendance and were recorded improperly as absent/late, so I do review the attendance roster after the class if possible when such is possible (e.g., Zoom logs, in person attendance roster sheet). This task is easier and quicker to do if the majority of persons are already correctly recorded (which, in my experience, tends to be the case if one enables both automatic and students recording their own attendance).

Right.
I figured that wouldn't be possible. 
Thank you so much for your time and feedback.
