### ISSUE TITLE
Import Sessions do not distinguish different courses

### ISSUE THREAD

**Issue by chandru1782** [danmarsden/moodle-mod_attendance#530]
Hi Team,
Moodle 3.10.4 (Build: 20210510)
mod_attendancce Version: 3.9.1 (2020120300)
block_attendance Version: 3.2.4 (2018052100)

I had to import sessions for various courses and found that if two different courses have classes on same session say 09:00 to 11:00 on 1st June 2021, it shows an error of duplicate session. Further when I changed the session time for one of the course as 09:01 to 11:00 then it adds without any trouble. Please correct it.
Thanks and regards,
Chandrashekaran

**Comment by danmarsden** [comment]
Thanks for the report, 

feel free to help by submitting a pull request with a fix - otherwise I'll put this in the backlog and come back to it sometime.

**Comment by chandru1782** [comment]
Hi, Thank you for the reply. I am a Maths teacher and very much new to
this. However I will try to do something with the code and look for a fix.

Chandrashekaran
