### ISSUE TITLE
Report for Parent Role

### ISSUE THREAD

**Issue by fw-nytra** [danmarsden/moodle-mod_attendance#531]
First of all: Thank you for your plugin, it's an absolutely must have for every moodle installation! 
I am wondering if there is a chance that you build in a right for the parent role ? 
It would be a nice feature for parents to see the attendance of their child. 
I am happy to hear from you.

**Comment by danmarsden** [comment]
I'm pretty sure this is already possible and there are posts in the moodle.org discussions with people who have done this. Can you please do a search on moodle.org and if that doesn't help create a new post in the forums and someone who has done this may give you some tips.
 https://moodle.org/mod/forum/view.php?id=741

Thanks!
