### ISSUE TITLE
Error upgrading Version 3.9.3, Moodle 3.10.5 on MS Sql  

### ISSUE THREAD

**Issue by peverist** [danmarsden/moodle-mod_attendance#538]
**moodle 3.10.5 (Build: 20210712), php 7.2.26, mssql 11.00.7493**

HI - I have just upgraded to Moodle 3.10.5 on a windows stack with MSSQL  and attempted to apply the upgrade of the attendance module from the plugins overview - it indicated the following: 
_There is a new version 2021050702 available!
Release 3.9.3_   

The server checks were all listed as OK but on updating the moodle database I got the following error display

DDL sql execution error

More information about this error

×Debug info: SQLState: 23000<br>
Error Code: 515<br>
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert the value NULL into column 'sessiondetailspos', table 'THEO_TEST.dbo.mdl_attendance'; column does not allow nulls. UPDATE fails.<br>
SQLState: 01000<br>
Error Code: 3621<br>
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated.<br>

ALTER TABLE mdl_attendance ALTER COLUMN sessiondetailspos NVARCHAR(5) COLLATE database_default NOT NULL
Error code: ddlexecuteerror
×Stack trace:
line 492 of \lib\dml\moodle_database.php: ddl_change_structure_exception thrown
line 324 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
line 752 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
line 77 of \lib\ddl\database_manager.php: call to sqlsrv_native_moodle_database->change_database_structure()
line 597 of \lib\ddl\database_manager.php: call to database_manager->execute_sql_arr()
line 634 of \lib\ddl\database_manager.php: call to database_manager->change_field_type()
line 574 of \mod\attendance\db\upgrade.php: call to database_manager->change_field_notnull()
line 871 of \lib\upgradelib.php: call to xmldb_attendance_upgrade()
line 570 of \lib\upgradelib.php: call to upgrade_plugins_modules()
line 1922 of \lib\upgradelib.php: call to upgrade_plugins()
line 713 of \admin\index.php: call to upgrade_noncore()

FYI - the latest H5P update also gave a similar error
 
Phil

**Comment by danmarsden** [comment]
Hi Phil - as per Moodle core, MS Sql support is 100% reliant on community contributions and I don't plan to work on this as a volunteer -  feel free to submit a pull request for review otherwise I'm likely to close this as won't fix.

thanks!

**Comment by JamesH1978** [comment]
We are also getting this, in a 3.9 upgrade, did you ever sort? Thanks

**Comment by danmarsden** [comment]
nope - pull requests welcome.

**Comment by JamesH1978** [comment]
not sure its something that can be PR'ed, the update code is trying to change sessiondetailspos to not allow nulls, but as there are nulls present in the table in that column, it fails out. Is there a reason that column changes to not allow nulls anymore?

**Comment by danmarsden** [comment]
It was an inconsistency between new installs and existing installs - it was supposed to not allow nulls the whole time but the upgrade code that added the sessiondetailspos field was different to the detail in the install.xml file.

Of course - there's always room for rewriting a lot of that and I'm thinking about converting a lot of the functionality to use Moodle's new reportbuilder apis but ... MS SQL support isn't something that overly motivates me to spend any time as a volunteer. :-)

**Comment by danmarsden** [comment]
closing as "won't fix" - as I do not directly support MS SQl myself - although happy to review a PR if anyone decides to fix this for MS Sql.
