### ISSUE TITLE
Error during upgrade to Moodle 3.11.1+

### ISSUE THREAD

**Issue by Richardvi** [danmarsden/moodle-mod_attendance#540]
When trying to update Moodle from 3.9.1 to 3.11.1+ we get the following error in updating attendance:

Installing available updates
Downloading mod_attendance ... OK
Validating mod_attendance ... Error
  [Error] Required Moodle version [2021050400] 
Installation aborted due to validation failure

**Comment by danmarsden** [comment]
That doesn't sound like a bug with attendance to me... the 3.11 version of attendance has the correct version:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/version.php#L27

it requires Moodle version 2021050400 or higher - and 3.11.1+ has this version number: 2021051701.01

I suspect some process you're using to run the upgrade is not getting the right versions of Moodle 3.11 - please use the forums on moodle.org to report the issue you're having including how you are running the upgrade and any screenshots of the process you are using.

thanks!

**Comment by Richardvi** [comment]
I know what the problem is Dan.

When you run a Moodle upgrade, you get the option to install updates for plugins. It will start downloading all the plugin updates for the Moodle version you are upgrading to. But... you are not yet at that version. So updating the plugin will fail.

Some plugins show this behavior, some don't. Probable because of the minimal Moodle requirement.

You can skip the plugin update during the Moodle update proces, run the Moodle update proces and afterwards go to plugins and check for available updates. Now the plugin will install.

This indeed might be seen as a Moodle issue. Thanks for your answer!

**Comment by danmarsden** [comment]
yes - for attendance to work correctly, the site upgrade must be performed first, or at the same time by updating the code in one go.

thanks,
