### ISSUE TITLE
Custom Profile Field Breaks Attendance Module?

### ISSUE THREAD

**Issue by ldh007bucknell** [danmarsden/moodle-mod_attendance#546]
Hi, Folks.

We are running Moodle 3.11.1 with version 3.11.3 of the Attendance module plugin.  

One of the reasons we chose to upgrade to 3.11 was the new possibility of adding a custom profile field to the Particpants list, as a way to display personal pronouns for the students in a course.

We created a custom "text input" profile field called "pronouns," and we populated that field with information from Banner ("she/her/hers," "he/him/his," etc.)  I then modified the setting under Site administration ⇒ Users ⇒ Permissions ⇒ User policies ⇒ Show user identity to select the new "pronouns" field to be displayed.

That worked as designed.  When I went to the Participants list for the course, I could see my new "pronouns" field with its values. 

However, my custom "pronouns" field is causing the dreaded "Error writing to database" error when faculty try to use the Attendance module, specifically, when they click on a session in order to record attendance.  I turned debugging on for my test server, and this is the error I generated when I tried to record attendance for a particular session:

Debug info: Unknown column 'uf1d_1.data' in 'field list'
SELECT u.id, u.email, uf1d_1.data AS profile_field_pronouns, u.picture, u.firstname, u.lastname, u.firstnamephonetic, u.lastnamephonetic, u.middlename, u.alternatename, u.imagealt
FROM mdl_user u
JOIN (SELECT DISTINCT eu1_u.id
FROM mdl_user eu1_u
JOIN mdl_user_enrolments ej1_ue ON ej1_ue.userid = eu1_u.id
JOIN mdl_enrol ej1_e ON (ej1_e.id = ej1_ue.enrolid AND ej1_e.courseid = ?)
JOIN (SELECT DISTINCT userid
FROM mdl_role_assignments
WHERE contextid IN (1,14,1405783,1405809)
AND roleid IN (5,19)
) ra ON ra.userid = eu1_u.id
WHERE 1 = 1 AND eu1_u.deleted = 0 AND eu1_u.id <> ? AND eu1_u.deleted = 0) je ON je.id = u.id
WHERE u.deleted = 0 ORDER BY u.lastname, u.firstname, u.id LIMIT 0, 25
[array (
0 => '40080',
1 => '1',
)]
Error code: dmlreadexception
Stack trace:

    line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 1273 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 1642 of /lib/enrollib.php: call to mysqli_native_moodle_database->get_records_sql()
    line 834 of /mod/attendance/classes/structure.php: call to get_enrolled_users()
    line 370 of /mod/attendance/renderables.php: call to mod_attendance_structure->get_users()
    line 99 of /mod/attendance/take.php: call to attendance_take_data->__construct()

Because "profile_field_pronouns" was mentioned in that error message, I went back to that User Policies setting and *de-selected* my new "pronouns" field, so it won't display in the Participants list.  Voila, the Attendance module is working again when a faculty member tries to record attendance for a session.

I am guessing that when the Attendance module is trying to display the list of students in order to record attendance, it can't handle my custom field, and so it throws out that "error writing to database" error.

Is there any way to *prevent* the Attendance module from trying to display that custom field?  We *really* wanted to be able to display pronouns in the Participants list, but the Attendance module is also frequently used, and we can't just tell people *not* to use it.

**Comment by danmarsden** [comment]
it looks like the core get_enrolled_users function doesn't support custom user profile fields - can you please try changing this line:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/classes/structure.php#L808
to:
```
$userf = \core_user\fields::for_identity($this->context, false)->with_userpic()->including(...$fields);
```
(adds the extra "false" after the context.)

and let me know if that prevents the error you were previously seeing?

thanks,
