### ISSUE TITLE
Additional 'showuseridentity' fields defined in Moodle don't work and cause notices

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-mod_attendance#547]
To reproduce...

Site admin > Users > Permissions > User policies
Add options to the 'Show user identities field'. I used 'username' and 'idnumber'
Go to an attendance instance and show the report page
Headings for these fields appear as expected but the columns are empty. Notices are thrown...

Notice: Undefined property: stdClass::$idnumber in /var/www/html/moodle311/mod/attendance/renderer.php on line 2194

This used to work in earlier versions of Moodle and/or the plugin

$plugin->version = 2021062901
Moodle 3.11.1

**Comment by danmarsden** [comment]
Thanks Howard - will likely be something related to the new userfieldsapi -  I'll take a look asap.

**Comment by danmarsden** [comment]
yeah - probably the wrong api in use within attendance - get_name_fields instead of get_identity_fields

**Comment by danmarsden** [comment]
ah - nope - I fixed this in 8d2841 and pushed out version 3.11.2 - if you upgrade it should be sorted.

**Comment by thepurpleblob** [comment]
Upgraded to latest and happy to confirm that fixes it. Cheers.
