### ISSUE TITLE
Follow-Up on Issue #546 - Custom Profile Field Ignored, But Title Displayed in Title Row

### ISSUE THREAD

**Issue by ldh007bucknell** [danmarsden/moodle-mod_attendance#548]
Thank you for resolving the problem with custom profile fields causing a failure in the Attendance Module.  Now, the Attendance Module allows you to record attendance (even with a custom profile field), but it lists the name of the field in square brackets at the top of the screen where you record attendance and at the top of the Reports screen as well.  That field title display is confusing to faculty users.  I wonder if there is a way to prevent that title from displaying.  
![Attendance_custom_profile_field_displays_taking_attendance](https://user-images.githubusercontent.com/36862887/129903935-2d60f561-b52e-47e4-8e00-8aa6c9128127.png)
![Attendance_custom_profile_field_view_Report_screen](https://user-images.githubusercontent.com/36862887/129903956-11e9fcc5-3b30-42d4-8c32-c1fb45dc7f2e.png)

**Comment by danmarsden** [comment]
thanks yeah - I saw that in the header too - I wanted to get the quick fix out so the page at least displays for now - pull requests welcome :-)

**Comment by vicden** [comment]
We are seeing this issue as well.

**Comment by mackensen** [comment]
In addition, it doesn't display the custom profile field if it has data in it.
