### ISSUE TITLE
Add API method for retreiving Attendance instances in course

### ISSUE THREAD

**Issue by pete1854** [danmarsden/moodle-mod_attendance#549]
Hi,
Many of the existing API methods pertaining to the Attendance plugin relies on Attendace instance ID:s to be submitted with the request. Currently there seems to be no method in the API for getting the Attendance instance ID:s in the first place, thus making it difficult to use available methods for e.g. adding new sessions to an existing Attendance instance.
Kind regards,
Peter

**Comment by danmarsden** [comment]
I'm not convinced it makes sense to add something that specific to the attendance activity - you'd be better to use some of the core webservices in the core_course externallib like get_course_contents - but Pull requests always welcome.
