### ISSUE TITLE
Maximum Grade point is posting to grade book than the actual depends the attendance

### ISSUE THREAD

**Issue by jasimp** [danmarsden/moodle-mod_attendance#550]
Hello all
I need help on above issue
Ihe  details mentioned  [here](https://moodle.org/mod/forum/discuss.php?d=425918) if it showing below

I created the attendance for a online session and only one activity there which is a non graded item page. and the other one attendance.

I set the maximum grade as 12 and the attendee will get 10.5 point if they attended and absent is zero

But the attendee getting the maximum grade of 12 in their grade book instead of 10.5

The points appearing correctly in the this course area but its showing 12 in grade book

Am i doing some thing wrong in the setting? 

Moodle 3.10.6

And attendance plug in version : 3.9.3 (2021050702)

**Grade book total** 

![image](https://user-images.githubusercontent.com/7235269/130354067-487d2778-ada2-45cf-b6a8-6a2fe05d3b0d.png)

![image](https://user-images.githubusercontent.com/7235269/130354059-23a82192-d661-49ad-9975-f31b024be0e9.png)

**Grade setting on attendance setting**

![image](https://user-images.githubusercontent.com/7235269/130354039-3168d2a7-b798-4fbd-8472-a7406091c066.png)

![image](https://moodle.org/pluginfile.php/185/mod_forum/post/1714985/image%20%283%29.png)

![image](https://user-images.githubusercontent.com/7235269/130354023-b3082d57-2697-490e-b89c-05141e825df0.png)

----------------------------------------------

![image](https://user-images.githubusercontent.com/7235269/130354012-8a3f0a20-123c-482f-9030-f5259a167848.png)

**Comment by danmarsden** [comment]
Please use the forums for support questions: https://moodle.org/mod/forum/discuss.php?d=425918#p1715105 - thanks.
