### ISSUE TITLE
Error adding session via API

### ISSUE THREAD

**Issue by pete1854** [danmarsden/moodle-mod_attendance#551]
Hi,

If I call:

`wstoken=...&wsfunction=mod_attendance_add_session&moodlewsrestformat=json&attendanceid=866&groupid=124&sessiontime=1629896400&duration=10800&description=Kurstillf%C3%A4lle&addcalendarevent=1`

I get the following error:
`content = '{"exception":"dml_missing_record_exception","errorcode":"invalidrecordunknown","message":"Cannot find record in database."}'`

The attendance instance and group exists in the course.

What is wrong?

Kind regards,
Peter

**Comment by danmarsden** [comment]
not sure sorry -  I'd need to look at your code and site to see what might be going wrong - and thats typically the sort of thing I wouldn't do for free.

the webservice functions are covererd by unit tests in tests/externallib_test.php - you might see a few hints in there.

**Comment by danmarsden** [comment]
if you find out there's a bug - feel free to create a report with detailed replication instructions and I can add it to the backlog of things to look at.
