### ISSUE TITLE
custom session fields

### ISSUE THREAD

**Issue by MikeAndMary** [danmarsden/moodle-mod_attendance#556]
Hi, first of all, thanks for this module.
I would like to ask, if there is a possibility to add a few features in the near future.
I would need some more or some customized fields for the lesson event to fill out and extract, like: the following
:Place, Teacher,,     Duration (hours), Kind,      Course Type,       Course Mode
Rome, M. Draghi,  3,                          Update, Specific product, Presence

The last three could be dropdowns with a few values (like the status (present, excused, absent)

Also, the exported data should be with the course name in the row, not grouped by course
I only need records with confirmed presence, so I don't need the columns:
P	R	A	Lezioni registrate	Punteggio	Percentuale
Please see the attached example of the data I would need.
[PROVA REPORT IVASS.xlsx](https://github.com/danmarsden/moodle-mod_attendance/files/7138345/PROVA.REPORT.IVASS.xlsx)
Thanks for your kind attention,
Michael

**Comment by danmarsden** [comment]
Hi there - great to hear you find it useful! - typically feature development is something I struggle to find time to do as a volunteer - (it's hard enough keeping on top of support for new versions across all the plugins I support!) - If you have internal development capabilities, pull requests are always welcome - alternatively if you would like to fund feature development feel free to get in touch privately and I can provide information on our rates (I work for the Moodle Partner Catalyst IT)

thanks,

**Comment by MikeAndMary** [comment]
Hi Dan,

thanks for your kind reply.
Perhaps, meanwhile I could have access to the data model or  is there a way to collect the generated sql statements used on exporting ? Perhaps I can use it to simplify implementing a query in the report “Ad-hoc database queries”.

I wish you a great day,
Michael

**Comment by danmarsden** [comment]
Moodle plugins all define their data-model in the db/install.xml files - if you need help understanding them or writing a new sql query the best place to ask for this help is in the community forums on moodle.org - thanks!

**Comment by MikeAndMary** [comment]
Ok, thanks for that hint, I can read the file install.xml – although that doesn’t help to take out much of the gessing work for the joius.
Will you just help me again by telling me if there is a way to get the teachers name out of it, something like the “owner” of the session, the one who created the lesson event ?

Many thanks, I wouldn’t bother you again 😊,
Michael

**Comment by danmarsden** [comment]
If you search the moodle.org community forums for sql schema there are a few things that should come up - but most things are named in a way you would expect - eg a "userid" field refers to a table called "user" and matches against the id field - best place to ask these sorts of questions (and to get a quick response) is the community forums - lots more people, different timezones etc... :-)
