### ISSUE TITLE
Cannot update user status

### ISSUE THREAD

**Issue by pete1854** [danmarsden/moodle-mod_attendance#557]
Hi!

I'm trying to update a user status for a session through the API using the following POST request:

`https://{{Server}}?wstoken={{ServiceKey}}&wsfunction=mod_attendance_update_user_status&moodlewsrestformat=json&sessionid=1073&studentid=16000&takenbyid=17558&statusid=906&statusset=0`

When I post the request I get an invalid_parameter_exception - invalidparameter

I suspect that it is the "statusset" parameter that's wrong. How do I format this parameter to have the plugin accept it? If I look in the code, this request parameter seems to be a string, but, in subsequent code it is treated as an int. I therefore first assumed that I should provide the param in the form of a string containing all potential statuses for the session, the "status set" (e.g. "905,906"). But looking more closely into the code it seems tha I should provide the ID of a statusset for the session, e.g. 0. I've tried both approaches, but still get the above error.

The provided **sessionid** is a valid session. The **studentid** an enrolled student in the course. The **takenbyid** is a techer in the course and finally, the **statusid** is the ID of one of the available statuses in the session and session set (0).

Kind regards,
Peter

**Comment by pete1854** [comment]
I checked the update_user_status_parameters() function in externallib.php and it seems it requires the statusset parameter to be a string, whilst subsequent use of the parameter expects an integer. Is this correct?

**Comment by danmarsden** [comment]
This might give you a few pointers:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/tests/externallib_test.php#L212

I haven't used that function myself, and wouldn't be surprised if it was buggy.

**Comment by danmarsden** [comment]
not sure if this is still an issue, but as it relates to external integration I'm flagging as closed - feel free to submit a PR if you think the webservices api in the attendance plugin can be improved!
