### ISSUE TITLE
First row header sticky

### ISSUE THREAD

**Issue by demontech** [danmarsden/moodle-mod_attendance#559]
Hi Dan,

Is it possible to make the first row of the table "sticky" where the statuses are on the taking attendance table? 

The reason is that we have 5 - 6 statuses and our courses and 30-40 students per course. Instructors would like to see the statuses while scrolling down when are taking attendance.

Thank you!

**Comment by danmarsden** [comment]
anything is possible - pull requests are always welcome :-)

I have been wanting to completely rebuild the marking pages - possibly using something like Moodle 4.0's new reportbuilder api - although it's likely that will need someone to fund the development - also keep in mind you can switch to using the "grid" view on the marking page and you could use some css to hide the user profile images (or make them smaller) if needed.

**Comment by demontech** [comment]
Excellent good to know

Thanks Dan!
