### ISSUE TITLE
[Q&A] Is there a way to mark attendance through API

### ISSUE THREAD

**Issue by maxkoshevoi** [danmarsden/moodle-mod_attendance#565]
Hi, I'm a student at university that uses this extension on [it's Moodle site](https://dl.nure.ua/?lang=en). 
I've also built [a timetable app](https://play.google.com/store/apps/details?id=com.whitebox.nuretimetable) that is used by pretty match every student.

I'm working on Moodle integration (currently timetable info it received from elsewhere), and as part of it I'd like to have an ability to mark attendance from within the app.

I've already figured out a way to get a token `https://dl.nure.ua/login/token.php`, and to execute some Moodle api method `https://dl.nure.ua/webservice/rest/server.php?moodlewsrestformat=json&wsfunction=core_enrol_get_users_courses`.

Is there a way to interact with this plugin via Moodle api?

**Update**: It seems like `mod_attendance_update_user_status` should do the trick, but I'm not fully understand, how to use it.
- What is `statusid` and `statusset`? What are their value if there're no radio buttons to choose from when I'm marking attendance (just click on `mark attendance` and that's it)?
- Can I do it with api token, instead of session id? I have an api token, student id, and course id. What else do I need and how to get it? If there's a wikim or some sample requests, I would really appreciate it

**Comment by danmarsden** [comment]
Sounds like a cool project! - if you install Moodle with a copy of the Attendance plugin you can access the web services documentation within your Moodle installation under Administration > Plugins > Web services > API Documentation. 

The attendance plugin contains a number of webservices built-in to help with this sort of integration - make sure your Moodle site has the attendance plugin installed and you'll see a list of the attendance webservices on that page.

In future - the best place to ask these sorts of questions is in the moodle.org community forums (this isn't really a support channel, rather a place to report bugs.)

Good luck!
