### ISSUE TITLE
About Totals for selected sessions Table

### ISSUE THREAD

**Issue by yakarsu** [danmarsden/moodle-mod_attendance#566]
Hello Dan,

A student attendance report has 4 times the present score, but it appears twice as high in the Totals for selected sessions table

![attendances](https://user-images.githubusercontent.com/49027250/138087853-9097ecfa-1661-4385-a218-9977fc897bdc.png)

**Comment by danmarsden** [comment]
I think you'd need to check the DB tables and do some investigation on that yourself - I don't remember seeing this before and I'd need to have more detailed reproduction information to try and diagnose it myself.

If you manage to dig out more info or work out what is going on there please post any updates here!

**Comment by yakarsu** [comment]
Hello Dan thanks for your answer. I will check Db.

**Comment by sleitao** [comment]
We have exactly the same issue. I think the glitch may be on group by sessions.... because If i change the "group by" visualisation for "Week" I get the right totals... 

Attendance v3.9.3 (2021050702)
Moodle 3.9 PostgreSQL

**Comment by sleitao** [comment]
Hi,
About reproducing the issue:

1. Create a new Attendance activity
2. Add a session
4. On "Status set" set update to 1 point on "Present" (P)
5. On "Sessions" click the triangle "Take attendance" and set Present (P) for a student 
6. On "Report" click the name of that student ando access "All Sessions"
7. You will get "2" on "Totals for selected sessions" item "Present:" if you use filters "Group sessions by:" "Attendance instance" or "Course". If you select "Week" you get "1".

Thank you.
