### ISSUE TITLE
No reminders arrive with local_reminders

### ISSUE THREAD

**Issue by MikeAndMary** [danmarsden/moodle-mod_attendance#567]
Hi,

I added the plugin local_reminders to invite students because teachers decide who should attend the lessions.
When I create a course event in the calendar then the adressed group members all receive an email, but when the event is created by the plugin mod_attendance, no email is sent and I wonder what the reason is for such behavior.
Perhaps it needs to be fixed in mod_attendance.
https://moodle.org/plugins/local_reminders
I am using moodle 3.11 and the latest versions of the plugins.

**Comment by danmarsden** [comment]
HI there - I don't use the local_reminders plugin and attendance uses Moodle's core calendar API to manage events - this isn't something I'd look into myself as a volunteer, but if you do some further investigation and find a bug in the attendance code I'm happy to review a pull request. I'm closing this for now as there isn't enough information provided to suggest that an issue actually exists in the attendance codebase.

If you don't have internal development capabilities you could try engaging a Moodle partner to help or you could also ask in the Moodle forums to see if anyone else has looked at this.

thanks!
