### ISSUE TITLE
/mod/attendance/messageselect.php - error [[messagedselecteduserfailed]]

### ISSUE THREAD

**Issue by reduva** [danmarsden/moodle-mod_attendance#568]
Hello,

in reports after selecting the user and writing a message. When you click send e-mail, the error appears.  

email run normally on the platform with other modules

[[messagedselecteduserfailed]]
![image](https://user-images.githubusercontent.com/93044922/141170409-14e015a9-bc79-45af-a52b-53fa0840c5cd.png)
![image](https://user-images.githubusercontent.com/93044922/141170526-2c1640f3-848c-40c5-8f71-d3502b1e52fc.png)

**Comment by danmarsden** [comment]
Thanks for the report - that's happening becuase the moodle api is returning an error when trying to send to the user - if you turn debugging on you might see more info..

but... the missing string is definitely a bug - I'll see if I can add add that at some point.

**Comment by reduva** [comment]
thanks for the answer, i'll do analysis


![image](https://user-images.githubusercontent.com/93044922/141344033-967fd4cd-0d25-412f-91ec-869695f5c683.png)

**Comment by krostas1983** [comment]
Sending the message fails in case messaging is disabled sitewide. Fallback to mail seems to be a thing of the past as well?

The language strings in question have been deprecated with Moodle 3.6:
https://github.com/moodle/moodle/commit/dc4dea0e40946d4d95fa6fd2bde91930674205e6
... and have been removed since.

**Comment by danmarsden** [comment]
@krostas1983 feel free to report a new issue - this is a closed issue that fixed a different thing (related to messaging) - pull requests or funding for improvements are always welcome too! :-)
