### ISSUE TITLE
How to make an automatic presence for the student just entering the course

### ISSUE THREAD

**Issue by gabrielrodrigodesbesell** [danmarsden/moodle-mod_attendance#569]
@danmarsden como é possível marcar a presença do aluno automaticamente assim que ele acessar o curso? Notei que tem o arquivo auto_mark.php porém ele não está se comportando de maneira correta ou está faltando parametrizar corretamente do meu lado, alguma sugestão?

moodle version: 3.8.1
mod_attendance: 3.9.1

**Comment by danmarsden** [comment]
HI there - the best place to ask these sorts of "how do I" questions is the community forums on moodle.org:
https://moodle.org/mod/forum/view.php?id=741
Also see #529 where some people have reported some issues while using the auto mark feature - it works for some people but not others.

thanks.
