### ISSUE TITLE
Remarks : 256 characters limit, can we make it configurable ?

### ISSUE THREAD

**Issue by imchetanvij** [danmarsden/moodle-mod_attendance#572]
**Request**: If there is a way ( configurable ) to increase the limit of characters that the teacher can write in Teacher Notes while taking attendance, it would be awesome.
If we can not make it configurable, is there a way I can increase it ?

I am also Using Attendance module as a way to write Monthly Student Progress Review Report.
The Status Set being : Green, Orange, Red and the Teacher Notes column capturing the details of qualitative feedback from the teacher.

**Comment by danmarsden** [comment]
Hi there - it's currently limited by the database field in use:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/db/install.xml#L76

Happy to consider increasing this in future. If you have internal development capabilities, pull requests are always welcome.

If you want help modifying your own Moodle installation to modify the limit - best place to ask for further free help is in the community forums on moodle.org.

**Comment by imchetanvij** [comment]
:) Thank you @danmarsden ... Will seek inputs from the forums.

Meanwhile, a huge thanks for this awesome module. This has been the most useful one for me and my team.
1. It has helped us drive consistent course delivery across our centres. Specially helpful in online teaching.
2. We have creatively used Status Sets to monitor the pace of delivery and progress of the students.

Thanks again!!
