### ISSUE TITLE
Moodle 3.9 compatibility issue

### ISSUE THREAD

**Issue by davosmith** [danmarsden/moodle-mod_attendance#573]
The change #525 introduced the defined value PROFILE_VISIBLE_TEACHERS into the code.

This is only available in Moodle 3.11 and above, but the version of mod_attendance listed in the Moodle plugins directory for M3.9 / M3.10 has this line of code included, which causes a debugging warning when running an export in Moodle 3.9.

I'm going to patch the code locally to remove it for our customer, but I thought you might want to know in order to fix the published version.

**Comment by danmarsden** [comment]
thanks! - I've reverted that in the branch that supports 3.9 here too.
