### ISSUE TITLE
Problems when tracking Attendance 

### ISSUE THREAD

**Issue by MrPhleeep** [danmarsden/moodle-mod_attendance#575]
We are having an issue while grading Attendance.
While grading attendance the grades are calculated by attendance to date and not by overall attendance. 
I found a Disscusion in the Moodle Forums discussing the same issue, see link below
https://moodle.org/mod/forum/discuss.php?d=427527

Philippe

**Comment by danmarsden** [comment]
Hi there, it sounds like what you are looking for is covered in #251 - there's a decent chunk of work involved in getting that right an it's unlikely I'd spend any time as a volunteer on it, but pull requests are always welcome.

If you'd like to look at funding the development required to implement this, feel free to reach out privately to discuss the details.

thanks!
