### ISSUE TITLE
QR Code rotation / expiry time out is incorrect

### ISSUE THREAD

**Issue by alaashaheen1** [danmarsden/moodle-mod_attendance#579]
Hi

In the Attendance plugin settings, the password interval is set to 30 sec. and the password expiry is set to 30 sec too. even though the QR code shows 100 sec at the begining then it shows the 30 sec. see attached images for more info.

could anyone explain why it shows 100 sec  ?

Thank
![2](https://user-images.githubusercontent.com/101625811/158328626-72408103-5b31-4bed-b145-1d072182baf2.png)
![1](https://user-images.githubusercontent.com/101625811/158328628-45a9056a-c568-4338-8c33-943c9d64c11f.png)

**Comment by alaashaheen1** [comment]
I discovered the root cause of the issue. it is the time difference between the Moodle server and the client that shows the QR code

**Comment by danmarsden** [comment]
nice work!
