### ISSUE TITLE
Activity description displaying twice in 4.0

### ISSUE THREAD

**Issue by emmarichardson** [danmarsden/moodle-mod_attendance#580]
In 4.0 the activity description is displaying twice on the Activity page.  Also, I tend to think that part of the top should not go to full screen...see attached screenshot...
<img width="809" alt="Screen Shot 2022-04-05 at 11 52 39 AM" src="https://user-images.githubusercontent.com/2079129/161819167-eee525b4-ad1b-44e7-b9c8-d21fb1556c3d.png">

**Comment by emmarichardson** [comment]
In looking at other activities, I see that forums also expands the grey section (with Mark as Done) button so I guess that is consistent but the description only shows up in the grey area and not again in the activity part.

**Comment by danmarsden** [comment]
Thanks Emma, that should be fixed now for attendance - although I think we need to improve the display of the header a bit on some pages which I'll work on too.
