### ISSUE TITLE
Backup restore can potentially delete calendar events that it shouldn't

### ISSUE THREAD

**Issue by cameron1729** [danmarsden/moodle-mod_attendance#581]
#517 introduced an upgrade step and a backup restore step that clean up orphaned calendar events.

The SQL is:

`"modulename = 'attendance' AND courseid = :courseid AND id NOT IN (SELECT caleventid
                                                                                        FROM {attendance_sessions}
                                                                                       WHERE attendanceid = :attendanceid)"`

Assume there are two attendance instances in the backup: `a` and `b`, when the SQL runs for instance `a` the `NOT IN` subquery finds only `a`'s caleventids and not `b`'s, however the main query includes all calendar events (i.e., events associated with `a` and `b`), so `b`'s events get deleted.

The same then happens when the SQL runs for `b` (it deletes `a`'s events).

The upgrade doesn't suffer from this problem as it has no `WHERE` clause in the subquery. I think the fix should be to make the two queries the same.

**Comment by danmarsden** [comment]
thanks - nice catch! - pushed a fix into the supported branches for 3.9 and higher.
