### ISSUE TITLE
Cross-domain CORS issue

### ISSUE THREAD

**Issue by WajdiBf** [danmarsden/moodle-mod_attendance#582]
Hey

I am facing the issue of CORS in moodle. I have shared the moodle session with another external web app (cross-domain cookies ).

and what I'm trying to do is to check session status via a custom API using Axios with  "withCredentials: true" params to send the cookie with a request

But unfortunately, i got blocked by moodle 
'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

Any help would be appreciated.

**Comment by danmarsden** [comment]
This doesn't appear to have anything to do with the attendance plugin which is what this issues tracker is for. Best place to ask for free help with moodle is the community forums on moodle.org - I see you've created a post there already. Thanks!
