### ISSUE TITLE
Failing Behat tests in Moodle 4.0

### ISSUE THREAD

**Issue by dragos5436** [danmarsden/moodle-mod_attendance#585]
Hi,

There are a few Behat tests failing for this plugin:

1. var/www/html/mod/attendance/tests/behat/attendance_mod.feature:41
   Feature: Teachers and Students can record session attendance
   Scenario: Students can mark their own attendance and teacher can hide specific status from students
```
And I follow "Administration": Link matching locator "Administration" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

2. var/www/html/mod/attendance/tests/behat/attendance_mod.feature:75
   Feature: Teachers and Students can record session attendance
   Scenario: Teachers can view below % report and send a message
```
And I follow "Administration": Link matching locator "Administration" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

3. var/www/html/mod/attendance/tests/behat/attendance_mod.feature:95
   Feature: Teachers and Students can record session attendance
   Scenario: Export report includes id number, department and institution
```
And I follow "Administration": Link matching locator "Administration" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

4. var/www/html/mod/attendance/tests/behat/attendance_mod.feature:114
   Feature: Teachers and Students can record session attendance
   Scenario: Test enabling custom user profile field
```
And I follow "Administration": Link matching locator "Administration" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

5. var/www/html/mod/attendance/tests/behat/attendance_mod.feature:129
   Feature: Teachers and Students can record session attendance
   Scenario: Test adding custom user profile
```
And I follow "Administration": Link matching locator "Administration" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

6. var/www/html/mod/attendance/tests/behat/calendar_features.feature:24
   Feature: Test the calendar related features in the attendance module
   Scenario: Calendar events can be created automatically with sessions creation
```
Given the following "courses" exist:: Could not open connection: Process unexpectedly closed with status 0
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '9b253a7bf912', ip: '192.168.48.5', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.62.1.el7.x86_64', java.version: '1.8.0_292'
Driver info: driver.version: unknown
remote stacktrace:  (Behat\Mink\Exception\DriverException)
```

7. var/www/html/mod/attendance/tests/behat/defaultstatus.feature:23
   Feature: Admin can set default status set for use in new attendance
   Scenario: Modified default status set added to new attendance
```
And I set the field with xpath "//*[@id='preferencesform']/table/tbody/tr[2]/td[3]/input" to "customstatusdescription": Xpath matching locator "//*[@id='preferencesform']/table/tbody/tr[2]/td[3]/input" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

8. var/www/html/mod/attendance/tests/behat/extra_features.feature:71
   Feature: Test the various new features in the attendance module
   Scenario: A teacher can take attendance for temporary users
```
And I follow "Report": The "(//html/.//a
[./@href][((./@id = 'Report' or contains(normalize-space(string(.)), 'Report') or contains(./@title, 'Report') or contains(./@rel, 'Report')) or .//*[(contains(concat(' ', @class, ' '), ' icon ') or self::img) and (contains(./@alt, 'Report') or contains(./@title, 'Report'))])] | //html/.//*
[translate(./@role, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz') = 'link'][((./@id = 'Report' or contains(./@value, 'Report')) or contains(./@title, 'Report') or contains(normalize-space(string(.)), 'Report'))])[1]" xpath node is not visible and it should be visible (Behat\Mink\Exception\ExpectationException)
```

9. var/www/html/mod/attendance/tests/behat/extra_features.feature:155
   Feature: Test the various new features in the attendance module
   Scenario: A teacher can create and use multiple status lists
```
And I set the field with xpath "//*[@id='preferencesform']/table/tbody/tr[1]/td[2]/input" to "G": Xpath matching locator "//*[@id='preferencesform']/table/tbody/tr[1]/td[2]/input" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

10. var/www/html/mod/attendance/tests/behat/extra_features.feature:203
   Feature: Test the various new features in the attendance module
   Scenario: A teacher can use the radio buttons to set attendance values for all users
```
And I follow "Report": The "(//html/.//a
[./@href][((./@id = 'Report' or contains(normalize-space(string(.)), 'Report') or contains(./@title, 'Report') or contains(./@rel, 'Report')) or .//*[(contains(concat(' ', @class, ' '), ' icon ') or self::img) and (contains(./@alt, 'Report') or contains(./@title, 'Report'))])] | //html/.//*
[translate(./@role, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz') = 'link'][((./@id = 'Report' or contains(./@value, 'Report')) or contains(./@title, 'Report') or contains(normalize-space(string(.)), 'Report'))])[1]" xpath node is not visible and it should be visible (Behat\Mink\Exception\ExpectationException)
```

11. var/www/html/mod/attendance/tests/behat/extra_features.feature:219
   Feature: Test the various new features in the attendance module
   Scenario: A teacher can use the radio buttons to set attendance values for unselected users
```
Given the following "courses" exist:: Short name is already used for another course (C1) (moodle_exception)
```

12. var/www/html/mod/attendance/tests/behat/preferences.feature:27
   Feature: Teachers can't change status variables to have empty acronyms or descriptions
   Scenario: Teachers can add status variables
```
And I set the field with xpath "//*[@id='preferencesform']/table/tbody/tr[2]/td[2]/input" to "": Xpath matching locator "//*[@id='preferencesform']/table/tbody/tr[2]/td[2]/input" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

13. var/www/html/mod/attendance/tests/behat/report.feature:39
   Feature: Visiting reports
   Scenario: Teacher takes attendance
```
And I navigate to "Edit settings" in current page administration: Link "Edit settings" in the current page edit menu" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

14. var/www/html/mod/attendance/tests/behat/report.feature:71
   Feature: Visiting reports
   Scenario: Teacher take attendance of group session
```
And I navigate to "Edit settings" in current page administration: Link "Edit settings" in the current page edit menu" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

15. var/www/html/mod/attendance/tests/behat/report.feature:116
   Feature: Visiting reports
   Scenario: Teacher visit summary report and absentee report
```
And I navigate to "Edit settings" in current page administration: Link "Edit settings" in the current page edit menu" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

16. var/www/html/mod/attendance/tests/behat/report.feature:161
   Feature: Visiting reports
   Scenario: Student visit user report
```
And I navigate to "Edit settings" in current page administration: Link "Edit settings" in the current page edit menu" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

MySQL 5.7
PHP 7.4
Moodle latest MOODLE_400_STABLE
executed with moodlehq/moodle-docker

**Comment by danmarsden** [comment]
That code looks old. Behat tests are passing here in github too. Please make sure you are using the latest/correct branch.

**Comment by danmarsden** [comment]
closing this - looks like you are running an older branch of the attendance plugin (MOODLE_311_STABLE or MOODLE_38_STABLE) instead of the correct code for Moodle 4.0 in the MOODLE_400_STABLE branch here in github.
