### ISSUE TITLE
missingparam error when clicking date in calendar as a student enrolled on course

### ISSUE THREAD

**Issue by craigbailie** [danmarsden/moodle-mod_attendance#586]
- Create a course with an attendance module
- Enrol a user on the course as a student
- Create a number of sessions within the attendance module
- Login as the student enrolled on the course and open the attendance module
- Select the 'This course' tab and then ensure that 'Months' is selected
- Click on the month nav option e.g. 'May' to reveal the calendar
- Click on a date in the calendar - this results in a missingparam error

`A required parameter (sesskey) was missing

[More information about this error](https://docs.moodle.org/39/en/error/moodle/missingparam)

×Debug info:
Error code: missingparam
×Stack trace:
line 498 of /lib/setuplib.php: moodle_exception thrown
line 566 of /lib/moodlelib.php: call to print_error()
line 73 of /lib/sessionlib.php: call to required_param()
line 124 of /mod/attendance/view.php: call to confirm_sesskey()`

**Comment by danmarsden** [comment]
thanks for the report - I've just pushed a fix into github to all supported releases that should fix this - next time the plugin is published to the plugins db it will include this fix.

thanks!
