### ISSUE TITLE
The 'Today' option on the attendance calendar doesn't appear to work

### ISSUE THREAD

**Issue by craigbailie** [danmarsden/moodle-mod_attendance#587]
- Create a course with an attendance module
- Create a number of sessions within the attendance module across multiple past and future days
- In the sessions tab select 'Days'
- Click on the date to reveal the calendar and select yesterday
- The session details for yesterday are shown
- Click on the date to reveal the calendar again and click the 'Today' button at the bottom of the calendar - the sessions aren't refreshed to show the sessions for today

**Comment by danmarsden** [comment]
Thanks for the report - that's some really old YUI code from a very long time ago, I'd be surprised it if ever worked and you're just the first to notice! :-) 

I've just removed the "today" button from the interface in the supported branches - eventually that component will need to be replaced with some more modern JS too!
