### ISSUE TITLE
`invalid_response_exception` from `get_session` and `get_sessions` WS functions

### ISSUE THREAD

**Issue by tjefferson08** [danmarsden/moodle-mod_attendance#589]
## Summary
When sessions use rich text for their description field, the WS functions `get_session` and `get_sessions` both fail to parse between PHP `text` and `string` types.

## Session description UI
![image](https://user-images.githubusercontent.com/3535390/169065497-6af8191c-bd48-4a22-b57d-3e9ad039cdc3.png)

## WS Error Response
```json
{"exception":"invalid_response_exception","errorcode":"invalidresponse","message":"Invalid response value detected","debuginfo":"description => Invalid response value detected: Invalid external api response: the value is \"<strong>hi<\/strong>\" of PHP type \"string\", the server was expecting \"text\" type"}
```

## Workaround
If you use the "advanced" section of the HTML editor, you can input a raw text description as "code". This alleviates the typecasting issue
![image](https://user-images.githubusercontent.com/3535390/169065240-ac15fd26-1462-40cc-8216-6df15a03f0ab.png)

## Environment info
Example/screenshots from moodle 4.0.1 and moodle-mod_attendance 4.0.1, but this issue exists in every version combination I've tested (several in the 3.x range)

**Comment by danmarsden** [comment]
thanks for the report - I've just pushed a fix for this into the supported branches here in github for this. Next time I push out a version to the moodle.org plugins db it will be included there as well.

thanks!

**Comment by tjefferson08** [comment]
Thanks for the quick fix! I'll look forward to the updated release 🥇
