### ISSUE TITLE
plugin installation made moodle crashes

### ISSUE THREAD

**Issue by sachi842** [danmarsden/moodle-mod_attendance#592]
After plugin installation in my moodle 4.0 in local host with xampp with the following config:

PHP 8.0.19 (cli) (built: May 10 2022 08:46:29) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.19, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.19, Copyright (c), by Zend Technologies

windows 11

**Comment by danmarsden** [comment]
thanks for the report - I haven't tested this plugin on PHP 8.0 yet, and I'd like to point out that Moodle 4.0 also does not officially support PHP 8.0 yet either:
https://docs.moodle.org/dev/Moodle_4.0_release_notes#Server_requirements

your report doesn't really provide enough information that would allow me to diagnose either so I'm going to close this but will open an issue for PHP 8.0 support.

If you have internal development capabilities, feel free to help by submitting a PR with any PHP 8.0 improvements.

thanks,

**Comment by sachi842** [comment]
Hello, thank you for your response,

What version of php do you recomend me to install in order to make it work
in moodle 4.0
?

**Comment by danmarsden** [comment]
The link I posted earlier shows the server requirements for Moodle 4.0 - the best place to ask for free help with installing moodle is the community forums on moodle.org.

**Comment by sachi842** [comment]
Could you please tell me what the latest version of php you have tested
this plugin?

I installed xampp with php 7.4.29 and moodle and worked well but, when
installing the Attendance plugin, It show the same error I reported
previously

**Comment by danmarsden** [comment]
you didn't include any information on the specific error - all you did was report "it crashes" - the best place to ask for help with installing plugins / general Moodle help is the moodle.org community forums here:
https://moodle.org/mod/forum/view.php?id=28

Please create a forum post there and post more information on the crash / screenshots / what error is reported etc, - also see 
the "troubleshooting" section in the plugin install docs here:
https://docs.moodle.org/en/Installing_plugins
