### ISSUE TITLE
Error when submitting attendance form (by teacher)

### ISSUE THREAD

**Issue by comete-upo** [danmarsden/moodle-mod_attendance#60]
Hello,

In debug mode, this error is displaying when submitting attendance form (by teacher) :

Argument $record must be an instance of stdClass.

    line 784 of /lib/classes/event/base.php: call to debugging()
    line 970 of /mod/attendance/locallib.php: call to core\event\base->add_record_snapshot()
    line 56 of /mod/attendance/take.php: call to attendance->take_from_form_data()

However, it seems to work ...

*Dan Marsden said :

Thanks Pascal - probably a bit of a restructure of the attendance class needed in  attendance/locallib.php to remove that warning - feel free to add an issue in github here*

**Comment by danmarsden** [comment]
this should be fixed with all the recent updates - let me know if there is still an issue with the latest code available in git.
