### ISSUE TITLE
Error while trying to access the module in Moodle 4 with PHP 8

### ISSUE THREAD

**Issue by ghost** [danmarsden/moodle-mod_attendance#602]
Exception - array_key_exists(): Argument #2 ($array) must be of type array, stdClass given

![image](https://user-images.githubusercontent.com/6366787/177762809-bfc1ccea-92d3-47ab-8f5d-9a58bd7d6cf9.png)

**Comment by danmarsden** [comment]
can you please confirm you have the latest version of the attendance plugin for Moodle 4? - I can't reproduce this with PHP 8.0 (I also have automated tests running on php 8.0 in this repository which are passing.)

Can you also set your debugging level to "developer" and then reload the page and get the full error trace and paste it here so I can look further?

If you're using PHP 8.1 - keep in mind that version is not yet supported by Moodle (https://tracker.moodle.org/browse/MDL-73016)

**Comment by ghost** [comment]
Hi
PFA for the errors report you have asked for and i am using php8.0 and MOODLE_400_STABLE Release
![image](https://user-images.githubusercontent.com/6366787/177915977-04a0f3a0-51e5-41be-86c8-11c354bf2cfe.png)

**Comment by danmarsden** [comment]
That looks like #479 which has been fixed for ages... are you sure you have the right attendance plugin version installed?

**Comment by ghost** [comment]
let me check which version it is

**Comment by ghost** [comment]
I have checked and sorry the version was an older one as I have searched in google and directly downloaded it without checking the version as I was thinking it will return me the latest one
