### ISSUE TITLE
Mod Attendance not properly showing time of sessions

### ISSUE THREAD

**Issue by svanschuyver** [danmarsden/moodle-mod_attendance#604]
The session list on the manage.php page only shows am or pm for the time, and it does not include any time numbers. 

![image](https://user-images.githubusercontent.com/46025741/184224873-1a0aa8a2-6122-4311-9f67-47603e211f26.png)

**Comment by danmarsden** [comment]
Hi there, 

can you please provide a bit more information there? - what version of Moodle are you running, what version of the attendance plugin do you have installed (is it the latest version) - also what PHP version is running on your server and what O/S is it using? for example is it hosted on a windows server or a linux-based server?

The attendance plugin uses the language pack for deciding how to display the time - what language do you have set, and have you customised the language strings on your site?

in particular - I want to know what you have set for the "strftimeh" and "strftimehm" lang strings in attendance for the language you have selected.

**Comment by svanschuyver** [comment]
Good morning,

Sorry I should have provided that initially. We are running Moodle 3.11.8, build: 20220711. Attendance plugin version 3.11.12. PHP version 7.4.22 running on Windows Server 2016 Standard. I'm seeing this error using en_us language. I just switched to en to see what that looked like, and it looks fine there. There in lies the problem. We don't really customize our language strings, except for a few very specific places.

Here are the language strings for attendance in en_us on our server. I'm not seeing "strftimeh" here.
```
$string['enrolmentend'] = 'User enrollment ends {$a}';
$string['enrolmentstart'] = 'User enrollment starts {$a}';
$string['enrolmentsuspended'] = 'Enrollment suspended';
$string['strftimedm'] = '%m/%d';
$string['strftimedmy'] = '%m/%d/%Y';
$string['strftimedmyhm'] = '%m/%d/%Y %H:%M';
$string['strftimedmyw'] = '%m/%d/%y (%a)';
$string['strftimehm'] = '%l:%M%P';
$string['strftimeshortdate'] = '%m/%d/%Y';
```

**Comment by danmarsden** [comment]
Probably  the capital P in the strftimehm field. That's not supported in some O/S

**Comment by danmarsden** [comment]
There is some code here that tries to work around buggy strftime in some o/s that could be improved for this too: https://github.com/danmarsden/moodle-mod_attendance/blob/ddc2045bcbe779cb3044f7fde78e6b7059b63160/locallib.php#L1250  pull requests always welcome otherwise I'll try to get to this one day...

**Comment by svanschuyver** [comment]
Great, that's helpful. Temporarily, I'm just deleted the en_us attendance.php language file, as the en defaults are great for us. I might look into fixing it code wise, if so, I'll be happy to put in a PR.

**Comment by svanschuyver** [comment]
@danmarsden I did find a bug in the module that I fixed myself. There's a SQL issue that can lead to a cannot divide by zero error. Happy to do a PR. How would I go about doing that?

**Comment by danmarsden** [comment]
just pushed something that might prevent this for others - but... I don't have a windows server running right now, so will leave it there for someone else to test... thanks!
