### ISSUE TITLE
Problem with hours:minutes 

### ISSUE THREAD

**Issue by ralfhilg** [danmarsden/moodle-mod_attendance#606]
Adding events with full hours (ie 8:00) are shown in the overview as 8 without :00. 
Moodle 3.11 with German lang pack. 
![Screenshot_3](https://user-images.githubusercontent.com/41056305/184398825-ed7d50d2-8e71-4d52-8d05-c0a48e36ef77.png)

**Comment by danmarsden** [comment]
@ralfhilg sounds like an issue with the German Lang pack.

when the time value is "00" it uses the string strftimeh - in the default version that is:

$string['strftimeh'] = '%I%p';

which turns it into 1AM - 2PM style values.

it looks like your strftimeh is set to the 24hr equivalent with the "hour-only" - probably just set to "%H"
if you want the full time to show in 24hr format (both hour and minute) you'll need to change that string to something like "%H:%k" or revert back to 12hr format with the "am/pm" flags using %p or %P

thanks!

**Comment by ralfhilg** [comment]
Hi Dan,

thanks for the information. You are using an own string for the time in mod_attendance instead of the strings from langconfig.php where  I tried to find the problem.
Finally I could solve it with '%H:%M' for time in 24.00 format. I will change it in the German lang pack also.
