### ISSUE TITLE
Problem with 4.0.6 version mod_attendance multiple sessions

### ISSUE THREAD

**Issue by cearanda** [danmarsden/moodle-mod_attendance#616]
Hello,

When we have upgraded since 4.0.3 version of mod_attendance plugin to 4.0.6 version, we have appreciated an issue. When we configure a session of attendance with multiple sessions we select for example all friday, but when we finish, the first session is correct but the other sessions are configured to thursday (1 day less always).

In multiple sessions, sessions are configured always with 1 day less...

Thank you very much.

**Comment by danmarsden** [comment]
Thanks, that will be due to the hack I added in #536, I'll rewrite that chunk properly sometime tomorrow and push a fix through.

**Comment by cearanda** [comment]
Thank yoy very much for your answer. I wait that.

**Comment by danmarsden** [comment]
should be a lot better now - I spent a bit more time digging into that function and converted it to use some slightly better date calculation functions - sorry about the inconvenience!

**Comment by cearanda** [comment]
Thank you very much. It is working now.
