### ISSUE TITLE
Subnet range in CIDR notation

### ISSUE THREAD

**Issue by Peituga** [danmarsden/moodle-mod_attendance#620]
Hi, in our case it would be more than desirable to have the option to restrict IP addresses using CIDR notation. Right now it can be made only by a comma separated list and in our case, we have 32 class C networks, so you can imagine the ammount of hosts and ips...

In addition, if we add our long list of IP´s, at the time when we save the changes we got a database write error.

Thank you

**Comment by danmarsden** [comment]
The attendance code uses moodles core api for this - pretty sure it supports cidr (but I haven't used it myself in attendance for ages) you can also see the other formats it supports along with examples here:
https://github.com/moodle/moodle/blob/4a0b0c82865fcee5e77f4356b30ddba728b921b4/lib/moodlelib.php#L8980

**Comment by Peituga** [comment]
> The attendance code uses moodles core api for this - pretty sure it supports cidr (but I haven't used it myself in attendance for ages) you can also see the other formats it supports along with examples here: https://github.com/moodle/moodle/blob/4a0b0c82865fcee5e77f4356b30ddba728b921b4/lib/moodlelib.php#L8980

Good feedback @danmarsden you are right! Even though it would be nice to add this valuable info to the help text of the configuration settings of the plugin. I was confused by the original description.

Solved. Thanks!
