### ISSUE TITLE
Attendance plugin or Moodle upgrade breaks participants' pages

### ISSUE THREAD

**Issue by dewray** [danmarsden/moodle-mod_attendance#622]
Steps to reproduce:

1. Make two courses in Moodle 3.11.? with the same participants in both courses. Ending date of course A is some weeks before opening date of course B.
2. Set up Attendance for both courses
3. Upgrade from Moodle 3.11.? to Moodle 4.0.1 after one course ends
4. After upgrading, clicking on students' pages from Participants list results in "missing parameter contextid" error and no information loads. "Continue" button leads back to the participants' list.

Students' pages are still accessible from "Site Administration/Users/Browse list of users." If the Attendance plugin is deleted from Course B and put it in again after deletion, everything works and participants' pages function normally.

This happened with my system recently. I set up the Courses A and B in March 2022; the A courses ended in July 2022, and the B courses begin in September 2022. The upgrade to Moodle 4.0 happened in August 2022.

Setup: Ubuntu 22.04/Mariadb 10.6.7/php 7.4.30/(currently) Moodle 4.0.4, build 22020912. Fordson theme with 3.11.?; LearnR theme with 4.0 ff. mod_attendanceregister also in use.

**Comment by danmarsden** [comment]
can you please set debugging level to "developer" and display errors = on and post the full debug trace of the page you are getting the missing parameter "contextid" error on? - thanks.

**Comment by dewray** [comment]
I will try, but the Fall semester begins in 8 minutes here in Japan, and I have to search for a course that's not fixed yet.

**Comment by danmarsden** [comment]
tbh - I'm not going to look at this without the debug trace, so if you want my help......

**Comment by danmarsden** [comment]
I did manage to look at the code that I think might be the cause, and I've pushed a fix into the github repo here that "might" fix this, but without the debug trace I can't confirm that.
