### ISSUE TITLE
Error upgrading from 4.0.8 to 4.0.10 when using MS SQL based db.

### ISSUE THREAD

**Issue by pete1854** [danmarsden/moodle-mod_attendance#623]
Hi,

When upgrading to version 4.0.10 from 4.0.8 I get the following exception:

Debuginformation: SQLState: 42S22<br>
Error Code: 207<br>
Message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'ID'.<br>

SELECT id
FROM mdl_attendance_log
WHERE ID NOT IN (SELECT max(id)
FROM mdl_attendance_log
GROUP BY sessionid, studentid, statusid)
[array (
)] 
Error code: dmlreadexception

Stack trace:

line 486 of \lib\dml\moodle_database.php: dml_read_exception thrown
line 324 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
line 431 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
line 900 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
line 976 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
line 746 of \mod\attendance\db\upgrade.php: call to sqlsrv_native_moodle_database->get_records_sql()
line 883 of \lib\upgradelib.php: call to xmldb_attendance_upgrade()
line 582 of \lib\upgradelib.php: call to upgrade_plugins_modules()
line 1935 of \lib\upgradelib.php: call to upgrade_plugins()
line 719 of \admin\index.php: call to upgrade_noncore()

**Comment by danmarsden** [comment]
good old MS Sql.... one day you'll stop using it for Moodle right? :-)

**Comment by danmarsden** [comment]
feel free to submit a PR to fix this otherwise  just comment it out on your upgrade and fix the duplicates manually.

**Comment by pete1854** [comment]
Sorry, can't do that. We're all in on MSSQL :) Will try and fix the code as per your recommendation.
Cheers,
Peter
