### ISSUE TITLE
Wrong path for the mobilestyles.css

### ISSUE THREAD

**Issue by ptramonti** [danmarsden/moodle-mod_attendance#627]
Hi,
I get the error "File does not exist" on /mod/attendance/mobilestyles.css because I don'have my Moodle installation on the root path.
You have to change [the file db/mobile.php line 38](https://github.com/danmarsden/moodle-mod_attendance/blob/90bf15f2ddfbbe53a845eeac1b8e89c3b93a4309/db/mobile.php#L38) from:
`'url' => '/mod/attendance/mobilestyles.css',`
to
`'url' => $CFG->wwwroot . '/mod/attendance/mobilestyles.css',`

Thank you
Paolo

**Comment by danmarsden** [comment]
thanks for the report! - I've just pushed a fix into the git branches here, it won't be updated in the moodle.org plugins db until the next time I push a release.

thanks,
