### ISSUE TITLE
Hours format

### ISSUE THREAD

**Issue by jaume77** [danmarsden/moodle-mod_attendance#628]
Hello!

The format in which the hours appear in module is a mix of 24h/AM.PM formats;

- When the start time is before 12:00 pm, it is displayed in AM/PM format.
- When the start time is after 12:00 pm, it is displayed in 24H format.
- End time is always displayed in AM/PM format.

The time format in the rest of the environment is 24H.

The module version is 2021082600

![attendance](https://user-images.githubusercontent.com/2485232/191023633-4d632371-eb16-44bf-a6f6-5da8640dc2d6.jpg)

**Comment by danmarsden** [comment]
Sounds like an issue with your lang pack. You will need to report this to whoever maintains the language pack for the language you have selected.
