### ISSUE TITLE
MOODLE_400_STABLE branch calls datasource add_all_from_entities

### ISSUE THREAD

**Issue by nwp90** [danmarsden/moodle-mod_attendance#629]
core_reportbuilder\datasource does not have add_all_from_entities in 4.0 so MOODLE_400_STABLE branch should not try to use it

**Comment by danmarsden** [comment]
duplicate of #611 - are you using the latest version?

**Comment by nwp90** [comment]
Thought we were; will check.

**Comment by nwp90** [comment]
Oh hang on, no, that was pre the update we're currently doing.

**Comment by danmarsden** [comment]
cool - flagging this as closed then :-)
