### ISSUE TITLE
Feature Request: Use core user identity field list when displaying list of students.

### ISSUE THREAD

**Issue by ffkharbat** [danmarsden/moodle-mod_attendance#63]
Hi 
I appreciate your effort. 
I was thinking if I can add the Student ID to the list while taking the attendance. The first name and last name is not enough some times. Any help? 

Thanks

**Comment by ffkharbat** [comment]
In moodle-mod_attendance / student_attenance_form.php Line 58, I tried to add $USER->id.' '
$mform->addGroup($radioarray, 'statusarray', $USER->id.' '.$USER->firstname.' '.$USER->lastname.':', array(''), false);

but it did not work

**Comment by mhughes2k** [comment]
this actually raises an interesting issue. Our staff have no idea of the student id, nor the "idnumber" field in the user profile (which holds a globally unique value for the person), we populate a custom user profile field ("Registration Number") with the students registration number (which uniquely identifies both the person and the period of study their on).

It would be nice if we could display the custom profile field as that's the value that the user will understand (the idnumber *only* being used for integration syncing).

This Moodle tracker issue (https://tracker.moodle.org/browse/MDL-45242) is interested in solving this at the Moodle level by allowing profile fields to be included as the "student identity".

**Comment by danmarsden** [comment]
Unfortunately the attendance code doesn't use that identity field stuff much but we should convert it to use it correctly in a number of different places. I've amended the title of this issue as it would make sense to do this at some point. @ffkharbat if you manage to work it out feel free to submit a patch.

**Comment by danmarsden** [comment]
slightly related to this - the get_users() function in locallib.php could do with a good re-factor, it also returns users with disabled enrolment methods:
https://tracker.moodle.org/browse/MDL-27591

**Comment by wiktorwandachowicz** [comment]
Actually, student identification fields (as selected by administrator) are already displayed in gradebook.
So maybe a relevant part of code could be ported from there?

(config param: showuseridentity in /admin/settings.php?section=userpolicies)

**Comment by danmarsden** [comment]
yes - that is correct and is exactly what this issue is about. It would be great to convert the Attendance code to pull through the identity fields. Patches are welcome! :-)
