### ISSUE TITLE
HTML tags not show.

### ISSUE THREAD

**Issue by mmonant** [danmarsden/moodle-mod_attendance#630]
Hello again.

As a teacher I create an attendance session, with html tags (see image):

![image](https://user-images.githubusercontent.com/114153253/191731529-40c0fda2-f25f-4a50-a62f-8c4d9858acd2.png)

But as a student these html tags are not shown (bold, hyperlinks, etc.)

![image](https://user-images.githubusercontent.com/114153253/191731707-bb91b91b-aee1-4904-a49a-bdce8757e7ae.png)

Have you considered leaving the line 1365 of the file renderer.php (ver 4.0.10 - 2022083107 ) like this ? :

> $row->cells[]` = $sess->description;

instead of

> $row->cells[] = format_string($sess->description, false);

This allows html tags again in the session description text, like previous versions. In my opinion, the session description text, may not be critical to filter from html tags. In my case I use this module also to include in the text description of every session, links to virtual training meeting, but these  hyperlinks do not appear 😪.

Sorry, and tranks again. Regards!

**Comment by danmarsden** [comment]
Thanks for the report - it should have been using format_text() instead like the report page does - I've just pushed that fix in now.

**Comment by mmonant** [comment]
Thank you again. Greetings.
