### ISSUE TITLE
A bug in report tab when group mode is separate groups

### ISSUE THREAD

**Issue by Saeid2016** [danmarsden/moodle-mod_attendance#637]
Hello,
There is a bug in the report tab of Attendance module. When group mode is set to separate groups, a user which is in group A and has permission to view report (mod/attendance:viewreports) when clicks on the report tab, he can view all participants of course while he should only be able to see the members of group A.

**Comment by danmarsden** [comment]
Thanks for the report. Group handling in the attendance plugin expects that you are using group sessions - (an individual session tied to a specific group) - when you create the sessions you state which group it is for. But... I'll have a think on that further to see if we can improve that as the user definitely shouldn't be able to see users they should not be able to.

**Comment by danmarsden** [comment]
I haven't actually been able to reproduce this... If the course is set to "separate groups" and the activity is set to "separate groups" a non-editing teacher assigned to a group can only view the users in the groups they are a memboer of on the "report" tab.

If the activity level is set to "visible groups" it does allow them to view all users/groups but that's expected behaviour as it's what group mode set to visible is supposed to do.

Can you please provide some more information? - what version of Moodle, what version of the attendance plugin, have you set separate groups at the course level AND the activity level? - does the report page show the group selector at the top of the page when logged in as the non-editing user that is only in one group allowing them to select between "all users" and specific groups?

thanks!

**Comment by Saeid2016** [comment]
> I haven't actually been able to reproduce this... If the course is set to "separate groups" and the activity is set to "separate groups" a non-editing teacher assigned to a group can only view the users in the groups they are a memboer of on the "report" tab.
> 
> If the activity level is set to "visible groups" it does allow them to view all users/groups but that's expected behaviour as it's what group mode set to visible is supposed to do.
> 
> Can you please provide some more information? - what version of Moodle, what version of the attendance plugin, have you set separate groups at the course level AND the activity level? - does the report page show the group selector at the top of the page when logged in as the non-editing user that is only in one group allowing them to select between "all users" and specific groups?
> 
> thanks!

Hello @danmarsden and thanks for reply. Please see the screenshot:
![attendance](https://user-images.githubusercontent.com/25425826/199184138-4f463634-2f82-46b4-8c79-8cd4f3a31ce0.png)

A non-editing teacher assigned to group A but in report tab he views all participants. In the screenshot only user2 assigned to group A. 
![image](https://user-images.githubusercontent.com/25425826/199185190-8d0cf385-7fc1-4e6b-814a-e98f72f1b4a1.png)

**Comment by danmarsden** [comment]
Can you please confirm which version of Moodle you are running and which version of the attendance plugin you have installed?

**Comment by Saeid2016** [comment]
> Can you please confirm which version of Moodle you are running and which version of the attendance plugin you have installed?

I tested it both in Moodle 3.11.5 and Moodle 4.0.4
In Moodle 3.11.5 the attendance version is 3.11.16 and in Moodle 4.0.4 the plugin version is 4.0.10

**Comment by danmarsden** [comment]
Thanks for that - I managed to find a weird edge case and reproduce it - I've pushed a fix for this which is a little bit hacky and I think I'd like to rewrite it at some point, but it does seem to fix it - I've pushed this into the 3.11 and higher versions into the github repo here - would be great if you were able to test it and confirm if it fixes for you before I release the new version to the plugins db - thanks!

**Comment by Saeid2016** [comment]
> Thanks for that - I managed to find a weird edge case and reproduce it - I've pushed a fix for this which is a little bit hacky and I think I'd like to rewrite it at some point, but it does seem to fix it - I've pushed this into the 3.11 and higher versions into the github repo here - would be great if you were able to test it and confirm if it fixes for you before I release the new version to the plugins db - thanks!

Hi, I tested it. The issue has been fixed. Thank you very much!
