### ISSUE TITLE
Rotate QR code/password expiry

### ISSUE THREAD

**Issue by frs2022** [danmarsden/moodle-mod_attendance#639]
Dear All, 

In admin side of attendance plugin we set the: 
Rotate QR code/password interval (seconds): 100
Rotate QR code/password expiry margin (seconds): 100

But we face issue that even the first password rotate and expired , some student still  can enter first password to take the attendance, any one can help in this ?  I need to clary if the attendance use the time of  the server  or machine "device"

Thank you

**Comment by danmarsden** [comment]
so - the expiry margin "adds" a margin on top of the qr code interval - so if the qr code is available for 100 seconds, and you have a 100 second expiry margin, the qr code is valid for 200 seconds - usually you set the expiry margin much lower - to allow the code to be valid briefly like 5 seconds after it's no longer shown on the screen - does that explain the behavior your'e seeing?

The computer displaying the qr code (eg the teachers device) must have the correct synchronized time, but also the server hosting Moodle must also have the correct synchronized time (the time on the students device doesn't matter.)

**Comment by danmarsden** [comment]
any update? - did that explain the issue you were seeing - can we close this?

**Comment by frs2022** [comment]
Hello,

Sorry for late reply..

Yes thank you.
