### ISSUE TITLE
Checksum report requided .... total for present, total for absent and so on 

### ISSUE THREAD

**Issue by jaanx** [danmarsden/moodle-mod_attendance#64]
Checksum report requided

just after checking attendance I require report like this

![attendance_repport](https://cloud.githubusercontent.com/assets/2552940/5809119/31088d78-a035-11e4-8f20-928a041b60db.gif)

after pressing "save attendance" button or **better before** pressing "save attendance" button

Jan Krolikowski
Lodz University of Technology

**Comment by danmarsden** [comment]
the reports have been improved a lot and now include some nice sums like this under each session - feel free to submit a new request if you would like further improvements - please note that further improvements may require funding. Thanks!
