### ISSUE TITLE
Responsive approach to date range/pagination form elements

### ISSUE THREAD

**Issue by stephensharpe** [danmarsden/moodle-mod_attendance#642]
A few responsive issues with the filtering aspects of the 'Report' tab.

* filtering options don't wrap responsively
* date range / pagination are squished when using smaller screens

Moodle 3.11
![image](https://user-images.githubusercontent.com/36191251/200563073-b4394a17-1c87-4f5a-9ada-6ff0c92b8570.png)

Moodle 4+
![image](https://user-images.githubusercontent.com/36191251/200562750-e67e68c1-9c7e-4b3b-9ec9-d9c51666d703.png)

**Possible improvements:**
* Adjust markup for `.attfiltercontrols` to use flex wrapping properties
* Alternatively, apply `white-space: nowrap;` or the bootstrap class `text-nowrap` class to the date range/pagination table cells

Thanks!
Stephen

**Comment by danmarsden** [comment]
Thanks Stephen - feel free to submit a pull request to improve that report. I really don't like the way that filters at all and would like to completely rewrite that filtering UI one day - I have been thinking about re-designing those reports to use Moodle's new reportbuilder API's, however reportbuilder doesn't quite provide all the functionality we would need to replace that page yet.

**Comment by stephensharpe** [comment]
thanks @danmarsden. PR created. Hopefully it improves the responsive view a little bit - https://github.com/danmarsden/moodle-mod_attendance/pull/643

**Comment by danmarsden** [comment]
great thanks! - merged that in now so closing this off.
