### ISSUE TITLE
Add total count of present ?

### ISSUE THREAD

**Issue by nicolasunivlr** [danmarsden/moodle-mod_attendance#644]
Hi,
Is it possible to add the total number of present for a session on the manage.php page ? To have this information, we have to go to take.php and select no paginate and go at the bottom of the page.
Thanks
For example :
![Screenshot 2022-11-09 at 12-37-55 Réseaux - novice Présence](https://user-images.githubusercontent.com/49336166/200820821-d7db2667-f062-4ed6-ae6f-f562cc4be59a.png)
or 85/98 If 85 out of 98 are present

**Comment by danmarsden** [comment]
Thanks for the idea - I think we could display the total counts of each status on that page and I can definitely see that being useful! - we couldn't just display all "Present" values - not all sites will use the "Present/P" status so we probably need to show all possible status values with their short codes like P0 L1 A4 E0 but we also will need to think about whether or not we allow teachers to hide/show that column too.

Ideally my long term preference would be to rewrite this report completely to use the new moodle report builder api, but that api doesn't contain all the features required to replace this table yet (in particular bulk action capabilities) but in the short term I'd be happy to see it added to this report.

If you have internal development capabilities, feel free to submit a pull request! - thanks.

**Comment by danmarsden** [comment]
you should be able to do this with the latest report builder report source so I'm closing this one off - feel free to report any further improvements though!
