### ISSUE TITLE
Non well formed numeric value encountered

### ISSUE THREAD

**Issue by scyrma** [danmarsden/moodle-mod_attendance#646]
Hi Dan,

We host a number of sites using Attendance and this error keeps coming up in the logs, though no users have complained.

That's on Moodle 4.0.5 with mod_attendance following MOODLE_400_STABLE (up to commit 106342e85e on Nov 15).

moodle-context.exceptions.errfile: /var/www/moodle/mod/attendance/classes/output/renderer.php
moodle-context.exceptions.errline: 1221
moodle-context.exceptions.errno: 8
moodle-context.exceptions.errstr: A non well formed numeric value encountered
moodle-context.script: /var/www/moodle/mod/attendance/view.php
moodle-context.uri: /mod/attendance/view.php?id=17954&mode=1

I'm guessing it's format_float() complaining in https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_401_STABLE/classes/output/renderer.php#L1221

Thanks.

**Comment by danmarsden** [comment]
Thanks @scyrma what php version are you running?

**Comment by danmarsden** [comment]
never mind - I see the issue, have pushed a fix through - thanks for the report!
