### ISSUE TITLE
Attendance reports: some table columns too narrow for content

### ISSUE THREAD

**Issue by phaedrus355** [danmarsden/moodle-mod_attendance#65]
Hello: 
 
First, thank you for this very useful module! Second, the Attendance Report page has a table layout and readability problem, especially when viewed in the Student role. Present across Firefox, IE, Chrome, and Safari browsers for PC. Have mod_attendance version 2014112001 installed in Moodle 2.7.

When viewed in an Administrator or Teacher role, the Attendance Report columns Date and Time are too narrow to easily read their content while the columns Type and Description are excessively wide. 

When viewed in Student role, the Attendance Report columns Date, Status, and Remarks are only one character wide (very difficult to read) while the column Description occupies 80% of the table width.

Please see attached screenshots taken in Firefox browser (zoom view reset, zoom text only unchecked).

I'm hoping there is an easy CSS style sheet fix to these column width problems. Thanks!
![attend-rpt-student1-day](https://cloud.githubusercontent.com/assets/1421814/5894828/af575bcc-a4c3-11e4-8a3f-c79dd1b31132.jpg)
![attend-rpt-teacher1](https://cloud.githubusercontent.com/assets/1421814/5894829/af5cffc8-a4c3-11e4-9e31-7c42c42adf6c.jpg)
![attend-rpt-student1-allpast](https://cloud.githubusercontent.com/assets/1421814/5894830/af5e2326-a4c3-11e4-92d1-63f648af102c.jpg)

**Comment by danmarsden** [comment]
Thanks for reporting this - the screenshots help a lot. I'm pretty busy at the moment so don't have plans to work on this as a volunteer right now but If someone finds a fix for this please let me know and I'll include it.

**Comment by danmarsden** [comment]
I've checked this in 3.0 using the themes: clean, canvas, more and they all display better than the screeshots provided. If there are still issues with the "core" Moodle themes please let me know and I'll take another look - if these are issues with 3rd party themes please contact the 3rd party theme developers for help. Thanks!
