### ISSUE TITLE
Session is not calculated correctly in points and percentage

### ISSUE THREAD

**Issue by masatyo** [danmarsden/moodle-mod_attendance#666]
Hello,

I encountered an issue where number of sessions is not correctly calculated in scores. Below is the screenshot : 
![image](https://user-images.githubusercontent.com/124858326/217723063-3f82dce0-07cc-4fa9-baac-9db86dd424b7.png)

There are 25 sessions, value in 'P' is correct, while value in 'A' is not correct and often more than maximum session available.
Is there any settings that I set incorrectly?

Moodle version 3.11+, plugin version 3.11.11 (2021082601).

**Comment by danmarsden** [comment]
3.11.11 is quite old and a number of fixes have been includes since that version which could be related. Please update the attendance plugin and if you are still having issues please create a new report - thanks!
