### ISSUE TITLE
Problems with new setting "Allow students to update own attendance"

### ISSUE THREAD

**Issue by t-schroeder** [danmarsden/moodle-mod_attendance#673]
#659 introduced the option on session creation to allow students to update their own attendance status after already having submitted one. I tested it and noticed some problems:

1. When creating a session the new setting "Allow students to update own attendance" appears twice when I check "Allow students to record own attendance".
2. With the new setting enabled (both in site administration and for a session) a submitted attendance status doesn't get saved anymore. Updating an existing status works, but inserting a new one doesn't.

**Comment by t-schroeder** [comment]
I just noticed the first issue has already been fixed through 2a428ada772822fbe8090fa1232130a2d95add5b, there just hasn't been a new release with that fix yet.

**Comment by danmarsden** [comment]
Thanks @t-schroeder - I can't reproduce the behaviour you're describing with the latest code - must be something else interacting here... I'll see if I can see what that might be by looking at what you're doing in your patch...

**Comment by danmarsden** [comment]
I managed to see what you were doing there and I've just tidied that up manually - I skipped out one of your suggested changes, but I suspect that was just accidental in your PR, but let me know if there was a reason you dropped that in and I'll take another look.

**Comment by t-schroeder** [comment]
Thanks for accepting those changes. https://github.com/danmarsden/moodle-mod_attendance/pull/674/commits/60a98c940073ffc4ec845c26a7a0cdcf18fb19ae fixes a warning that appears in this circumstance: You have a session with self-recording and updating attendance allowed for students. You login as a student who hasn't recorded anything for that session. When you click on "Submit attendance" you get this warning:

> Warning: Undefined array key 0 in [...]/mod/attendance/classes/form/studentattendance.php on line 81

The warning might be hidden behind the navbar. When you then click the cancel button you get that same warning, but displayed on a page of its own.

The cause: `$existingstatusid` would be `false` since there's not yet a status for that session and that user. Array access at index `false` == `0` fails because each status id is a positive number.

**Comment by danmarsden** [comment]
ah - I missed that when you updated it after the first draft - yeah I can see that makes sense, will drop a patch in shortly.
