### ISSUE TITLE
Switching language on the take attendance page leads to an error

### ISSUE THREAD

**Issue by t-schroeder** [danmarsden/moodle-mod_attendance#676]
The cause is that `$PAGE->set_url()` doesn't get called with the required parameters.

**Comment by t-schroeder** [comment]
I haven't checked all pages, but I believe this problem occurred both when a teacher takes attendance and when a student does. And I think those are two different pages. Your fix works for the case where the teacher takes attendance, right?

**Comment by danmarsden** [comment]
ah - yeah, only the teacher taking attendance page was updated there thanks -  I'll reopen and check that sometime...
