### ISSUE TITLE
No capability checks on get_sessions web services call.

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-mod_attendance#678]
...as far as I can see, anyway.

For example, mod_attendance_get_sessions once made available appears to allow access to sessions site-wide. There is no capability check that might allow it to be locked down to a particular context in Moodle.

**Comment by danmarsden** [comment]
that's just... wrong... and something I would report as a bug myself when reviewing the webservices in a plugin too... I'll get that sorted... probably using something similar to whats being done in the get_session code. (checking per session for access.)

**Comment by danmarsden** [comment]
I've just dropped in a similar check to the get_sessions web service call for now - which I don't like all that much but was lowest potential impact. I think in a future release it might make sense to create a specific capability for the webservices calls.
