### ISSUE TITLE
Tag the releases

### ISSUE THREAD

**Issue by taraghi** [danmarsden/moodle-mod_attendance#679]
Would you mind tagging the releases?

This would help us easily integrate the releases into our Moodle environment via our CI process.

Thank you!

**Comment by danmarsden** [comment]
Thanks for the request, I maintain a lot of different plugins as a volunteer both in my personal repo and in the catalyst org one, we use git branches and have been rolling out the automatic publishing to moodle.org plugins db process but have no plans to use tags at this stage. Thanks
