### ISSUE TITLE
Database schema is not aligned

### ISSUE THREAD

**Issue by scyrma** [danmarsden/moodle-mod_attendance#681]
Just upgraded to the latest version from git, into Moodle 4.1.2. The database schema check is telling me the "Database schema is not aligned" for table "attendance_sessions":
> column 'allowupdatestatus' should be NOT NULL (I)
> column 'allowupdatestatus' has default 'NULL', expected '0' (I)

**Comment by danmarsden** [comment]
grrr... how did I miss that one.... I've just pushed a fix - thanks for the report!

**Comment by scyrma** [comment]
Thanks Dan, that was quick!

Le mar. 28 mars 2023, 06 h 36, Dan Marsden ***@***.***> a
écrit :
