### ISSUE TITLE
Moodle 3.7->3.11 upgrade takes 70+ mins with the plugin installed

### ISSUE THREAD

**Issue by golenkovm** [danmarsden/moodle-mod_attendance#685]
Hi @danmarsden ,

We're facing a long running upgrade step that is taking ~60 mins to complete this select https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/db/upgrade.php#L713-L718

See upgrade log below:
```
-->mod_attendance
++ 2020072900: Success (0.34 seconds) ++
++ 2021050700: Success (1.30 seconds) ++
++ 2021082400: Success (1.97 seconds) ++
++ 2021082401: Success (1.16 seconds) ++
++ 2021082402: Success (1.90 seconds) ++
++ 2021082600: Success (0.03 seconds) ++
++ 2021082609: Success (3787.31 seconds) ++
++ 2021082610: Success (0.02 seconds) ++
++ Success (3794.69 seconds) ++
```

The `mdl_attendance_log` table has 56226 records and eventually none of them get deleted as part of this upgrade step.

Interesting fact that the SQL completes almost instantly when executed in CLI:
```
mysql> SELECT id FROM mdl_attendance_log WHERE id NOT IN (SELECT MAX(id) FROM mdl_attendance_log GROUP BY sessionid, studentid, statusid);
Empty set (0.15 sec)
```

I also tried to make a simple php script to replicate long running select:
```
<?php
define('CLI_SCRIPT', true);
require(__DIR__ . '/config.php');
global $DB;
$sql = "SELECT id
                      FROM {attendance_log}
                      WHERE id NOT IN (SELECT max(id)
                               FROM {attendance_log}
                           GROUP BY sessionid, studentid, statusid)";
$records = $DB->get_records_sql($sql);
mtrace('Count: ' . count($records));
```

But it is same quick:
```
root@3be64880750e:/var/www/site# time php test.php 
Count: 0

real	0m0.972s
user	0m0.397s
sys	0m0.161s
```

Tried this before and after upgrade. Can't replicate the problem outside of the upgrade process.

I managed to profile it, please see the screenshot below:
![image](https://github.com/danmarsden/moodle-mod_attendance/assets/22066290/226993c4-e393-4d14-a651-de28e750ffd0)

**Comment by danmarsden** [comment]
hey Misha - pull requests welcome ;-) - unfortunately I don't have time to look into this as a volunteer at the moment - thanks!

**Comment by golenkovm** [comment]
Np @danmarsden I'd love to implement a fix but for some reason the SQL works fine when executed outside of the upgrade step. We'll see if I get anything.

**Comment by danmarsden** [comment]
closing this as won't fix, but I'm happy to receive pull requests from the community if anyone finds something that works better!
