### ISSUE TITLE
External tests not passing in Moodle 4.2

### ISSUE THREAD

**Issue by juancs** [danmarsden/moodle-mod_attendance#686]
The error we get is:

PHP Fatal error:  Uncaught coding_exception: Coding error detected, it must be fixed by a programmer: When including this file for a unit test, the test must be run in an isolated process. See the PHPUnit @runInSeparateProcess and @runTestsInSeparateProcesses annotations

This error is due to this change in Moodle 4.2:

https://moodledev.io/docs/4.2/devupdate

**Comment by danmarsden** [comment]
Fixed in the merged PR - closing.
