### ISSUE TITLE
Attendance miscalculation in grade book

### ISSUE THREAD

**Issue by jasonalley** [danmarsden/moodle-mod_attendance#69]
This is a very specific, but also misleading bug to both the teacher in the Grader report and a student in the User report. Here's a scenario I've created:

1. I created an Attendance activity with a grade of 52.
2. I then created 26 slots in the Attendance activity, each with a maximum of 2 points (hence the grade of 52 at the initial Attendance creation page).

Here's where the misleading behavior enters:

1. I scored three Attendance slots for one student. Let's say I gave her the maximum of 2 points per session for a total of 6 points out of the 6 up to that point, though 6 out of the semester potential total of 52.
2. After grading this student for three sessions, I see in the Grader report a 52 out of 52 for 100% because her running record is currently listed at 100%, even though she has only earned 6 points up to this point.

It seems the Attendance activity is calculating the total points earned based off the percentage of the cumulative total of all Attendance slots for the course (e.g., 5/6=83.33% so the Grader report would show the student having earned 43.33/52, which also equals 83.33%).

**Comment by danmarsden** [comment]
there are a few other people working on reports (see pull requests and existing bugs) that alter how the grade calculation is made - in particular see the "summary" report pull request.

**Comment by danmarsden** [comment]
closing this as we have other issues discussing the improvement of reports and the percentage calculations - thanks!
