### ISSUE TITLE
(BUG) Moodle 4.1 / Plugin 2023020107: Missing field for passwords

### ISSUE THREAD

**Issue by stdoma** [danmarsden/moodle-mod_attendance#691]
In the version there is no longer a checkbox for random passwords in the settings of an appointment, provided participants can register themselves.
The checkbox in the settings for the default value is still there.

**Comment by danmarsden** [comment]
I can't reproduce this - please make sure you have the latest version of the plugin installed and provide screenshots of any future issues. thanks!
