### ISSUE TITLE
Error when generating an attendance report

### ISSUE THREAD

**Issue by babicht** [danmarsden/moodle-mod_attendance#694]
Moodle version: 4.1.4
Plugin version: 2023020107

When generating a report via "user menu -> reports -> new report -> report source -> attendance" currently we get the following error: 
![image](https://github.com/danmarsden/moodle-mod_attendance/assets/136691601/0efd5aba-3de5-41fc-8043-9308846ca263)

The report seems to be getting generated but when trying to view the report the same error occurs. Other reports are working fine.
Thanks for your help!

**Comment by danmarsden** [comment]
Thanks for the report! Can you also please clarify what database type you are running? Mysql/postgres etc?

**Comment by babicht** [comment]
We are using MariaDB/MySQL.

**Comment by haietza** [comment]
We are also seeing this error with MySQL.

**Comment by danmarsden** [comment]
Thanks for confirming that - I usually do my local testing and development against postgres - if you have internal development capabilities, pull requests are always welcome, otherwise I'll try to take a look at this sometime!

**Comment by danmarsden** [comment]
I've just pushed a fix into the github repo that should fix this for 4.1 and higher versions - let me know if you get a chance to test this and if it resolves the issues you were having!

thanks,
