### ISSUE TITLE
'preventsharediptime' field on form has no labels and no help/documentation

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-mod_attendance#701]
The prevent shared IP part of the form looks like this...

<img width="716" alt="Screenshot 2023-09-22 at 18 22 27" src="https://github.com/danmarsden/moodle-mod_attendance/assets/664139/4e88b507-eb6f-4fca-b22b-f636906ee75b">

There's no clue what the text field on the right of the drop-down is for. There's no label and nothing in the help. You get an error if you don't supply a time. But no clue what the units are or what it does/means (except, I suppose, the hint from the error message).

**Comment by danmarsden** [comment]
yeah - that's a crap UI... who wrote that... (probably me....) 

we should definitely improve that - thanks Howard! :-)

**Comment by danmarsden** [comment]
took a look at this tonight and noticed that it wasn't even supposed to be showing when using "yes" as the option in that list which is probably where some of the confusion lies - it should only show when you select the "Prevent students sharing IP address" "specifed minutes" option - it's still a crap UI but I've pushed a fix to hide that field and prevent the validation from tripping when using "yes"

hopefully it's a bit simpler than it was - thanks!
