### ISSUE TITLE
Coding error detected, it must be fixed by a programmer: Complex columns must have an alias

### ISSUE THREAD

**Issue by haietza** [danmarsden/moodle-mod_attendance#702]
Attempting to create a report with attendance as the source and received the following error:

Coding error detected, it must be fixed by a programmer: Complex columns must have an alias

status_++_total_count.count
Error code: codingerror
* line 312 of /reportbuilder/classes/local/report/column.php: coding_exception thrown
* line 331 of /mod/attendance/classes/local/entities/attendance.php: call to core_reportbuilder\local\report\column->add_field()
* line 80 of /mod/attendance/classes/local/entities/attendance.php: call to mod_attendance\local\entities\attendance->get_all_columns()
* line 257 of /reportbuilder/classes/local/report/base.php: call to mod_attendance\local\entities\attendance->initialise()
* line 56 of /mod/attendance/classes/reportbuilder/datasource/attendance.php: call to core_reportbuilder\local\report\base->add_entity()
* line 99 of /reportbuilder/classes/local/report/base.php: call to mod_attendance\reportbuilder\datasource\attendance->initialise()
* line 68 of /reportbuilder/classes/manager.php: call to core_reportbuilder\local\report\base->__construct()
* line 93 of /reportbuilder/classes/manager.php: call to core_reportbuilder\manager::get_report_from_persistent()
* line 52 of /reportbuilder/classes/form/report.php: call to core_reportbuilder\manager::get_report_from_id()
* line 66 of /reportbuilder/classes/form/report.php: call to core_reportbuilder\form\report->get_custom_report()
* line 68 of /lib/form/classes/dynamic_form.php: call to core_reportbuilder\form\report->get_context_for_dynamic_submission()
* line 73 of /lib/form/classes/external/dynamic_form.php: call to core_form\dynamic_form->__construct()
* line 261 of /lib/externallib.php: call to core_form\external\dynamic_form::execute()

We are running Moodle 4.1.4 (Build: 20230612) and attendance plugin verion 2023020107.

Thanks!

**Comment by danmarsden** [comment]
This looks to be a duplicate of #694 for which I pushed a fix into the github repo for last night? - are you using mysql? - can you try grabbing the latest version from git to see if that helps?

**Comment by haietza** [comment]
I apolozie @danmarsden , I missed that issue and fix and was trying the reports on our production instance. I pulled the latest code and the error appears to be resolved. Thank you!
