### ISSUE TITLE
Moodle 4.3: Deprecated function user_preference_allow_ajax_update()

### ISSUE THREAD

**Issue by opitz** [danmarsden/moodle-mod_attendance#707]
Behat tests with Moodle 4.3:
user_preference_allow_ajax_update() is deprecated. Please use the "core_user/repository" module instead.
line 506 of /mod/attendance/classes/output/renderer.php: call to user_preference_allow_ajax_update()

**Comment by danmarsden** [comment]
thanks for the report! - if you have internal development capabilities, pull requests are always welcome!

**Comment by arborrow** [comment]
@danmarsden - just checking to see if you were hoping or had plans to create a [4.3 branch](https://moodle.org/plugins/mod_attendance/versions)

**Comment by danmarsden** [comment]
always have plans... never enough time to implement them all though! :-) - pull requests with fixes always welcome...
