### ISSUE TITLE
Relationship to Custom Reports

### ISSUE THREAD

**Issue by chihiro-sugita** [danmarsden/moodle-mod_attendance#709]
Installing the latest plugin(2023020107) causes errors in custom reports.
My Moodle : Moodle 4.1.5+ (Build: 20230822)
Several people in my organization have experienced the same phenomenon.

”Coding error detected, it must be fixed by a programmer: Complex columns must have an alias"

**Comment by danmarsden** [comment]
This is a duplicate of #694
