### ISSUE TITLE
Separate groups in attendance

### ISSUE THREAD

**Issue by hanirok** [danmarsden/moodle-mod_attendance#714]
Hi!
We use separated groups in our courses and the teachers only are able to see the students in their groups. When we use Attendance, the teachers can see the sessions of all students of the course (they can choose the “see all” option in the “sessions” select).

In other Moodle Core activities, such as the Moodle assignment, the teachers in a group can only see their students' assignments. We would be very happy if this behaviour could be implemented in your Attendance plugin in this way: if a teacher is in one or more groups, he should only be able to see the sessions of his groups.

Regards and many thanks,

**Comment by danmarsden** [comment]
Can you confirm that both the course settings and the activity level settings both are set to "separate groups" mode, and what version of Moodle and the attendance plugin are you using? - I'm pretty sure we did some work in the last 12-24 months to improve the way group mode works too - so if you have an old version of Moodle or the attendance plugin you should update it to make sure you have the latest version.

**Comment by danmarsden** [comment]
I'm assuming as you have not responded you are using an old version of Moodle or attendance so I'm closing this off, but let me know if not and if you can provide more information we can re-open this again!

thanks.
