### ISSUE TITLE
Exporting 'Common' Session type Sessions filtered by Group throws an error

### ISSUE THREAD

**Issue by barrysspace** [danmarsden/moodle-mod_attendance#72]
*Steps to reproduce:*
1. Create an attendance instance with "Visible Groups" setting
2. Create sessions with Common Group type
3. Export sessions filtered by a Group
4. This throws an error as below
![groups_export_error](https://cloud.githubusercontent.com/assets/7804636/6185654/03f85556-b369-11e4-85fe-71b907843f3c.jpg)

*Expected behaviour:*
The export should filter by group just like the Report page.  I.e. filter by group members not filter by sessions tied to a group.

**Comment by danmarsden** [comment]
Thanks for the patch - it makes sense. There was a small spacing issue introduced in the patch but I've pushed another commit to fix that.

**Comment by wiktorwandachowicz** [comment]
I'm terribly sorry, but this change breaks both report and export with regard to group filtering, when you have group sessions :(

Original reporter described only common sessions and still wanted to filter by group. But our teachers typically create only group sessions, for different groups, of course.

In this case both report and export contain ALL sessions, no matter what group is selected. This behavior is a very bad regression for us - different from mod_attforblock we were previously using. Actually, I have a response from members of two Polish univerisites, that this change is really disturbing.

**Comment by danmarsden** [comment]
Thanks for the report! - I've just taken another look and pushed through a fix - would be great if you could test this and let me know if it works as you expect before I update the moodle.org plugins db.

**Comment by wiktorwandachowicz** [comment]
Of course the fixed code will work as before, because of removal of 'false' parameter in call to get_filtered_sessions() in 'renderables.php'.

But this effectively is a reversal of changes commited previously as solution for this issue, compare:
https://github.com/barrysspace/moodle-mod_attendance/commit/e8c58cec563830db618db0464437f8d604ac304e

So while I am the most happy (since I have a similar fix working in production already), the reporter for issue 72 will not be... So this issue should probably be reopened then.

**Comment by barrysspace** [comment]
No this is not just a reversal. It adds a " OR groupid = 0 " to the query so this is perfect for both of us.

**Comment by barrysspace** [comment]
I tested it locally and it worked fine for me

**Comment by wiktorwandachowicz** [comment]
Thank you very much for pointing this out, that's was not easy to spot just by looking at the commit.

I can test it tomorrow at work, but it looks like by having aforementioned " OR groupid = 0 " clause there should be no problem.

**Comment by wiktorwandachowicz** [comment]
Updated and tested today, works a treat.
