### ISSUE TITLE
Undecoded links in description after restore

### ISSUE THREAD

**Issue by voegii** [danmarsden/moodle-mod_attendance#720]
When an attendance activity description has a link to another activity and you restore (e.g. via duplicate) the attendance activity, the link in the description is not valid anymore.

E.g. 
Link before: `https://yourmoodle/mod/glossary/showentry.php?courseid=123&eid=999&displayformat=dictionary`
Link after: `$@GLOSSARYSHOWENTRY*123*999@$&displayformat=dictionary`

I would suggest to add the intro field to the "define_decode_contents" in restore task.

**Comment by danmarsden** [comment]
thanks for the PR - I've cherry-picked into 4.1 and higher branches.
