### ISSUE TITLE
Bulk mark links don't work on Moodle 4.3

### ISSUE THREAD

**Issue by ehoving** [danmarsden/moodle-mod_attendance#722]
The links to bulk mark attendance are not working on Moodle 4.3

Can this be fixed?

![attendance bug](https://github.com/danmarsden/moodle-mod_attendance/assets/56312408/395a9885-3c93-412b-920c-14734336ed4f)

**Comment by danmarsden** [comment]
Thanks for the report - if you have internal development capabilities, feel free to help further by submitting a pull request with the fix!

**Comment by danmarsden** [comment]
looks like this is being picked up in the behat tests on the new 4.3 branch too which is helpful.

**Comment by aspark21** [comment]
might be that re-grunting against 4.3 might clear that up @opitz ?

**Comment by danmarsden** [comment]
I would have expected the moodlecheck call to trigger a warning if grunt was stale - but I've run it just in case locally on a 4.3 site and it doesn't trigger anything - I'd expect there's some other javascript conflict somewhere.

**Comment by opitz** [comment]
@danmarsden Apologies! I have a typo in my fix when I replaced deprecated JS function M.util.set_user_preference().
Will provide a PR ASAP.

**Comment by danmarsden** [comment]
thanks @opitz - I missed that too! :-)
