### ISSUE TITLE
Moodle 4.3.2 error: get_all_user_name_fields() is deprecated

### ISSUE THREAD

**Issue by hsaeedian** [danmarsden/moodle-mod_attendance#726]
hi
after upgared moodle to Moodle 4.3.2 (Build: 20231222) 
i get this error: 

Coding error detected, it must be fixed by a programmer: get_all_user_name_fields() is deprecated. Please use the \core_user\fields API instead

**Comment by danmarsden** [comment]
Hi there, 

That api was deprecated back in Moodle 3.11 and the work to convert the get_all_user_name_fields() apis in Attendance was done a long time ago. I suspect you are either using an old version of the attendance plugin, or this is coming from some other 3rd party code in your site.

Please make sure you have the latest version of the attendance plugin, and if you do, try setting your debugging mode to developer and see what code is reporting that error - thanks.
