### ISSUE TITLE
instructor name

### ISSUE THREAD

**Issue by MuratAmelov** [danmarsden/moodle-mod_attendance#731]
![image](https://github.com/danmarsden/moodle-mod_attendance/assets/161822073/fc49d257-1564-463d-b3ea-03f13a33e5a1)

is it possible to add the name of an instructor from a group or from the instructor role?

**Comment by danmarsden** [comment]
The attendance plugin has the ability to create custom fields which could be used for this, but it doesn't have the ability to automatically list all the available instructors. I think in the meantime you will just need to add it manually to the description of the session.

this isn't something I plan to add as a feature myself - but if you would like to fund development on the plugin I work for the Moodle Partner Catalyst IT - feel free to reach out privately and I can provide information on our rates.

**Comment by MuratAmelov** [comment]
Good afternoon, how much will this modification cost?

**Comment by danmarsden** [comment]
Hi Murat - I can't provide estimates for work via public github comments - please contact me privately (you should be able to find an email address for me without too much difficulty or send me your email details via a message on the moodle.org private messaging.
