### ISSUE TITLE
Unable to save custom session fields when editing sessions

### ISSUE THREAD

**Issue by bwalkerl** [danmarsden/moodle-mod_attendance#736]
Custom session fields are currently only saved when a new session is added and not when editing an existing session. Clicking "Save changes" shows success but the custom session fields aren't being changed. It appears like save_customfields() is never called here?

Tested on MOODLE_401_STABLE branch.

**Comment by danmarsden** [comment]
thanks - doesn't look like many people are using custom fields - that's been a bug for a long time... I've just tidied that up and pushed into the 4.1 and higher branches.
