### ISSUE TITLE
Unable to add new sessions when a custom session field is locked

### ISSUE THREAD

**Issue by bwalkerl** [danmarsden/moodle-mod_attendance#737]
When a field is locked the can_edit() function of the session handler is sending system context to guess_if_creator_will_have_course_capability(), which expects course or course category context. 

![Screenshot from 2024-03-15 17-35-29](https://github.com/danmarsden/moodle-mod_attendance/assets/132629557/0f31823b-826b-4d4b-9a16-b3a87e77f04e)

Tested on MOODLE_401_STABLE branch.

**Comment by danmarsden** [comment]
thanks for the report! - I've just pushed a fix for this into the 4.1 and higher branches.
