### ISSUE TITLE
Automatically setting status after session end

### ISSUE THREAD

**Issue by gergelyrakoczi** [danmarsden/moodle-mod_attendance#738]
We love your plugin at TU Wien and would have a hopefully interesting feature request for you. In large courses, not all students set their statuses for each session. So as teachers, we have to set (with the bulk option) the status of those who have not responded. However, for many sessions and many students, this is quite time-consuming. It would be great to have a feature, where Moodle automatically sets the session for the students e.g. as "absent" after the end of the session. This would save a lot of time.

**Comment by danmarsden** [comment]
That's already possible - first make sure your status set has one of the statues set with the  "Automatically set when not marked" option.

Then when creating the session, under the Student recording sections set "automatic marking" to "set unmarked at end of session"

Then when after the session ends, the scheduled task "Check for attendance sessions that require auto marking" should set the users to the status value you have chosen to use in the status set config.

try it out and feel free to come back and report any issues you have.

**Comment by gergelyrakoczi** [comment]
Oh sorry, for missing this great feature. Superb, thank you very much for your helpful description. I have tested it in our Moodle installation and it is working like a charm.
Cheers,
Gergely
