### ISSUE TITLE
Only profile picture linked to profile

### ISSUE THREAD

**Issue by gergelyrakoczi** [danmarsden/moodle-mod_attendance#740]
We love your plugin at TU Wien and would have a hopefully interesting feature request for you. 

When teachers click on the name of a student in the "Report" tab, the student's relevant information is shown. This is a fantastic overview. However here, only the profile picture is linked to the profile of the student. It would be great to make the link more visible! For example by linking the name of the student or implement an "open profile" link below the profile image. This could improve accessibility as well.

![18-03-2024_10-47-03](https://github.com/danmarsden/moodle-mod_attendance/assets/106730052/d187baa5-0c1a-448b-9b6e-4c6b76ae24d5)

**Comment by danmarsden** [comment]
thanks for the suggestion - if you have internal development capabilities feel free to submit a pull request to help further!

**Comment by danmarsden** [comment]
I had the code open and just pushed an improvement for this one in the end today as well - note these fixes are only currently available in the code in github - it won't come through to the moodle.org plugins db release until I push the next version update there.

**Comment by gergelyrakoczi** [comment]
Perfect, thank you very much!
