### ISSUE TITLE
Calendar language wrong when adding sessions

### ISSUE THREAD

**Issue by gergelyrakoczi** [danmarsden/moodle-mod_attendance#741]
We love your plugin at TU Wien and would have a hopefully interesting improvement for you.

When I add a new session as a teacher and I click on the calendar Symbol to select the date, there is an issue with the language within the calendar. The language of the calendar is always in English and not sensitive to the given language of the user profile - provoking a mix of different languages on one page. See best in this screenshot:

![18-03-2024_10-56-11](https://github.com/danmarsden/moodle-mod_attendance/assets/106730052/be2ec791-1fd2-4f0b-bb86-97f5f99f5843)

**Comment by danmarsden** [comment]
Hi there - this is a standard calendar form element that is used in multiple places within Moodle  - it's actually an issue with Moodle core which is reported here:
https://tracker.moodle.org/browse/MDL-50364

closing this one as it's not an issue with attendance itself.

thanks!

**Comment by gergelyrakoczi** [comment]
I see, thanks for the info. I have voted for the issue in the Moodle tracker. Hope it will be fixed.
Cheers,
Gergely
