### ISSUE TITLE
Breadcrumb navigation lists attendance twice

### ISSUE THREAD

**Issue by gergelyrakoczi** [danmarsden/moodle-mod_attendance#742]
We love your plugin at TU Wien and would have a hopefully interesting improvement for you.

When looking at the breadcrumb navigation of the Moodle Boost theme, there is a difference between Moodle standard plugins and the attendance plugin. Standard Moodle plugins are only listed once in the breadcrumb navigation (non-linked) whereas the attendance plugin is listed twice (once linked and once not linked). This is somewhat confusing for all users - teachers as well as students. It would be great to go along with Moodle standard - having only one item there.

See also in this screenshot:
![18-03-2024_11-10-52](https://github.com/danmarsden/moodle-mod_attendance/assets/106730052/8c8d4712-ebfc-4096-98ee-6f5326b9cbaa)

**Comment by danmarsden** [comment]
nice catch - I've just pushed a fix for that in the version for Moodle 4.3 and higher.

**Comment by gergelyrakoczi** [comment]
Superb, thank you very much for the fast fix. Great!
