### ISSUE TITLE
Keep session description empty when no description is set

### ISSUE THREAD

**Issue by jumabgz** [danmarsden/moodle-mod_attendance#744]
Hello, 

Some teachers find the default "_Regular class session_" text confusing when creating a session without setting a description.
It would be better to keep the text empty if the teacher does not set it. Would it be possible?

Thank you,
Regards

**Comment by danmarsden** [comment]
you should be able to do that yourself using the language customisation feature - the string that is used there is called "nodescription" 

see here for how to do this - just select the attendance lang file and/or search for the string name "nodescription"
https://docs.moodle.org/403/en/Language_customisation#Changing_words_or_phrases
