### ISSUE TITLE
Allow activity grade to use percentage based on Over All Sessions calculation.

### ISSUE THREAD

**Issue by zishanj** [danmarsden/moodle-mod_attendance#745]
In attendance percentage is shown based on **Over Taken Sessions** and **Over All Sessions**, whereas in Grader report attendance percentage is shown based on **Over Taken Sessions** only and students are marked as pass/fail based on this. 

check this screenshot from attendance of 3 students
![image](https://github.com/danmarsden/moodle-mod_attendance/assets/1451292/1361a634-7a54-40aa-bd13-b9a9cebe9309)

and this is the screenshot from Grader report showing only Over taken Sessions percentage ... if its calculated based on Over all Sessions then third student showing 80% will have 21.1% and is failed. Same is the case with other 2 students also showing over taken sessions percentage.
![image](https://github.com/danmarsden/moodle-mod_attendance/assets/1451292/342f17c2-8dfb-4c3b-be44-ab11c5806730)

Is it possible to show it based on **Over All Sessions** in Grader report?

**Comment by danmarsden** [comment]
That's not something that is currently possible with the current codebase - if you have internal development capabilities, pull requests are always very welcome, otherwise feel free to reach out privately if you would like to fund feature development on the plugin.

**Comment by zishanj** [comment]
Any hint on how Grader report fetch the values from attendance plugin? I will then further look into it.

**Comment by zishanj** [comment]
I have to modify some files to make it work.
