### ISSUE TITLE
Acronyms with special characters cause error when using Attendance as datasource in Report Builder

### ISSUE THREAD

**Issue by Limekiller** [danmarsden/moodle-mod_attendance#752]
Hi Dan,

We ran into an issue where--when using Attendance as a data source in the report builder--if there exists a mod_attendance instance that has a status set that contains an acronym with a special character, this will cause a fatal error in the report builder. The error occurs because the Attendance plugin creates a column for every unique acronym in the system, using the acronym itself as part of the column name, but Report Builder requires that column names be alphanumeric; indeed, Moodle throws an error that says as much (I can't remember the exact error text at the moment).

This should be reproducible by creating a new Attendance module, going to the Status Set page, and adding a new row with an acronym like "A+". Then, go to the report builder and create a new report using Attendance as the datasource. You should encounter a fatal error that prevents the page from loading.

The issue can be fixed by either requiring that acronyms be alphanumeric, or by changing the code that generates the column names from the acronyms in the system to escape special characters. If you let me know which of these approaches you'd rather take, I can probably create a pull request. Let me know if you need any more information.

**Comment by danmarsden** [comment]
I think it makes sense to escape the chars in the report builder source itself rather than forcing acronyms to use a certain format - there are some other feature requests like #645 and #671 that might increase the complexity of the acronym field in future too.

thanks!
