### ISSUE TITLE
preconfigured Timeslots

### ISSUE THREAD

**Issue by Sythelux** [danmarsden/moodle-mod_attendance#754]
I'd like to have a preconfigured timeslot field for our teachers at school instead of the 2 drop-downs for the start time and end time each.

Also with current time being preselected. I attached a screenshot how I imagine it to be below.

![Bildschirmfoto vom 2024-05-16 21-31-45](https://github.com/danmarsden/moodle-mod_attendance/assets/601797/c7c1300d-ff01-4c2e-9ccd-9b3c6dee75be)

I can't pre bulk upload the attendance times. For reasons the time planning and moodle attendance are 2 separate systems at my school.

I think it is a lot to ask, but I still try.

**Comment by danmarsden** [comment]
Hi @Sythelux thanks for the suggestion - there is definitely room for improvement around the session start and end field - we also have a request in #638 which mainly covers the ability to set a better sensible default value in the start and end time in the form.

One of the challenges is that your example above is quite specific and the majority of the users of the attendance activity want the flexibility to define a specific start and end time.

One day - I'd like to see a time selector a bit like the create event dialogue in Google Calendar - that allows suggested timings but also with the ability to type directly into the time fields to set a specific time.

I'm going to close this as won't fix as it's not something I plan to work on as a volunteer and the design suggested here decreases the overall flexibility of the plugin - I'm also not a fan of the UX suggested, but getting that right is a lot more work.

I am still open to receiving pull requests to improve the time picker - but they need to be built in a way that improves the general UX and don't make it harder for me to implement something like a google calendar time picker at some point in future.

thanks again!
