### ISSUE TITLE
Bug when switching lang in the upload attendance by CSV

### ISSUE THREAD

**Issue by pittpasc** [danmarsden/moodle-mod_attendance#758]
When I'm in the page "Upload attendance by CSV" 
(url :mod/attendance/import/marksessions.php) and I want to change the language, there are error messages:
<img width="533" alt="image" src="https://github.com/danmarsden/moodle-mod_attendance/assets/20473441/668003a6-ec11-45c4-bca8-81a229ec7e82">

[Moodle](http://moodle.org/) [4.4 (Build: 20240422)](https://moodledev.io/general/releases)
PHP VERSION 8.2.19

**Comment by danmarsden** [comment]
Thanks for the report - if you have internal development capabilities feel free to help further by submitting a PR.
