### ISSUE TITLE
null name given when Save and Display causes error

### ISSUE THREAD

**Issue by krajewsk** [danmarsden/moodle-mod_attendance#762]
We're testing the latest (2024072400) plugin version on our. test server (Moodle 4.4+ (Build: 20240425)).  

When we Save and Display the following error is thrown. Is anyone else seeing this?

Exception - core_courseformat\hook\after_cm_name_edited::__construct(): Argument #2 ($newname) must be of type string, null given, called in [dirroot]/course/modlib.php on line 733

[More information about this error](https://docs.moodle.org/404/en_us/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 36 of /course/format/classes/hook/after_cm_name_edited.php: TypeError thrown
line 733 of /course/modlib.php: call to core_courseformat\hook\after_cm_name_edited->__construct()
line 183 of /course/modedit.php: call to update_moduleinfo()

**Comment by danmarsden** [comment]
I haven't been able to reproduce this and it's not showing up in the behat tests on the repo either.

Do you have any other plugins on your site or custom course formats that might be causing this? - does it happen when you try to add plugins for other 3rd party plugins? - can you try upgrading to the latest stable release of Moodle 4.4 to see if that improves anything?

**Comment by krajewsk** [comment]
Thanks Dan. It does look like it could be another plugin interfering with the save. When I remove one other plugin the save works. We have over 70 non-core plugins running.
