### ISSUE TITLE
Attendance Register Report not pulling through custom fields data

### ISSUE THREAD

**Issue by ecottis** [danmarsden/moodle-mod_attendance#763]
When Looking at the Attendance Register Report t t shows columns for 2nd email address and learner status (custom fields.  But it's not pulling through from the learner record.  The data is in there, but just not showing.   However it shows whsn you export the registers

Can you take a look at this please. and update we are runnning on Moodle Version 4.3.3 (Build: 20240212)and attendance version 2024042203

![Attendance Register Report not polulating Screenshot 2024-08-15 093234](https://github.com/user-attachments/assets/254569f6-7698-4f52-9ca4-8c225b11a4f9)

Thanks

**Comment by danmarsden** [comment]
can you please set the debugging level to developer and turn display errors on to see if it's generating any debugging messages on the page that might show what's going on there?

**Comment by danmarsden** [comment]
I've just checked this on my local version and it seems to work fine for me - do you have any custom field types in use or custom code that could be causing this? - have you checked to see if something in your theme is hiding the text on the page inside those columns too?

thanks,

**Comment by ecottis** [comment]
Hi I've run the developer debugging with no errors showing.    I also took all the  custom CSS and changed the theme to Boost and cleared the Cash with not change to the output 
The cusome fuield in question are as follows:
![Screenshot Custom Field 2](https://github.com/user-attachments/assets/fd63137d-607b-4bda-a586-6fc5c3a46acd)
![Screenshot Custom Field 1](https://github.com/user-attachments/assets/9526462f-9c25-4157-9540-533ea356e7fa)

**Comment by ecottis** [comment]
Ive changed the setting for the debug messgaes and got the follwing 
Warning: Undefined property: stdClass::$profile_field_secondaryemail in /home/ebabac60/tutoring.pathwayskillszone.ac.uk/mod/attendance/classes/output/renderer.php on line 2232

Warning: Undefined property: stdClass::$profile_field_learnerstatus in /home/ebabac60/tutoring.pathwayskillszone.ac.uk/mod/attendance/classes/output/renderer.php on line 2232

Warning: Undefined property: stdClass::$profile_field_secondaryemail in /home/ebabac60/tutoring.pathwayskillszone.ac.uk/mod/attendance/classes/output/renderer.php on line 2232

Warning: Undefined property: stdClass::$profile_field_learnerstatus in /home/ebabac60/tutoring.pathwayskillszone.ac.uk/mod/attendance/classes/output/renderer.php on line 2232

Warning: Undefined property: stdClass::$profile_field_secondaryemail in /home/ebabac60/tutoring.pathwayskillszone.ac.uk/mod/attendance/classes/output/renderer.php on line 2232

Warning: Undefined property: stdClass::$profile_field_learnerstatus in /home/ebabac60/tutoring.pathwayskillszone.ac.uk/mod/attendance/classes/output/renderer.php on line 2232

Warning: Undefined property: stdClass::$profile_field_secondaryemail in /home/ebabac60/tutoring.pathwayskillszone.ac.uk/mod/attendance/classes/output/renderer.php on line 2232

Warning: Undefined property: stdClass::$profile_field_learnerstatus in /home/ebabac60/tutoring.pathwayskillszone.ac.uk/mod/attendance/classes/output/renderer.php on line 2232

Warning: Undefined property: stdClass::$profile_field_secondaryemail in /home/ebabac60/tutoring.pathwayskillszone.ac.uk/mod/attendance/classes/output/renderer.php on line 2232

Warning: Undefined property: stdClass::$profile_field_learnerstatus in /home/ebabac60/tutoring.pathwayskillszone.ac.uk/mod/attendance/classes/output/renderer.php on line 2232

**Comment by ecottis** [comment]
I changed the setting for the debug messages and got the following  errors:

Warning: Undefined property: stdClass::$profile_field_secondaryemail in /tutoring.pathwayskillszone.ac.uk/mod/attendance/classes/output/renderer.php on line 2232

Warning: Undefined property: stdClass::$profile_field_learnerstatus in /tutoring.pathwayskillszone.ac.uk/mod/attendance/classes/output/renderer.php on line 2232

**Comment by danmarsden** [comment]
I haven't been able to reproduce this so I'm flagging it as closed - very happy to re-open it if someone else is able to reproduce and find where the issue is occurring and can point to it being a bug in the moodle code.

Basically the code uses the same core process for attaching user profile field data to the user record - it's possible something related to a php version could be getting in the way here too.
