### ISSUE TITLE
Exporting attendance lists - bug editing-teacher

### ISSUE THREAD

**Issue by r1ik** [danmarsden/moodle-mod_attendance#765]
Hello,
I'm facing a bug when exporting attendance lists. When the user is an editing-teacher, he get this error :
Exception : array_keys(): Argument#1($array) must be type array, null given.

I use the 2024072400 plugin version, and 4.4 Moodle version (20240524)

Do i hav to edit the rights of this role ?
Thank you,

**Comment by danmarsden** [comment]
can you please set your debug level to "developer" with display errors on and get the full error message that is being displayed and then come back and add those details as a comment here?

**Comment by r1ik** [comment]
Hello @danmarsden 
here are the screenshots of the error page.
<img width="1524" alt="Capture d’écran 2024-09-10 à 10 06 09" src="https://github.com/user-attachments/assets/3fd4c4ca-43fa-4004-800e-eb5f8065d40c">
<img width="1309" alt="Capture d’écran 2024-09-10 à 10 02 35" src="https://github.com/user-attachments/assets/6e1c4913-53aa-40bc-9271-5f3b781cc638">

**Comment by danmarsden** [comment]
I've just pushed a fix that should prevent that fatal error - looks like the user hitting the page doesn't have access to see any groups in the course but has the ability to export the attendance but the patch now in the code should prevent the fatal error.

**Comment by r1ik** [comment]
Thanks a lot, it works fine !
