### ISSUE TITLE
Division by Zero error

### ISSUE THREAD

**Issue by kimberley-johnston** [danmarsden/moodle-mod_attendance#766]
Hi Dan,

Trying to do a status set with zero values so we can take attendance but not have it count towards an overall total. Looking at the All Sessions report for a user that has uses this status set gives an Division by zero error. Traceback is below

Ideally I'm looking for a way to have some sessions not count towards overall totals/counts. I'd been hoping the 'Include session when calculating absentee report' setting could have been extended further into Custom Reports and the All Sessions report page.

Thanks for looking :) 

Traceback:
[16-Sep-2024 11:39:52 Pacific/Auckland] Default exception handler: Exception - Division by zero Debug:
Error code: generalexceptionmessage
* line 1809 of /mod/attendance/classes/output/renderer.php: DivisionByZeroError thrown
* line 1167 of /mod/attendance/classes/output/renderer.php: call to mod_attendance\output\renderer->construct_user_allsessions_log()
* line 1103 of /mod/attendance/classes/output/renderer.php: call to mod_attendance\output\renderer->construct_user_data()
* line 495 of /lib/outputrenderers.php: call to mod_attendance\output\renderer->render_user_data()
* line 153 of /mod/attendance/view.php: call to plugin_renderer_base->render()

**Comment by danmarsden** [comment]
Thanks for that - I was able to reproduce that and have pushed a fix into the supported branches here that should sort it.
