### ISSUE TITLE
Title: Variables $hours and $minutes Used Before Declaration

### ISSUE THREAD

**Issue by eduardokraus** [danmarsden/moodle-mod_attendance#775]
The variables `$hours` and `$minutes` were used before being created or initialized, causing potential errors in the code execution.

![Captura de Tela 2024-10-24 às 14 55 44](https://github.com/user-attachments/assets/33b713b3-3620-48a1-a08f-35ee1b764576)

**Comment by danmarsden** [comment]
no plans to spend time on this as it's just an IDE warning and not a PHP error/deprecation so I'm closing as won't fix - happy for someone to send through a PR though.
