### ISSUE TITLE
Variable $mappingdata is an Array but Used as an Object

### ISSUE THREAD

**Issue by eduardokraus** [danmarsden/moodle-mod_attendance#777]
The variable `$mappingdata` is declared as an array, but it's being used as if it were an object. This can lead to unexpected behavior and errors. Ensure that array-specific methods are used, or convert it to an object if necessary.

![Captura de Tela 2024-10-24 às 15 00 39](https://github.com/user-attachments/assets/d334aa0f-7da4-4578-a97b-35b5075c7a86)

**Comment by eduardokraus** [comment]
When executing, it throws an error in FOR for trying to add an item to the Array that does not exist.

**Comment by danmarsden** [comment]
@eduardokraus I think you might have missed that this was closed automatically due to a patch that landed in the 4.5 branch - unless you're reporting that the fix didn't resolve the issue?
