### ISSUE TITLE
Verify if $this->error is a string or an array.

### ISSUE THREAD

**Issue by eduardokraus** [danmarsden/moodle-mod_attendance#778]
In the file `marksessions.php`, it is unclear whether the variable `$this->error` is being treated as a string or an array. This needs to be clarified to avoid potential issues with error handling. 

![Captura de Tela 2024-10-24 às 15 01 42](https://github.com/user-attachments/assets/1ef19559-fd39-4898-84e2-ae727ff5b16e)

**Comment by danmarsden** [comment]
no plans to spend time on this as it's just an IDE warning and not a PHP error/deprecation so I'm closing as won't fix - happy for someone to send through a PR though.
