### ISSUE TITLE
sql_concat function does not accept any parameters.

### ISSUE THREAD

**Issue by eduardokraus** [danmarsden/moodle-mod_attendance#779]
The `sql_concat` function is currently not accepting any parameters, which is preventing the concatenation of SQL queries or fields as expected. 

![Captura de Tela 2024-10-24 às 15 10 09](https://github.com/user-attachments/assets/6579494c-bfc1-41c8-bada-653ed482af35)

**Comment by danmarsden** [comment]
Please see https://moodledev.io/docs/4.5/apis/core/dml#sql_concat
