### ISSUE TITLE
`moodle_url` class not imported properly

### ISSUE THREAD

**Issue by eduardokraus** [danmarsden/moodle-mod_attendance#781]
The `moodle_url` class was never imported in the code. Therefore, it must be called with the namespace prefix `\moodle_url` to work correctly.

![Captura de Tela 2024-10-24 às 15 15 02](https://github.com/user-attachments/assets/8db99bee-19ac-4903-ad9d-d33b54b39e35)

**Comment by danmarsden** [comment]
no plans to spend time on this as it's just an IDE warning and not a PHP error/deprecation so I'm closing as won't fix - happy for someone to send through a PR though.
