### ISSUE TITLE
Double Spaces in Comments

### ISSUE THREAD

**Issue by eduardokraus** [danmarsden/moodle-mod_attendance#783]
There are occurrences of double spaces being inserted within comments. This issue affects readability and might cause minor formatting inconsistencies across the platform.

![Captura de Tela 2024-10-24 às 15 25 24](https://github.com/user-attachments/assets/409873ba-ae35-4a38-9b12-07377c958eb4)

**Comment by danmarsden** [comment]
no plans to spend time on this as it's just an IDE warning and not a PHP error/deprecation so I'm closing as won't fix - happy for someone to send through a PR though.
