### ISSUE TITLE
Code checker

### ISSUE THREAD

**Issue by eduardokraus** [danmarsden/moodle-mod_attendance#785]
FILE: /home/runner/work/moodle-mod_attendance/moodle-mod_attendance/moodle/mod/attendance/externallib.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------
 537 | WARNING | Inline comments must start with a capital letter, digit or 3-dots sequence
     |         | (moodle.Commenting.InlineComment.NotCapital)
------------------------------------------------------------------------------------------------------------------------------------

FILE: ...rk/moodle-mod_attendance/moodle-mod_attendance/moodle/mod/attendance/backup/moodle2/restore_attendance_activity_task.class.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------
 95 | WARNING | Inline comments must start with a capital letter, digit or 3-dots sequence
    |         | (moodle.Commenting.InlineComment.NotCapital)
------------------------------------------------------------------------------------------------------------------------------------

FILE: /home/runner/work/moodle-mod_attendance/moodle-mod_attendance/moodle/mod/attendance/automark.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------
 48 | WARNING | Inline comments must start with a capital letter, digit or 3-dots sequence
    |         | (moodle.Commenting.InlineComment.NotCapital)
------------------------------------------------------------------------------------------------------------------------------------

FILE: /home/runner/work/moodle-mod_attendance/moodle-mod_attendance/moodle/mod/attendance/tests/generator/lib.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------------------------
 [19](https://github.com/test-moodle/moodle-mod_attendance/actions/runs/11504627504/job/32024530929#step:9:20) | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
    |         | (moodle.Commenting.InlineComment.InvalidEndChar)
 47 | WARNING | Implicitly marking a parameter as nullable is deprecated since PHP 8.4. Update the type to be explicitly nullable
    |         | instead. Found implicitly nullable parameter: $options.
    |         | (PHPCompatibility.FunctionDeclarations.RemovedImplicitlyNullableParam.Deprecated)
------------------------------------------------------------------------------------------------------------------------------------

FILE: /home/runner/work/moodle-mod_attendance/moodle-mod_attendance/moodle/mod/attendance/defaultstatus.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------
 47 | WARNING | Inline comments must start with a capital letter, digit or 3-dots sequence
    |         | (moodle.Commenting.InlineComment.NotCapital)
------------------------------------------------------------------------------------------------------------------------------------

FILE: /home/runner/work/moodle-mod_attendance/moodle-mod_attendance/moodle/mod/attendance/preferences.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------
 66 | WARNING | Inline comments must start with a capital letter, digit or 3-dots sequence
    |         | (moodle.Commenting.InlineComment.NotCapital)
------------------------------------------------------------------------------------------------------------------------------------

FILE: /home/runner/work/moodle-mod_attendance/moodle-mod_attendance/moodle/mod/attendance/lang/en/attendance.php
------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 4 WARNINGS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------------------------
 585 | WARNING | Unexpected comment found. Auto-fixing will not work after this comment
     |         | (moodle.Files.LangFilesOrdering.UnexpectedComment)
 585 | WARNING | Inline comments must start with a capital letter, digit or 3-dots sequence
     |         | (moodle.Commenting.InlineComment.NotCapital)
 585 | WARNING | Inline comments must end in full-stops, exclamation marks, or question marks
     |         | (moodle.Commenting.InlineComment.InvalidEndChar)
 586 | WARNING | Unexpected comment found. Auto-fixing will not work after this comment
     |         | (moodle.Files.LangFilesOrdering.UnexpectedComment)
------------------------------------------------------------------------------------------------------------------------------------

**Comment by danmarsden** [comment]
Thanks, I'm closing this off as it's already reported in the github actions, but feel free to submit a pull request with any improvements.
