### ISSUE TITLE
[Error] Plugin does not declare its version [null]

### ISSUE THREAD

**Issue by zishanj** [danmarsden/moodle-mod_attendance#786]
Receiving this error while updating plugin to latest 2024072400:

> [Error] Plugin does not declare its version [null]

I have checked the plugin version.php file and it does mention plugin version. 

My moodle version is 4.4.1.

**Comment by danmarsden** [comment]
sounds like you might have the file permissions wrong for your version.php file - not much I can help with here though - If you're still having trouble, try asking for further help in the community forums on moodle.org
