### ISSUE TITLE
Creation of dynamic property mod_attendance\output\user_data::$summaries is deprecated

### ISSUE THREAD

**Issue by ziegenberg** [danmarsden/moodle-mod_attendance#791]
I get this error message for this file: `output/user_data.php:91`

https://github.com/danmarsden/moodle-mod_attendance/blob/b03d219b2972d98b0bf0b139f482b24f04f04838/classes/output/user_data.php#L88-L94

```txt
undefined: undefined
1. ... (/opt/moodle/tuwel/web/mod/attendance/classes/output/user_data.php:91)
2. mod_attendance\output\user_data::__construct (/opt/moodle/tuwel/web/mod/attendance/view.php:105)
```

Should this maybe be a `$this->summary = [];` instead?  See also line 104.

**Comment by danmarsden** [comment]
thanks for the report - you're right that should be "summary" so I've just pushed a fix for that, but I'm suspicious that the data isn't actually used on the all sessions page so maybe it doesn't even need to be calculating it... something for another day....
