### ISSUE TITLE
Moodle External Database pluging

### ISSUE THREAD

**Issue by frs2022** [danmarsden/moodle-mod_attendance#794]
Dear All, 

we are using external database plugging enrollment method to synchronize students and courses enrollment from Eduwave platform , we have already add Synchronise external database enrolments task in moodle and we have disabled since two weeks, but suddenly on 25 November some students and teachers were suspended from courses in Moodle , and logs show User enrolment updated. Can you explain how this is happening since we disable the Synchronise external database enrolments task in moodle how they are affected?

**Comment by danmarsden** [comment]
you are in the wrong place... the right place is: https://moodle.org/mod/forum/discuss.php?d=464083 - good luck!
