### ISSUE TITLE
Expired self enrolments prevent attendance taking when active manual enrolments exist

### ISSUE THREAD

**Issue by barrysspace** [danmarsden/moodle-mod_attendance#81]
Steps to reproduce:
1. Add self enrolment method to a course (set to expire before attendance session)
2. As a student self enrol on the course
3. Create an attendance session which starts after the self enrolment expires
4. Manually enrol the student on the same course with no expiry date
5. Take attendance for the session
6. The student above will be greyed out on the attendance register with "User enrolment ends ## ## #### (date)"

**Comment by danmarsden** [comment]
Thanks heaps Barry - tested and merged!
