### ISSUE TITLE
Responsiveness for table views

### ISSUE THREAD

**Issue by Kathrin84** [danmarsden/moodle-mod_attendance#85]
As we implemented a responsive theme within our moodle, it showed up that the displaying of the tables in your plugin is not responsive.
I just wanted to request, if there could be development towards responsiveness?
![attendance_listview_on_smart_device](https://cloud.githubusercontent.com/assets/4711883/7085311/db0d7c46-df75-11e4-8501-ed62298423fb.png)

**Comment by danmarsden** [comment]
Hi There,

Thanks for the report.

I support and maintain this plugin as a volunteer. Unfortunately my volunteer time is in very high demand across the various plugins and core Moodle code I support and leaves me with no time for improvement or feature work on the attendance plugin so I am only able to volunteer time to work on serious bugs and ensure that it works in each new Moodle release.

Most of the improvements/feature development of the Attendance module over the past 24 months has come from community contributed code. I'm happy to review any community patches for inclusion in the core code-base.

I work for the Moodle Partner Catalyst IT and we can provide commercial development services (including improvements to the attendance module.)

thanks,

**Comment by danmarsden** [comment]
we've improved the responsiveness for the student view - haven't done this for teachers yet but this issue doesn't give any specifics on areas that would be good to improve so I'm closing it for now. If there are particular screens that could be useful for other users to improve, please create a specific issue with relevant screenshots. Thanks.
