### ISSUE TITLE
Clicking 'OK' button throwing errors

### ISSUE THREAD

**Issue by btindell** [danmarsden/moodle-mod_attendance#87]
Hello,

We have stumbled across an issue with the plugin. 
To replicate:
1) go to the "Sessions" tab. 
2) click on the 'OK' button in the lower-right hand corner
3) This will throw an exception like: [Fri May 01 11:42:05.795219 2015] [:error] [pid 1995] [client 127.0.0.1:44992] PHP Fatal error:  Call to a member function display() on a non-object in /home/btindell/prj/moodle/git/docs/mod/attendance/sessions.php on line 178
4) This will bring the user to a page that has nothing on it. Please see attached screenshot.

Hopefully this can get fixed before the next release! 

Thanks!
Ben 
![screen shot 2015-05-01 at 11 53 51 am](https://cloud.githubusercontent.com/assets/7874245/7433618/e2ca2112-eff8-11e4-93c4-263a78f6ea03.png)

**Comment by danmarsden** [comment]
pushed a commit that tides this up a little bit. The long term solution would be to modify that form so that it doesn't allow a submit action on the empty "choose" option and move to a better Javascript based form handler.
