### ISSUE TITLE
Feature request:  API for Attendance

### ISSUE THREAD

**Issue by trevoriancox** [danmarsden/moodle-mod_attendance#88]
Is anyone else interested in this? An API would allow Moodle Mobile or custom apps to provide more streamlined attendance taking by teachers using their mobile devices.

**Comment by danmarsden** [comment]
Hi Trevor,

I took over maintenance of the Attendance plugin when the original developer moved on as we had a few clients who use the plugin and paid for my time to update the code to work with newer Moodle versions. I still provided limited support/maintenance on the plugin as a volunteer but I have a large number of plugins and core Moodle code that I am responsible for so I don't have time for any feature work on the attendance plugin unless the work is funded.

There are a number of areas of the attendance code that could do with a re-structure to make it easier for other custom apps to re-use the same functionality and I'm always happy to review 3rd party patches for inclusion in the core codebase. As long as the code follows the standard Moodle coding guidelines and doesn't introduce any performance/security or maintenance issues I'm usually pretty happy to integrate the changes.

**Comment by drjosephbaxter** [comment]
Hi Trevor,

It might be worth starting a discussion on the attendance forum 

https://moodle.org/mod/forum/view.php?id=741

as a lot more of the plugins users monitor that forum than this repo (tends to be just us developers)

if you can get enough users together maybe you can get enough funding together to get a developer to do the work for you.

Here at UoN we contribute changes regularly to the plugin that Dan reviews and integrates for us.

**Comment by trevoriancox** [comment]
Thanks Dan and Joseph. Yes, there is already some relevant discussion in the forum so I will start there!

**Comment by danmarsden** [comment]
Hi Trevor - your first post on moodle.org got you flagged as a spammer (whoops) - let me know if you need help re-enabling it again.

Your post got flagged as spam due to the link you included in the bottom of the post which was outside the context of the discussion. As this was your first ever post in the community it made you look like a spammer. Often spammers will write some generic response to a post and include a url to an un-related site.

More info on the moodle.org code of conduct is here:
https://moodle.org/mod/page/view.php?id=7080

This policy states that urls in signatures are not allowed.

**Comment by trevoriancox** [comment]
Hi Dan,

Thank you for the email, and yes, I need help. :) I am not able to log in nor reset my password. I'll be sure not to include any URL's in my future posts!

user:  "appazur"

Thanks,
Trevor

**Comment by danmarsden** [comment]
I've just created an issue for the team here:
https://tracker.moodle.org/browse/MDLSITE-4053

hopefully someone should be in touch soon to let you know that it's been released! :-)

**Comment by wildgirl** [comment]
Hi Trevor,
Sorry for your moodle.org account being suspended (and thanks Dan for letting us know). It is now un-suspended, so you can log in again and post.

**Comment by danmarsden** [comment]
re-reading through this again and I don't think it is specific enough to stand alone as a feature request. 

"API" is too broad. @danielneis started to write a webservice call here:
https://github.com/danmarsden/moodle-mod_attendance/pull/90

but he has not had a chance to finish it off.

The IPAL module folks may also be interested in converting some of their code to using any web-services code we end up creating.
