### ISSUE TITLE
No 2.4 Stable

### ISSUE THREAD

**Issue by CobaltBlueDW** [danmarsden/moodle-mod_attendance#89]
Not really a big deal just:
The https://github.com/danmarsden/moodle-mod_attendance/tree/MOODLE_24-26_STABLE branch requires Moodle 2.6.2, so it doesn't actually work for 2.4.x or 2.5.x sites.

**Comment by danmarsden** [comment]
the 2.4-2.6 branch has a "requires" version of "2013040500" which should support 2.5.x sites but it does look like I dropped support for 2.4 in that branch back in August 2013

Moodle 2.6 and all earlier versions are no longer supported by Moodle HQ so I don't plan to make any changes to those versions of the attendance plugin either. People that need to work with older versions can also obtain compatible versions for older Moodle releases from the moodle.org plugins db.

Closing this as I don't plan to do anything here as the versions are no longer officially supported. Thanks.
